# Coding Practice Session 2
## Examining Data Types and Structures

In [78]:
import pandas as pd
import numpy as np
import seaborn as sns
import dateparser

In [4]:
np_int = np.int32(78)
np_int

np.int32(78)

In [5]:
np_float = np.float16(-2.6)
np_float

np.float16(-2.6)

In [6]:
pd_series = pd.Series([1, 2, 3])

In [7]:
pd_series.dtype

dtype('int64')

### Common Data Types

In [8]:
np.array([1, 2, 3], dtype=np.int16)

array([1, 2, 3], dtype=int16)

In [9]:
np.array([1.0, 2.56, -1.36], dtype=np.float32)

array([ 1.  ,  2.56, -1.36], dtype=float32)

In [10]:
pd.Series([1, 2, 3], dtype="uint8")

0    1
1    2
2    3
dtype: uint8

In [11]:
pd.Series([1.0, 3.14, 2.781], dtype="float32")

0    1.000
1    3.140
2    2.781
dtype: float32

In [12]:
np.array(["apple", "orange", "kiwi"], dtype="U")

array(['apple', 'orange', 'kiwi'], dtype='<U6')

In [13]:
pd.Series(["apple", "orange", "kiwi"], dtype="string")

0     apple
1    orange
2      kiwi
dtype: string

In [14]:
np.array([False, True, True]).dtype

dtype('bool')

In [15]:
pd.Series([False, False, True, False]).dtype

dtype('bool')

In [16]:
np.array(["2026-08-29", "2025-11-18"], dtype="datetime64")

array(['2026-08-29', '2025-11-18'], dtype='datetime64[D]')

In [18]:
pd.to_datetime(["2026-08-29", "2025-11-18"]).dtype

dtype('<M8[us]')

In [19]:
pd.Series(["A", "A", "C", "B", "A", "B", "C"], dtype="category")

0    A
1    A
2    C
3    B
4    A
5    B
6    C
dtype: category
Categories (3, str): ['A', 'B', 'C']

In [20]:
complex_arr = np.array([1 + 2j, 3 + 4j])
complex_arr

array([1.+2.j, 3.+4.j])

In [21]:
complex_arr.dtype

dtype('complex128')

In [24]:
pd.Series([1, 2, None], dtype="Int8")

0       1
1       2
2    <NA>
dtype: Int8

Note the uppercase **I**

### Examining and Verifying Data Types

In [26]:
df_titanic = sns.load_dataset("titanic")

In [27]:
df_taxis = sns.load_dataset("taxis")

In [28]:
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [29]:
df_taxis.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [30]:
df_titanic.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [31]:
df_taxis.dtypes

pickup             datetime64[us]
dropoff            datetime64[us]
passengers                  int64
distance                  float64
fare                      float64
tip                       float64
tolls                     float64
total                     float64
color                         str
payment                       str
pickup_zone                   str
dropoff_zone                  str
pickup_borough                str
dropoff_borough               str
dtype: object

In [32]:
df_titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [33]:
df_taxis.info()

<class 'pandas.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[us]
 1   dropoff          6433 non-null   datetime64[us]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   str
 9   payment          6389 non-null   str
 10  pickup_zone      6407 non-null   str
 11  dropoff_zone     6388 non-null   str
 12  pickup_borough   6407 non-null   str
 13  dropoff_borough  6388 non-null   str
dtypes: datetime64[us](2), float64(5), int64(1), str(6)
memory usage: 703.7 KB

In [34]:
df_titanic["age"].dtype

dtype('float64')

In [35]:
df_taxis.total.dtype

dtype('float64')

In [37]:
df_titanic["age"].describe().round(decimals=2)

count    714.00
mean      29.70
std       14.53
min        0.42
25%       20.12
50%       28.00
75%       38.00
max       80.00
Name: age, dtype: float64

In [38]:
type(df_titanic["age"])

pandas.Series

In [39]:
df_taxis.total.describe()

count    6433.000000
mean       18.517794
std        13.815570
min         1.300000
25%        10.800000
50%        14.160000
75%        20.300000
max       174.820000
Name: total, dtype: float64

In [40]:
df_titanic["age"].isnull().sum()

np.int64(177)

In [41]:
len(df_titanic["age"])

891

In [42]:
pd.to_numeric(df_titanic["age"], errors="coerce")

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [43]:
df_titanic["sex"].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [45]:
df_titanic["embarked"].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [46]:
# standardizing categories
df_titanic["sex"].str.lower().str.strip()

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 891, dtype: str

In [50]:
df_titanic.loc[0, "age"]

np.float64(22.0)

In [51]:
df_taxis["pickup"].dtype

dtype('<M8[us]')

In [52]:
df_taxis["pickup"].head()

0   2019-03-23 20:21:09
1   2019-03-04 16:11:55
2   2019-03-27 17:53:01
3   2019-03-10 01:23:59
4   2019-03-30 13:27:42
Name: pickup, dtype: datetime64[us]

In [53]:
df_titanic.select_dtypes(include=["int64", "float64"])

     survived  pclass   age  sibsp  parch     fare
0           0       3  22.0      1      0   7.2500
1           1       1  38.0      1      0  71.2833
2           1       3  26.0      0      0   7.9250
3           1       1  35.0      1      0  53.1000
4           0       3  35.0      0      0   8.0500
..        ...     ...   ...    ...    ...      ...
886         0       2  27.0      0      0  13.0000
887         1       1  19.0      0      0  30.0000
888         0       3   NaN      1      2  23.4500
889         1       1  26.0      0      0  30.0000
890         0       3  32.0      0      0   7.7500

[891 rows x 6 columns]

In [54]:
df_titanic.select_dtypes(include=["string"])

        sex embarked    who  embark_town alive
0      male        S    man  Southampton    no
1    female        C  woman    Cherbourg   yes
2    female        S  woman  Southampton   yes
3    female        S  woman  Southampton   yes
4      male        S    man  Southampton    no
..      ...      ...    ...          ...   ...
886    male        S    man  Southampton    no
887  female        S  woman  Southampton   yes
888  female        S  woman  Southampton    no
889    male        C    man    Cherbourg   yes
890    male        Q    man   Queenstown    no

[891 rows x 5 columns]

In [56]:
df_titanic["is_adult"] = df_titanic["age"] > 18
df_titanic["is_adult"]

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: is_adult, Length: 891, dtype: bool

In [57]:
df_titanic["is_adult"].dtype

dtype('bool')

In [58]:
df_titanic.memory_usage()

Index           132
survived       7128
pclass         7128
sex            7128
age            7128
sibsp          7128
parch          7128
fare           7128
embarked       7128
class          1023
who            7128
adult_male      891
deck           1247
embark_town    7128
alive          7128
alone           891
is_adult        891
dtype: int64

In [59]:
df_taxis.memory_usage()

Index                132
pickup             51464
dropoff            51464
passengers         51464
distance           51464
fare               51464
tip                51464
tolls              51464
total              51464
color              51464
payment            51464
pickup_zone        51464
dropoff_zone       51464
pickup_borough     51464
dropoff_borough    51464
dtype: int64

In [60]:
df_taxis.info()

<class 'pandas.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[us]
 1   dropoff          6433 non-null   datetime64[us]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   str
 9   payment          6389 non-null   str
 10  pickup_zone      6407 non-null   str
 11  dropoff_zone     6388 non-null   str
 12  pickup_borough   6407 non-null   str
 13  dropoff_borough  6388 non-null   str
dtypes: datetime64[us](2), float64(5), int64(1), str(6)
memory usage: 703.7 KB

In [62]:
df_taxis.memory_usage().sum() / 1e3

np.float64(720.628)

In [63]:
df_titanic.loc[1, "age"] = np.nan

In [65]:
df_titanic["age"].head()

0    22.0
1     NaN
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

### Handling Mixed Categorical Data

In [69]:
df_titanic.loc[0, "embarked"] = "Southampton"
df_titanic.loc[1, "embarked"] = "Cherbourg"
df_titanic.loc[2, "embarked"] = np.nan

In [70]:
df_titanic["embarked"].unique()

<StringArray>
['Southampton', 'Cherbourg', nan, 'S', 'Q', 'C']
Length: 6, dtype: str

In [ ]:
def clean_categorical_column(series):
    mapping = {"Southampton": "S", "Cherbourg": "C", "Queenstown": "Q"}

    cleaned_series = series.map(lambda x: mapping.get(x, x)).astype("category")
    return cleaned_series

In [75]:
clean_data = clean_categorical_column(df_titanic["embarked"])
clean_data

0        S
1        C
2      NaN
3        S
4        S
      ...
886      S
887      S
888      S
889      C
890      Q
Name: embarked, Length: 891, dtype: category
Categories (3, str): ['C', 'Q', 'S']

In [76]:
clean_data.unique()

['S', 'C', NaN, 'Q']
Categories (3, str): ['C', 'Q', 'S']

### Handling Mixed Data Types

In [77]:
df_taxis["pickup"] = "1912-04-10"
df_taxis.loc[0, "pickup"] = "10/04/1912"
df_taxis.loc[1, "pickup"] = "April 10, 1912"
df_taxis.loc[2, "pickup"] = np.nan

In [79]:
def convert_to_iso(date_string: str):
    parsed_date = dateparser.parse(date_string)

    if parsed_date is None:
        return "Invalid date format"

    iso_date = parsed_date.isoformat()
    return iso_date

In [83]:
converted_date = convert_to_iso("July 26th, 2026")
converted_date

'2026-07-26T00:00:00'

In [84]:
type(converted_date)

str

In [92]:
def clean_date_column(series):
    cleaned_series = series.apply(lambda x: convert_to_iso(str(x)))
    return cleaned_series.astype("datetime64[s]")

In [94]:
clean_date_column(df_taxis["pickup"])

0      1912-10-04
1      1912-04-10
2      2026-08-29
3      1912-04-10
4      1912-04-10
          ...
6428   1912-04-10
6429   1912-04-10
6430   1912-04-10
6431   1912-04-10
6432   1912-04-10
Name: pickup, Length: 6433, dtype: datetime64[s]

In [95]:
df_titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            178
sibsp            0
parch            0
fare             0
embarked         3
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
is_adult         0
dtype: int64

In [ ]:
sample_data = pd.DataFrame(
    {
        "transaction_date": ["2026-01-01", "2026-01-02", "2026-01-03"],
        "amount": ["$100,000", "$200,000", "$300,000"],
    }
)

In [100]:
sample_data.to_csv("../data/sample_data.csv", index=False)

In [101]:
def parse_currency(currency_str):
    return float(currency_str.replace("$", "").replace(",", ""))

In [103]:
sample_data = pd.read_csv(
    "../data/sample_data.csv",
    parse_dates=["transaction_date"],
    converters={"amount": parse_currency}
)

In [104]:
sample_data

  transaction_date    amount
0       2026-01-01  100000.0
1       2026-01-02  200000.0
2       2026-01-03  300000.0

In [105]:
sample_data.dtypes

transaction_date    datetime64[us]
amount                     float64
dtype: object

In [107]:
df_titanic.duplicated().sum()

np.int64(107)

In [109]:
df_titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'is_adult'],
      dtype='str')

In [111]:
expected_sex_categories = ["male", "female"]

In [113]:
df_titanic["sex"].isin(expected_sex_categories).all()

np.True_