# Pandas Exercise Session 05

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("data/winequality-red.csv", sep=";")

In [5]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [6]:
df["free sulfur dioxide"].dtype

dtype('float64')

In [7]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [8]:
df.index.dtype

dtype('int64')

In [9]:
df["quality"].astype("float32")

0       5.0
1       5.0
2       5.0
3       6.0
4       5.0
       ...
1594    5.0
1595    6.0
1596    6.0
1597    5.0
1598    6.0
Name: quality, Length: 1599, dtype: float32

In [11]:
df.isnull().any()

fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                      False
sulphates               False
alcohol                 False
quality                 False
dtype: bool

In [14]:
pd.set_option("display.max_rows", 8)

In [16]:
reviews = pd.read_csv("data/winemag-data-130k-v2.csv", index_col=0)

In [17]:
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [18]:
reviews["price"].dtype

dtype('float64')

In [20]:
reviews.dtypes.value_counts()

object     11
int64       1
float64     1
Name: count, dtype: int64

In [22]:
reviews["points"].astype("float32")

0         87.0
1         87.0
2         87.0
3         87.0
          ...
129967    90.0
129968    90.0
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float32

In [23]:
pd.isnull(reviews["country"])

0         False
1         False
2         False
3         False
          ...
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [24]:
reviews[pd.isnull(reviews["country"])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
4243,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking
9509,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ
129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [25]:
reviews["region_1"].fillna("Unknown")

0                        Etna
1                     Unknown
2           Willamette Valley
3         Lake Michigan Shore
                 ...
129967                 Oregon
129968                 Alsace
129969                 Alsace
129970                 Alsace
Name: region_1, Length: 129971, dtype: object

In [26]:
reviews["region_1"].fillna("Unknown").value_counts()

region_1
Unknown                               21247
Napa Valley                            4480
Columbia Valley (WA)                   4124
Russian River Valley                   3091
                                      ...
Sonoma County-Santa Barbara County        1
Del Veneto                                1
Bardolino Superiore                       1
Paestum                                   1
Name: count, Length: 1230, dtype: int64

In [27]:
reviews["region_1"].dropna().value_counts()

region_1
Napa Valley                  4480
Columbia Valley (WA)         4124
Russian River Valley         3091
California                   2629
                             ...
Nasco di Cagliari               1
Dolcetto d'Alba Superiore       1
Medrano                         1
Collioure                       1
Name: count, Length: 1229, dtype: int64

In [30]:
reviews.shape

(129971, 13)

In [32]:
reviews["taster_twitter_handle"].replace("@vossroger", "@m$Mroger")

0         @kerinokeefe
1            @m$Mroger
2          @paulgwine
3                  NaN
              ...
129967     @paulgwine
129968       @m$Mroger
129969       @m$Mroger
129970       @m$Mroger
Name: taster_twitter_handle, Length: 129971, dtype: object

In [52]:
print("Columns:\n")
for indx, column in enumerate(reviews.columns):
    print(column)
    if indx == len(reviews.columns) - 1:
        continue
    print("-" * 10)

Columns:

country
----------
description
----------
designation
----------
points
----------
price
----------
province
----------
region_1
----------
region_2
----------
taster_name
----------
taster_twitter_handle
----------
title
----------
variety
----------
winery

In [37]:
reviews["points"].dtype

dtype('int64')

In [38]:
point_strings = reviews["points"].astype("str")

In [39]:
point_strings

0         87
1         87
2         87
3         87
          ..
129967    90
129968    90
129969    90
129970    90
Name: points, Length: 129971, dtype: object

In [54]:
reviews.points.memory_usage(deep=True, index=False) / 1e6

1.039768

In [55]:
point_strings.memory_usage(deep=True, index=False) / 1e6

7.668308

In [42]:
reviews.price.isnull().sum()

np.int64(8996)

In [43]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [48]:
reviews["region_1"].fillna("Unknown").value_counts()

region_1
Unknown                               21247
Napa Valley                            4480
Columbia Valley (WA)                   4124
Russian River Valley                   3091
                                      ...
Sonoma County-Santa Barbara County        1
Del Veneto                                1
Bardolino Superiore                       1
Paestum                                   1
Name: count, Length: 1230, dtype: int64