# Pandas Exercise Session 07

In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.0'

## Essentials

In [3]:
# 1
df = pd.read_csv("data/student_depression_dataset.csv")

In [4]:
# 2
df.head(n=10)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,'Less than 5 hours',Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,'7-8 hours',Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,'Less than 5 hours',Unhealthy,'Class 12',No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,'7-8 hours',Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,'Less than 5 hours',Moderate,LLB,Yes,2.0,5.0,No,1

In [5]:
df.tail()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [6]:
# 3
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27901 non-null  str
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(7), int64(2), str(9)
memory usage: 3.8 MB

In [7]:
df.isna().any().any()

np.False_

In [8]:
# 4
df.describe().round(decimals=3)

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Depression
count,27901.000,27901.000,27901.000,27901.000,27901.000,27901.000,27901.000,27901.000,27901.000
mean,70442.149,25.822,3.141,0.000,7.656,2.944,0.001,7.157,0.585
std,40641.175,4.906,1.381,0.044,1.471,1.361,0.044,3.708,0.493
min,2.000,18.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,35039.000,21.000,2.000,0.000,6.290,2.000,0.000,4.000,0.000
50%,70684.000,25.000,3.000,0.000,7.770,3.000,0.000,8.000,1.000
75%,105818.000,30.000,4.000,0.000,8.920,4.000,0.000,10.000,1.000
max,140699.000,59.000,5.000,5.000,10.000,5.000,4.000,12.000,1.000

In [9]:
# 5
df.columns.to_list()

['id',
 'Gender',
 'Age',
 'City',
 'Profession',
 'Academic Pressure',
 'Work Pressure',
 'CGPA',
 'Study Satisfaction',
 'Job Satisfaction',
 'Sleep Duration',
 'Dietary Habits',
 'Degree',
 'Have you ever had suicidal thoughts ?',
 'Work/Study Hours',
 'Financial Stress',
 'Family History of Mental Illness',
 'Depression']

In [10]:
df.columns.str.lower().str.replace(" ", "_")

Index(['id', 'gender', 'age', 'city', 'profession', 'academic_pressure',
       'work_pressure', 'cgpa', 'study_satisfaction', 'job_satisfaction',
       'sleep_duration', 'dietary_habits', 'degree',
       'have_you_ever_had_suicidal_thoughts_?', 'work/study_hours',
       'financial_stress', 'family_history_of_mental_illness', 'depression'],
      dtype='str')

In [11]:
df.columns = df.columns.str.lower()

In [12]:
df.head()

,id,gender,age,city,profession,academic pressure,work pressure,cgpa,study satisfaction,job satisfaction,sleep duration,dietary habits,degree,have you ever had suicidal thoughts ?,work/study hours,financial stress,family history of mental illness,depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0

## Selection and Filtering

In [13]:
# 6
df.columns.to_list()

['id',
 'gender',
 'age',
 'city',
 'profession',
 'academic pressure',
 'work pressure',
 'cgpa',
 'study satisfaction',
 'job satisfaction',
 'sleep duration',
 'dietary habits',
 'degree',
 'have you ever had suicidal thoughts ?',
 'work/study hours',
 'financial stress',
 'family history of mental illness',
 'depression']

In [16]:
df_subset = df.loc[:, ["city", "profession", "degree"]]

In [17]:
df_subset

                city profession      degree
0      Visakhapatnam    Student     B.Pharm
1          Bangalore    Student         BSc
2           Srinagar    Student          BA
3           Varanasi    Student         BCA
4             Jaipur    Student      M.Tech
...              ...        ...         ...
27896          Surat    Student  'Class 12'
27897       Ludhiana    Student         MSc
27898      Faridabad    Student          MD
27899       Ludhiana    Student  'Class 12'
27900          Patna    Student         BCA

[27901 rows x 3 columns]

In [18]:
df_subset.profession.value_counts()

profession
Student                     27870
Architect                       8
Teacher                         6
'Digital Marketer'              3
'Content Writer'                2
Chef                            2
Doctor                          2
Pharmacist                      2
'Civil Engineer'                1
'UX/UI Designer'                1
'Educational Consultant'        1
Manager                         1
Lawyer                          1
Entrepreneur                    1
Name: count, dtype: int64

In [19]:
# 7
df.iloc[10:21, :5]

     id  gender   age       city profession
10   83    Male  24.0     Nagpur    Student
11   91    Male  33.0   Vadodara    Student
12   94    Male  27.0     Kalyan    Student
13  100  Female  19.0     Rajkot    Student
14  103  Female  19.0     Kalyan    Student
15  106    Male  29.0   Srinagar    Student
16  120    Male  25.0     Nashik    Student
17  132  Female  20.0  Ahmedabad    Student
18  139    Male  19.0    Chennai    Student
19  145    Male  25.0     Kalyan    Student
20  161    Male  29.0    Kolkata    Student

In [22]:
# 8
df.loc[20, ["gender", "city", "dietary habits"]] # type: ignore

gender                Male
city               Kolkata
dietary habits    Moderate
Name: 20, dtype: str

In [27]:
# 9
avg_age = df["age"].mean().round(0) # type: ignore
avg_age

np.float64(26.0)

In [30]:
df[df["age"] > avg_age]

,id,gender,age,city,profession,academic pressure,work pressure,cgpa,study satisfaction,job satisfaction,sleep duration,dietary habits,degree,have you ever had suicidal thoughts ?,work/study hours,financial stress,family history of mental illness,depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,'Less than 5 hours',Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,'7-8 hours',Healthy,BSc,No,1.0,2.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27895,140684,Male,31.0,Lucknow,Student,2.0,0.0,7.27,5.0,0.0,'7-8 hours',Moderate,B.Com,Yes,6.0,1.0,Yes,0
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [33]:
# 10
df["dietary habits"].value_counts()

dietary habits
Unhealthy    10317
Moderate      9921
Healthy       7651
Others          12
Name: count, dtype: int64

In [38]:
mask = (df["dietary habits"] == "Unhealthy") & (df["study satisfaction"] >= 3)

In [39]:
mask

0        False
1        False
2        False
3        False
4        False
         ...
27896     True
27897    False
27898     True
27899    False
27900    False
Length: 27901, dtype: bool

In [40]:
df[mask]

,id,gender,age,city,profession,academic pressure,work pressure,cgpa,study satisfaction,job satisfaction,sleep duration,dietary habits,degree,have you ever had suicidal thoughts ?,work/study hours,financial stress,family history of mental illness,depression
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,'Less than 5 hours',Unhealthy,'Class 12',No,0.0,1.0,Yes,0
13,100,Female,19.0,Rajkot,Student,2.0,0.0,8.52,4.0,0.0,'Less than 5 hours',Unhealthy,'Class 12',No,6.0,2.0,Yes,0
22,166,Female,25.0,Ahmedabad,Student,3.0,0.0,5.57,3.0,0.0,'More than 8 hours',Unhealthy,MSc,Yes,10.0,5.0,No,1
24,173,Male,18.0,Bangalore,Student,4.0,0.0,7.10,3.0,0.0,'More than 8 hours',Unhealthy,'Class 12',Yes,11.0,5.0,Yes,1
27,193,Male,25.0,Lucknow,Student,3.0,0.0,7.25,3.0,0.0,'More than 8 hours',Unhealthy,M.Ed,Yes,10.0,5.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27885,140597,Female,19.0,Mumbai,Student,2.0,0.0,9.21,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,3.0,2.0,No,0
27886,140601,Female,22.0,Jaipur,Student,5.0,0.0,9.25,4.0,0.0,'More than 8 hours',Unhealthy,BBA,Yes,8.0,3.0,No,1
27891,140645,Female,28.0,Thane,Student,4.0,0.0,7.77,3.0,0.0,'Less than 5 hours',Unhealthy,MSc,No,2.0,5.0,No,1
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0