# Pandas Exercise Session 04

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset("iris")

In [4]:
# 1
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [8]:
df.describe().round(decimals=2)

       sepal_length  sepal_width  petal_length  petal_width
count        150.00       150.00        150.00       150.00
mean           5.84         3.06          3.76         1.20
std            0.83         0.44          1.77         0.76
min            4.30         2.00          1.00         0.10
25%            5.10         2.80          1.60         0.30
50%            5.80         3.00          4.35         1.30
75%            6.40         3.30          5.10         1.80
max            7.90         4.40          6.90         2.50

In [13]:
# 2
df.rename(columns=lambda name: name.replace("_", " ").strip().title(), inplace=True)
df

     Sepal Length  Sepal Width  Petal Length  Petal Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
# 3
df["Species"].nunique()

3

In [17]:
df["Species"].value_counts()

Species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [30]:
# 4
df.loc[df["Species"] == "virginica", "Sepal Width"].mean()

np.float64(2.974)

In [31]:
# 5
condition = (df["Petal Length"] > 1.5) & (df["Petal Length"] < 5)
df[condition]

     Sepal Length  Sepal Width  Petal Length  Petal Width    Species
5             5.4          3.9           1.7          0.4     setosa
11            4.8          3.4           1.6          0.2     setosa
18            5.7          3.8           1.7          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
..            ...          ...           ...          ...        ...
121           5.6          2.8           4.9          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica

[67 rows x 5 columns]

In [33]:
condition = df["Petal Length"].between(1.55, 5, inclusive="neither")
df[condition]

     Sepal Length  Sepal Width  Petal Length  Petal Width    Species
5             5.4          3.9           1.7          0.4     setosa
11            4.8          3.4           1.6          0.2     setosa
18            5.7          3.8           1.7          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
..            ...          ...           ...          ...        ...
121           5.6          2.8           4.9          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica

[67 rows x 5 columns]

In [40]:
# 6
df.loc[df["Sepal Length"].idxmax()]

Sepal Length          7.9
Sepal Width           3.8
Petal Length          6.4
Petal Width           2.0
Species         virginica
Name: 131, dtype: object

In [42]:
df.loc[df["Sepal Length"].idxmax(), "Species"]

'virginica'

In [37]:
df["Sepal Length"].max()

7.9

In [43]:
# 7
df.to_csv("data/custom_iris.csv")