# Pandas Exercise Session 06

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("data/winemag-data-130k-v2.csv", index_col=0)

In [6]:
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [16]:
df.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

In [13]:
df["points"].value_counts(ascending=False)

points
88     17207
87     16933
90     15410
86     12600
89     12226
91     11359
92      9613
85      9530
93      6489
84      6480
94      3758
83      3025
82      1836
95      1535
81       692
96       523
80       397
97       229
98        77
99        33
100       19
Name: count, dtype: int64

In [15]:
df.groupby("points")["price"].min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [ ]:
df.groupby(["country", "province"]).apply(
    lambda x: x.loc[x["points"].idxmax()], include_groups=False
)

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price                 region_1 region_2  \
country   province
Argentina Mendoza Province  120.0                  Mendoza      NaN
          Other              90.0                    Salta      NaN
Armenia   Armenia            15.0                      NaN      NaN
Australia Australia Other    15.0  South Eastern Australia      NaN
          New South Wales    32.0          New South Wales      NaN
...                           ...                      ...      ...
Uruguay   Juanico            45.0                      NaN      NaN
          Montevideo         60.0                      NaN      NaN
          Progreso           46.0                      NaN      NaN
          San Jose           50.0                      NaN      NaN
          Uruguay            22.0                      NaN      NaN

                                  taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province  Michael Schachner           @wineschach
          Other             Michael Schachner           @wineschach
Armenia   Armenia               Mike DeSimone        @worldwineguys
Australia Australia Other                 NaN                   NaN
          New South Wales      Joe Czerwinski                @JoeCz
...                                       ...                   ...
Uruguay   Juanico           Michael Schachner           @wineschach
          Montevideo        Michael Schachner           @wineschach
          Progreso          Michael Schachner           @wineschach
          San Jose          Michael Schachner           @wineschach
          Uruguay           Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 11 columns]

In [26]:
df.groupby("country")["price"].agg([len, "min", "max"]).head(8)

                         len   min     max
country
Argentina               3800   4.0   230.0
Armenia                    2  14.0    15.0
Australia               2329   5.0   850.0
Austria                 3345   7.0  1100.0
Bosnia and Herzegovina     2  12.0    13.0
Brazil                    52  10.0    60.0
Bulgaria                 141   8.0   100.0
Canada                   257  12.0   120.0

The `len` method gives the number of entries for each country

In [35]:
# length of written description for the specific wine produced in the specified country, province
countries_reviews = df.groupby(["country", "province"])["description"].agg(len)
countries_reviews

country    province
Argentina  Mendoza Province    3264
           Other                536
Armenia    Armenia                2
Australia  Australia Other      245
           New South Wales       85
                               ...
Uruguay    Juanico               12
           Montevideo            11
           Progreso              11
           San Jose               3
           Uruguay               24
Name: description, Length: 425, dtype: int64

In [37]:
type(countries_reviews.index)

pandas.core.indexes.multi.MultiIndex

In [40]:
countries_reviews = countries_reviews.reset_index()
countries_reviews

       country          province  description
0    Argentina  Mendoza Province         3264
1    Argentina             Other          536
2      Armenia           Armenia            2
3    Australia   Australia Other          245
4    Australia   New South Wales           85
..         ...               ...          ...
420    Uruguay           Juanico           12
421    Uruguay        Montevideo           11
422    Uruguay          Progreso           11
423    Uruguay          San Jose            3
424    Uruguay           Uruguay           24

[425 rows x 3 columns]

In [43]:
countries_reviews.sort_values(by="description")

          country           province  description
386        Turkey  Elazığ-Diyarbakir            1
389        Turkey        Urla-Thrace            1
395            US             Hawaii            1
357  South Africa    Piekenierskloof            1
354  South Africa         Paardeberg            1
..            ...                ...          ...
409            US             Oregon         5373
227         Italy            Tuscany         5897
118        France           Bordeaux         5941
415            US         Washington         8639
392            US         California        36247

[425 rows x 3 columns]

In [44]:
countries_reviews.sort_values(by="description", ascending=False)

    country          province  description
392      US        California        36247
415      US        Washington         8639
118  France          Bordeaux         5941
227   Italy           Tuscany         5897
409      US            Oregon         5373
..      ...               ...          ...
389  Turkey       Urla-Thrace            1
48   Canada      Canada Other            1
40   Brazil  Serra do Sudeste            1
395      US            Hawaii            1
399      US          Kentucky            1

[425 rows x 3 columns]

In [48]:
countries_reviews.sort_values(["country", "description"]).loc[countries_reviews["country"] == "Italy"]

    country            province  description
223   Italy  Northwestern Italy           13
220   Italy         Italy Other          135
221   Italy            Lombardy          533
219   Italy       Central Italy         1233
226   Italy      Southern Italy         1349
225   Italy   Sicily & Sardinia         1797
222   Italy  Northeastern Italy         2138
228   Italy              Veneto         2716
224   Italy            Piedmont         3729
227   Italy             Tuscany         5897

### Exercise

In [49]:
df

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [64]:
# 1
df.groupby("taster_twitter_handle")["taster_twitter_handle"].count()

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
Name: taster_twitter_handle, dtype: int64

In [65]:
df.groupby("taster_twitter_handle").size()

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
dtype: int64

In [68]:
# 2
df.groupby("price")["points"].max().sort_index(ascending=True)

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [74]:
# 3
df["variety"].nunique()

707

In [77]:
variety_prices = df.groupby("variety")["price"].agg(["min", "max"]).rename(columns={"max": "Max Price", "min": "Min Price"})
variety_prices

             Min Price  Max Price
variety
Abouriou          15.0       75.0
Agiorgitiko       10.0       66.0
Aglianico          6.0      180.0
Aidani            27.0       27.0
Airen              8.0       10.0
...                ...        ...
Zinfandel          5.0      100.0
Zlahtina          13.0       16.0
Zweigelt           9.0       70.0
Çalkarası         19.0       19.0
Žilavka           15.0       15.0

[707 rows x 2 columns]

In [80]:
# 4
variety_prices.sort_values(by=["Min Price", "Max Price"], ascending=False).dropna()

                  Min Price  Max Price
variety
Ramisco               495.0      495.0
Terrantez             236.0      236.0
Francisa              160.0      160.0
Rosenmuskateller      150.0      150.0
Tinta Negra Mole      112.0      112.0
...                     ...        ...
Merlot                  4.0      625.0
Tempranillo             4.0      600.0
White Blend             4.0      375.0
Malbec-Syrah            4.0       78.0
Pinot Grigio            4.0       70.0

[697 rows x 2 columns]

In [86]:
# 5
taster_mean_ratings = df.groupby("taster_name")["points"].mean().round(decimals=1)
taster_mean_ratings

taster_name
Alexander Peartree    85.9
Anna Lee C. Iijima    88.4
Anne Krebiehl MW      90.6
Carrie Dykes          86.4
Christina Pickard     87.8
Fiona Adams           86.9
Jeff Jenssen          88.3
Jim Gordon            88.6
Joe Czerwinski        88.5
Kerin O’Keefe         88.9
Lauren Buzzeo         87.7
Matt Kettmann         90.0
Michael Schachner     86.9
Mike DeSimone         89.1
Paul Gregutt          89.1
Roger Voss            88.7
Sean P. Sullivan      88.8
Susan Kostrzewa       86.6
Virginie Boone        89.2
Name: points, dtype: float64

In [87]:
taster_mean_ratings.describe()

count    19.000000
mean     88.231579
std       1.244567
min      85.900000
25%      87.300000
50%      88.500000
75%      89.000000
max      90.600000
Name: points, dtype: float64

In [ ]:
# 6
# find every combination of 'country' and 'variety', and turn them to a group
df.groupby(["country", "variety"]).size().sort_values(ascending=False).head(20)

country    variety
US         Pinot Noir                  9885
           Cabernet Sauvignon          7315
           Chardonnay                  6801
France     Bordeaux-style Red Blend    4725
Italy      Red Blend                   3624
US         Syrah                       3244
           Red Blend                   2972
France     Chardonnay                  2808
Italy      Nebbiolo                    2736
US         Zinfandel                   2711
Portugal   Portuguese Red              2466
US         Merlot                      2311
Italy      Sangiovese                  2265
US         Sauvignon Blanc             2163
France     Pinot Noir                  1966
           Rosé                        1923
US         Bordeaux-style Red Blend    1824
Germany    Riesling                    1790
US         Riesling                    1753
Argentina  Malbec                      1510
dtype: int64