# Coding Practice Session 8
## Handling Duplicate Data in Pandas

In [37]:
import pandas as pd
import numpy as np

In [38]:
df = pd.DataFrame(
    {
        "Name": ["John", "Jane", "John", "Mike", "Jane"],
        "Age": [28, 32, 28, 45, 32],
        "City": ["New York City", "Boston", "New York City", "Chicago", "Denver"],
    }
)

df

   Name  Age           City
0  John   28  New York City
1  Jane   32         Boston
2  John   28  New York City
3  Mike   45        Chicago
4  Jane   32         Denver

In [39]:
print(f"Mean of age with duplicates:\n{df['Age'].mean()}")

Mean of age with duplicates:
33.0

In [40]:
print("Mean of age without duplicates:")
print(df.drop_duplicates()["Age"].mean())

Mean of age without duplicates:
34.25

### Detecting Duplicates

In [41]:
df

   Name  Age           City
0  John   28  New York City
1  Jane   32         Boston
2  John   28  New York City
3  Mike   45        Chicago
4  Jane   32         Denver

In [42]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [43]:
df.duplicated(keep="last")

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [44]:
df.duplicated(keep="first")

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [45]:
df.duplicated(keep=False)

0     True
1    False
2     True
3    False
4    False
dtype: bool

In [46]:
df[df.duplicated(keep="last")]

   Name  Age           City
0  John   28  New York City

In [47]:
df[df.duplicated(keep=False)]

   Name  Age           City
0  John   28  New York City
2  John   28  New York City

In [48]:
df = pd.DataFrame(
    {"A": [1, 2, 2, 3, 4, 5, 5], "B": ["a", "b", "b", "c", "d", "e", "e"]}
)


df

   A  B
0  1  a
1  2  b
2  2  b
3  3  c
4  4  d
5  5  e
6  5  e

In [49]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
dtype: bool

In [50]:
df[df.duplicated()]

   A  B
2  2  b
6  5  e

In [51]:
df[df.duplicated(keep=False)]

   A  B
1  2  b
2  2  b
5  5  e
6  5  e

In [52]:
df = pd.DataFrame(
    {
        "Name": ["John", "Jane", "John", "Mike", "Jane"],
        "Age": [28, 32, 28, 45, 33],
        "City": ["New York", "Boston", "Chicago", "Chicago", "Boston"],
    }
)

df

   Name  Age      City
0  John   28  New York
1  Jane   32    Boston
2  John   28   Chicago
3  Mike   45   Chicago
4  Jane   33    Boston

In [53]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [54]:
df.duplicated(subset=["Name"])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [55]:
df[df.duplicated(subset=["Name"], keep=False)]

   Name  Age      City
0  John   28  New York
1  Jane   32    Boston
2  John   28   Chicago
4  Jane   33    Boston

In [56]:
df.duplicated(subset=["Name", "Age"])

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [57]:
df[df.duplicated(subset=["Name", "Age"], keep=False)]

   Name  Age      City
0  John   28  New York
2  John   28   Chicago

In [58]:
df["Name"].value_counts() > 1

Name
John     True
Jane     True
Mike    False
Name: count, dtype: bool

In [59]:
df["Name"].value_counts()[df["Name"].value_counts() > 1]

Name
John    2
Jane    2
Name: count, dtype: int64

### Removing Duplicate Data

In [60]:
df.drop_duplicates(subset=["Name"], keep="last")

   Name  Age     City
2  John   28  Chicago
3  Mike   45  Chicago
4  Jane   33   Boston

In [61]:
df.drop_duplicates(subset=["Name", "Age"], ignore_index=True)

   Name  Age      City
0  John   28  New York
1  Jane   32    Boston
2  Mike   45   Chicago
3  Jane   33    Boston

In [96]:
df = pd.DataFrame({"A": [1, 2, 2, 3], "B": ["a", "b", "b", "c"], "C": [10, 20, 20, 30]})

df

   A  B   C
0  1  a  10
1  2  b  20
2  2  b  20
3  3  c  30

In [97]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [98]:
df.duplicated().any()

np.True_

In [64]:
df.drop_duplicates(keep="first")  # by default keeps first duplicate

   A  B   C
0  1  a  10
1  2  b  20
3  3  c  30

In [65]:
df = pd.DataFrame(
    {
        "Name": ["John", "Jane", "John", "Mike", "Jane"],
        "Age": [28, 32, 28, 45, 33],
        "City": ["New York", "Boston", "Chicago", "Chicago", "Boston"],
    }
)

df

   Name  Age      City
0  John   28  New York
1  Jane   32    Boston
2  John   28   Chicago
3  Mike   45   Chicago
4  Jane   33    Boston

In [66]:
df.duplicated(subset=["Name", "Age"]).any()

np.True_

In [67]:
df.drop_duplicates(subset=["Name", "Age"], keep="last", inplace=True, ignore_index=True)

In [68]:
df

   Name  Age     City
0  Jane   32   Boston
1  John   28  Chicago
2  Mike   45  Chicago
3  Jane   33   Boston

In [69]:
df.isnull().any()

Name    False
Age     False
City    False
dtype: bool

### Advanced Duplicate Handling

In [71]:
from thefuzz import fuzz, process

In [79]:
# simple ratio
fuzz.ratio("My name is Arad", "My Name is Arad!")

90

In [81]:
fuzz.ratio("Hello there ", "Hello there")

96

In [82]:
fuzz.ratio("Hello there", "Hello there")

100

In [75]:
fuzz.ratio("World ", "World")

91

In [77]:
fuzz.ratio("Don't go there", "Don't go there!")

97

In [76]:
# partial ratio
fuzz.partial_ratio("Don't go there", "Don't go there!")

100

In [83]:
fuzz.partial_ratio("COMe HeRE", "come here")

40

In [87]:
sports_teams = [
    "Los Angles Lakers",
    "Boston Celtics",
    "New York Knicks",
    "Los Angles Clippers",
    "Los Angles Chargers",
    "New York Jets",
    "Philadelphia 76ers",
    "Boston Bruins",
]

In [95]:
process.extract("New York", sports_teams, limit=2, scorer=fuzz.ratio)

[('New York Jets', 76), ('New York Knicks', 70)]