# Coding Practice Session 9
## String Manipulation in Pandas

In [1]:
import pandas as pd
import numpy as np
from faker import Faker

In [2]:
fake_gen = Faker()
fake_gen.seed_instance(17)

In [3]:
fake_names = [fake_gen.name() for _ in range(4)]
fake_names

['Renee Horne', 'Ralph Padilla', 'Ashley Johnson', 'Paul King']

In [4]:
emails = []
for name in fake_names:
    first_name = name.split()[0]
    email = f"{first_name.lower()}@example.com"
    emails.append(email)

In [5]:
emails

['renee@example.com',
 'ralph@example.com',
 'ashley@example.com',
 'paul@example.com']

In [6]:
fake_addresses = [fake_gen.address() for _ in range(5)]
fake_addresses

['628 Donald Turnpike Apt. 288\nWest Amber, FM 94294',
 '1879 Felicia Lodge Suite 065\nPort Joanneton, NJ 49630',
 '3183 Alison Lake\nWest Calebview, ID 98480',
 '4552 Davis Ports\nMatthewton, WV 46114',
 '0344 Kaitlin Stravenue Suite 099\nSouth Todd, OR 51825']

In [7]:
fake_names.append(np.nan)
emails.append("unknown@axample.com")

In [8]:
fake_names

['Renee Horne', 'Ralph Padilla', 'Ashley Johnson', 'Paul King', nan]

In [9]:
df = pd.DataFrame({"Name": fake_names, "Email": emails, "Address": fake_addresses})

df

,Name,Email,Address
0,Renee Horne,renee@example.com,"628 Donald Turnpike Apt. 288\nWest Amber, FM 9..."
1,Ralph Padilla,ralph@example.com,"1879 Felicia Lodge Suite 065\nPort Joanneton, ..."
2,Ashley Johnson,ashley@example.com,"3183 Alison Lake\nWest Calebview, ID 98480"
3,Paul King,paul@example.com,"4552 Davis Ports\nMatthewton, WV 46114"
4,NaN,unknown@axample.com,"0344 Kaitlin Stravenue Suite 099\nSouth Todd, ..."

In [10]:
df["Address"] = df["Address"].apply(lambda address: address.replace("\n", ", "))

In [11]:
df

,Name,Email,Address
0,Renee Horne,renee@example.com,"628 Donald Turnpike Apt. 288, West Amber, FM 9..."
1,Ralph Padilla,ralph@example.com,"1879 Felicia Lodge Suite 065, Port Joanneton, ..."
2,Ashley Johnson,ashley@example.com,"3183 Alison Lake, West Calebview, ID 98480"
3,Paul King,paul@example.com,"4552 Davis Ports, Matthewton, WV 46114"
4,NaN,unknown@axample.com,"0344 Kaitlin Stravenue Suite 099, South Todd, ..."

### Accessing String Methods

use `.str` accessor

In [12]:
s = pd.Series(["apple", "orange", "banana", "cherry", np.nan])

In [13]:
s.str.upper()

0     APPLE
1    ORANGE
2    BANANA
3    CHERRY
4       NaN
dtype: object

In [14]:
s.str.len()

0    5.0
1    6.0
2    6.0
3    6.0
4    NaN
dtype: float64

In [15]:
df

,Name,Email,Address
0,Renee Horne,renee@example.com,"628 Donald Turnpike Apt. 288, West Amber, FM 9..."
1,Ralph Padilla,ralph@example.com,"1879 Felicia Lodge Suite 065, Port Joanneton, ..."
2,Ashley Johnson,ashley@example.com,"3183 Alison Lake, West Calebview, ID 98480"
3,Paul King,paul@example.com,"4552 Davis Ports, Matthewton, WV 46114"
4,NaN,unknown@axample.com,"0344 Kaitlin Stravenue Suite 099, South Todd, ..."

In [16]:
df["Name"].str.lower()

0       renee horne
1     ralph padilla
2    ashley johnson
3         paul king
4               NaN
Name: Name, dtype: object

In [17]:
df["Name"].str.len()

0    11.0
1    13.0
2    14.0
3     9.0
4     NaN
Name: Name, dtype: float64

In [18]:
df["Name"].str[0:4]

0    Rene
1    Ralp
2    Ashl
3    Paul
4     NaN
Name: Name, dtype: object

In [19]:
df["Name"].str[-1]

0      e
1      a
2      n
3      g
4    NaN
Name: Name, dtype: object

In [20]:
# method chaining
df["Email"].str.split("@").str[0].str.upper()

0      RENEE
1      RALPH
2     ASHLEY
3       PAUL
4    UNKNOWN
Name: Email, dtype: object

In [21]:
df["Name"].str.startswith("R")

0     True
1     True
2    False
3    False
4      NaN
Name: Name, dtype: object

In [22]:
df[df["Name"].str.startswith("R", na=False)]

,Name,Email,Address
0,Renee Horne,renee@example.com,"628 Donald Turnpike Apt. 288, West Amber, FM 9..."
1,Ralph Padilla,ralph@example.com,"1879 Felicia Lodge Suite 065, Port Joanneton, ..."

In [23]:
df[["Name", "Email"]].apply(lambda x: x.str.upper())

             Name                Email
0     RENEE HORNE    RENEE@EXAMPLE.COM
1   RALPH PADILLA    RALPH@EXAMPLE.COM
2  ASHLEY JOHNSON   ASHLEY@EXAMPLE.COM
3       PAUL KING     PAUL@EXAMPLE.COM
4             NaN  UNKNOWN@AXAMPLE.COM

In [24]:
df["Email"].str.extract(r"@(.+)$")

             0
0  example.com
1  example.com
2  example.com
3  example.com
4  axample.com

### Basic String Operations

In [25]:
s = pd.Series(["APPLE", "banana", "Cherry", "ORanGe"])

In [26]:
s.str.lower()

0     apple
1    banana
2    cherry
3    orange
dtype: object

In [27]:
s.str.title()

0     Apple
1    Banana
2    Cherry
3    Orange
dtype: object

In [28]:
s.str.swapcase()

0     apple
1    BANANA
2    cHERRY
3    orANgE
dtype: object

In [29]:
df["Name"].str.lower()

0       renee horne
1     ralph padilla
2    ashley johnson
3         paul king
4               NaN
Name: Name, dtype: object

In [30]:
s = pd.Series(["  apple  ", " banana ", "cherry  ", "  date"])

In [31]:
s.str.strip()

0     apple
1    banana
2    cherry
3      date
dtype: object

In [32]:
s.str.lstrip()

0     apple
1     banana
2    cherry
3        date
dtype: object

In [33]:
"   apple ".lstrip()

'apple '

In [34]:
s.str.rstrip()

0      apple
1     banana
2     cherry
3       date
dtype: object

In [35]:
pd.Series(["##apple##", "#banana#", "cherry##"]).str.strip("#")

0     apple
1    banana
2    cherry
dtype: object

In [36]:
s = pd.Series(["apple", "banana", "cherry"])

In [37]:
s.str.pad(width=10, fillchar="^")

0    ^^^^^apple
1    ^^^^banana
2    ^^^^cherry
dtype: object

In [38]:
s.str.pad(width=10, side="right", fillchar="&")

0    apple&&&&&
1    banana&&&&
2    cherry&&&&
dtype: object

In [39]:
s.str.center(width=10, fillchar="-")

0    --apple---
1    --banana--
2    --cherry--
dtype: object

In [40]:
s.str.ljust(width=10, fillchar=">")

0    apple>>>>>
1    banana>>>>
2    cherry>>>>
dtype: object

In [41]:
s.str.rjust(width=8, fillchar=">")

0    >>>apple
1    >>banana
2    >>cherry
dtype: object

In [42]:
df["Name"].str.ljust(width=16, fillchar="-")

0    Renee Horne-----
1    Ralph Padilla---
2    Ashley Johnson--
3    Paul King-------
4                 NaN
Name: Name, dtype: object

### String Information and Checks

In [43]:
df

,Name,Email,Address
0,Renee Horne,renee@example.com,"628 Donald Turnpike Apt. 288, West Amber, FM 9..."
1,Ralph Padilla,ralph@example.com,"1879 Felicia Lodge Suite 065, Port Joanneton, ..."
2,Ashley Johnson,ashley@example.com,"3183 Alison Lake, West Calebview, ID 98480"
3,Paul King,paul@example.com,"4552 Davis Ports, Matthewton, WV 46114"
4,NaN,unknown@axample.com,"0344 Kaitlin Stravenue Suite 099, South Todd, ..."

In [44]:
df["Email"].str.len()

0    17
1    17
2    18
3    16
4    19
Name: Email, dtype: int64

In [45]:
df["Email"].str.len().mean()

np.float64(17.4)

In [46]:
df["Name"].str.startswith("P", na=False)

0    False
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

In [47]:
df["Email"].str.endswith("example.com")

0     True
1     True
2     True
3     True
4    False
Name: Email, dtype: bool

In [48]:
df.loc[4]

Name                                                     NaN
Email                                    unknown@axample.com
Address    0344 Kaitlin Stravenue Suite 099, South Todd, ...
Name: 4, dtype: object

In [49]:
df["Address"].str.endswith("46114")

0    False
1    False
2    False
3     True
4    False
Name: Address, dtype: bool

In [50]:
df[df["Address"].str.endswith("46114")]

        Name             Email                                 Address
3  Paul King  paul@example.com  4552 Davis Ports, Matthewton, WV 46114

In [51]:
df["Name"].str.contains("pad", case=False, na=False)

0    False
1     True
2    False
3    False
4    False
Name: Name, dtype: bool

In [52]:
df["Address"]

0    628 Donald Turnpike Apt. 288, West Amber, FM 9...
1    1879 Felicia Lodge Suite 065, Port Joanneton, ...
2           3183 Alison Lake, West Calebview, ID 98480
3               4552 Davis Ports, Matthewton, WV 46114
4    0344 Kaitlin Stravenue Suite 099, South Todd, ...
Name: Address, dtype: object

In [53]:
# checks for digits using regex
df["Address"].str.contains(r"\d{5}", regex=True, na=False)

0    True
1    True
2    True
3    True
4    True
Name: Address, dtype: bool

In [54]:
df["Name"].str.contains("john", case=False, na=False)

0    False
1    False
2     True
3    False
4    False
Name: Name, dtype: bool

In [55]:
df[df["Name"].str.startswith("P") | df["Address"].str.contains("NJ")]

,Name,Email,Address
1,Ralph Padilla,ralph@example.com,"1879 Felicia Lodge Suite 065, Port Joanneton, ..."
3,Paul King,paul@example.com,"4552 Davis Ports, Matthewton, WV 46114"

### Extracting and Replacing Substrings

In [56]:
s = pd.Series(["apple", "orange", "banana", "cherry"])
s

0     apple
1    orange
2    banana
3    cherry
dtype: object

In [57]:
s.str.slice(0, 3)

0    app
1    ora
2    ban
3    che
dtype: object

In [58]:
s.str.slice(2)

0     ple
1    ange
2    nana
3    erry
dtype: object

In [59]:
s.str.slice(-2)

0    le
1    ge
2    na
3    ry
dtype: object

In [60]:
df["Name"].str.slice(0, 8, step=2)

0    RneH
1    RlhP
2    Ahe
3    Pu i
4     NaN
Name: Name, dtype: object

In [61]:
s.str.get(0)

0    a
1    o
2    b
3    c
dtype: object

In [62]:
s.str.get(-2)

0    l
1    g
2    n
3    r
dtype: object

In [63]:
df["Email"].str.split("@").str.get(-1)

0    example.com
1    example.com
2    example.com
3    example.com
4    axample.com
Name: Email, dtype: object

In [64]:
df["Email"].str.split("@").str.get(-1).value_counts()

Email
example.com    4
axample.com    1
Name: count, dtype: int64

In [65]:
s = pd.Series(["apple pie", "banana split", "cherry tart"])
s

0       apple pie
1    banana split
2     cherry tart
dtype: object

In [66]:
s.str.find("e")

0    4
1   -1
2    2
dtype: int64

In [67]:
s.str.find("apple")

0    0
1   -1
2   -1
dtype: int64

In [68]:
s.str.find("lit")

0   -1
1    9
2   -1
dtype: int64

In [69]:
df["Email"].str.find("@")

0    5
1    5
2    6
3    4
4    7
Name: Email, dtype: int64

In [70]:
s.str.replace("apple", "blueberry")

0    blueberry pie
1     banana split
2      cherry tart
dtype: object

In [71]:
s.str.replace("a", "XX")

0         XXpple pie
1    bXXnXXnXX split
2       cherry tXXrt
dtype: object

In [72]:
s.str.replace("a", "XX", n=1)

0       XXpple pie
1    bXXnana split
2     cherry tXXrt
dtype: object

In [73]:
s.str.replace(r"\s", "_", regex=True)

0       apple_pie
1    banana_split
2     cherry_tart
dtype: object

In [74]:
df.loc[4, "Email"] = df.loc[4, "Email"].replace("axample.com", "example.com")

In [75]:
df["Email"].str.replace("example.com", "workdomain.com")

0      renee@workdomain.com
1      ralph@workdomain.com
2     ashley@workdomain.com
3       paul@workdomain.com
4    unknown@workdomain.com
Name: Email, dtype: object

In [76]:
x = df["Email"].loc[0]
x

'renee@example.com'

In [77]:
x[0:3] + "*" * (x.find("@") - 3) + x[x.find("@") :]

'ren**@example.com'

In [78]:
# masking part of email
df["Email"].apply(
    lambda email: (
        email[:3] + "*" * (email.find("@") - 3) + email[email.find("@") :]
        if isinstance(email, str)
        else email
    )
)

0      ren**@example.com
1      ral**@example.com
2     ash***@example.com
3       pau*@example.com
4    unk****@example.com
Name: Email, dtype: object

In [79]:
df["Address"]

0    628 Donald Turnpike Apt. 288, West Amber, FM 9...
1    1879 Felicia Lodge Suite 065, Port Joanneton, ...
2           3183 Alison Lake, West Calebview, ID 98480
3               4552 Davis Ports, Matthewton, WV 46114
4    0344 Kaitlin Stravenue Suite 099, South Todd, ...
Name: Address, dtype: object

In [80]:
state_mapping = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    # Territories and Armed Forces (optional)
    "DC": "District of Columbia",
    "AS": "American Samoa",
    "GU": "Guam",
    "MP": "Northern Mariana Islands",
    "PR": "Puerto Rico",
    "VI": "U.S. Virgin Islands",
    "AA": "Armed Forces Americas",
    "AE": "Armed Forces Europe",
    "AP": "Armed Forces Pacific",
}

In [81]:
df["Address"] = df["Address"].replace(state_mapping, regex=True)

In [82]:
df["Address"]

0    628 Donald Turnpike Apt. 288, West Amber, FM 9...
1    1879 Felicia Lodge Suite 065, Port Joanneton, ...
2        3183 Alison Lake, West Calebview, Idaho 98480
3    4552 Davis Ports, Matthewton, West Virginia 46114
4    0344 Kaitlin Stravenue Suite 099, South Todd, ...
Name: Address, dtype: object

In [83]:
df["Email"].str.split("@").str.get(0)

0      renee
1      ralph
2     ashley
3       paul
4    unknown
Name: Email, dtype: object

### Regular Expressions in Pandas

In [84]:
s = pd.Series(["foo123", "bar456", "123baz"])
s

0    foo123
1    bar456
2    123baz
dtype: object

In [85]:
s.str.match(r"[a-zA-Z]")

0     True
1     True
2    False
dtype: bool

In [86]:
s.str.contains(r"\d+")

0    True
1    True
2    True
dtype: bool

In [87]:
s.str.findall(r"\d+")

0    [123]
1    [456]
2    [123]
dtype: object

In [88]:
df["Address"].str.findall(r"\d+")

0     [628, 288, 94294]
1    [1879, 065, 49630]
2         [3183, 98480]
3         [4552, 46114]
4    [0344, 099, 51825]
Name: Address, dtype: object

In [89]:
s.str.extract(r"([a-zA-Z]+)(\d+)")

     0    1
0  foo  123
1  bar  456
2  NaN  NaN

In [90]:
df["Address"]

0    628 Donald Turnpike Apt. 288, West Amber, FM 9...
1    1879 Felicia Lodge Suite 065, Port Joanneton, ...
2        3183 Alison Lake, West Calebview, Idaho 98480
3    4552 Davis Ports, Matthewton, West Virginia 46114
4    0344 Kaitlin Stravenue Suite 099, South Todd, ...
Name: Address, dtype: object

In [91]:
df["Email"].str.extractall(r"(\w+)@(\w+\.\w+)")

               0            1
  match
0 0        renee  example.com
1 0        ralph  example.com
2 0       ashley  example.com
3 0         paul  example.com
4 0      unknown  example.com

In [92]:
df = pd.DataFrame(
    {
        "Name": ["John Smith", "Jane Doe", "Bob Johnson", "Alice Brown", None],
        "Email": [
            "john@example.com",
            "jane@example.com",
            "bob@example.com",
            "alice@example.com",
            "unknown@example.com",
        ],
        "Address": [
            "123 Main St, NY 10001",
            "456 Elm St, CA 90210",
            "789 Oak St, TX 75001",
            "321 Pine St, FL 33101",
            "654 Maple St, WA 98101",
        ],
    }
)

df

          Name                Email                 Address
0   John Smith     john@example.com   123 Main St, NY 10001
1     Jane Doe     jane@example.com    456 Elm St, CA 90210
2  Bob Johnson      bob@example.com    789 Oak St, TX 75001
3  Alice Brown    alice@example.com   321 Pine St, FL 33101
4         None  unknown@example.com  654 Maple St, WA 98101

In [93]:
address_components = df["Address"].str.extract(r"(\d+)\s+(.+),\s+(\w{2})\s+(\d+)")
address_components

     0         1   2      3
0  123   Main St  NY  10001
1  456    Elm St  CA  90210
2  789    Oak St  TX  75001
3  321   Pine St  FL  33101
4  654  Maple St  WA  98101

In [94]:
address_components.columns = ["Street Number", "Street Name", "State", "Zip Code"]

In [95]:
address_components

  Street Number Street Name State Zip Code
0           123     Main St    NY    10001
1           456      Elm St    CA    90210
2           789      Oak St    TX    75001
3           321     Pine St    FL    33101
4           654    Maple St    WA    98101

In [96]:
address_components["Street Name"].str.strip(r"\sSt")

0     Main
1      Elm
2      Oak
3     Pine
4    Maple
Name: Street Name, dtype: object

In [97]:
email_components = df["Email"].str.extract(r"(\w+)@(\w+\.\w+)")
email_components

         0            1
0     john  example.com
1     jane  example.com
2      bob  example.com
3    alice  example.com
4  unknown  example.com

In [98]:
email_components.columns = ["Username", "Domain"]
email_components

  Username       Domain
0     john  example.com
1     jane  example.com
2      bob  example.com
3    alice  example.com
4  unknown  example.com

In [99]:
df_expanded = pd.concat([df, address_components, email_components], axis=1)

In [100]:
df_expanded

,Name,Email,Address,Street Number,Street Name,State,Zip Code,Username,Domain
0,John Smith,john@example.com,"123 Main St, NY 10001",123,Main St,NY,10001,john,example.com
1,Jane Doe,jane@example.com,"456 Elm St, CA 90210",456,Elm St,CA,90210,jane,example.com
2,Bob Johnson,bob@example.com,"789 Oak St, TX 75001",789,Oak St,TX,75001,bob,example.com
3,Alice Brown,alice@example.com,"321 Pine St, FL 33101",321,Pine St,FL,33101,alice,example.com
4,None,unknown@example.com,"654 Maple St, WA 98101",654,Maple St,WA,98101,unknown,example.com

In [101]:
df_expanded.isna()

,Name,Email,Address,Street Number,Street Name,State,Zip Code,Username,Domain
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False

In [102]:
df_expanded[df_expanded["Name"].isna()]

,Name,Email,Address,Street Number,Street Name,State,Zip Code,Username,Domain
4,None,unknown@example.com,"654 Maple St, WA 98101",654,Maple St,WA,98101,unknown,example.com

In [103]:
df_expanded["Valid Email"] = df_expanded["Email"].str.match(r"^[\w\.-]+@[\w\.-]+\.\w+$")

In [104]:
df_expanded["Area Code"] = df_expanded["Zip Code"].str.slice(0, 3)

In [105]:
df_expanded.iloc[:, -4:]

  Username       Domain  Valid Email Area Code
0     john  example.com         True       100
1     jane  example.com         True       902
2      bob  example.com         True       750
3    alice  example.com         True       331
4  unknown  example.com         True       981

In [106]:
df_expanded

,Name,Email,Address,Street Number,Street Name,State,Zip Code,Username,Domain,Valid Email,Area Code
0,John Smith,john@example.com,"123 Main St, NY 10001",123,Main St,NY,10001,john,example.com,True,100
1,Jane Doe,jane@example.com,"456 Elm St, CA 90210",456,Elm St,CA,90210,jane,example.com,True,902
2,Bob Johnson,bob@example.com,"789 Oak St, TX 75001",789,Oak St,TX,75001,bob,example.com,True,750
3,Alice Brown,alice@example.com,"321 Pine St, FL 33101",321,Pine St,FL,33101,alice,example.com,True,331
4,None,unknown@example.com,"654 Maple St, WA 98101",654,Maple St,WA,98101,unknown,example.com,True,981

### Splitting and Joining Strings

In [107]:
s = pd.Series(["apple pie", "banana split", "cherry tart", "icy strawberry pudding"])
s

0                 apple pie
1              banana split
2               cherry tart
3    icy strawberry pudding
dtype: object

In [108]:
s.str.split()

0                  [apple, pie]
1               [banana, split]
2                [cherry, tart]
3    [icy, strawberry, pudding]
dtype: object

In [109]:
s.str.split(expand=True).fillna("-")

        0           1        2
0   apple         pie        -
1  banana       split        -
2  cherry        tart        -
3     icy  strawberry  pudding

In [110]:
s.str.split(n=1, expand=True)

        0                   1
0   apple                 pie
1  banana               split
2  cherry                tart
3     icy  strawberry pudding

In [111]:
df

          Name                Email                 Address
0   John Smith     john@example.com   123 Main St, NY 10001
1     Jane Doe     jane@example.com    456 Elm St, CA 90210
2  Bob Johnson      bob@example.com    789 Oak St, TX 75001
3  Alice Brown    alice@example.com   321 Pine St, FL 33101
4         None  unknown@example.com  654 Maple St, WA 98101

In [112]:
df["Name"].str.split(expand=True)

       0        1
0   John    Smith
1   Jane      Doe
2    Bob  Johnson
3  Alice    Brown
4   None     None

In [113]:
s.str.rsplit(n=1)

0                 [apple, pie]
1              [banana, split]
2               [cherry, tart]
3    [icy strawberry, pudding]
dtype: object

In [114]:
df["Email"].str.rsplit("@", n=1, expand=True)

         0            1
0     john  example.com
1     jane  example.com
2      bob  example.com
3    alice  example.com
4  unknown  example.com

In [115]:
first_names = pd.Series(["John", "Jane", "Bob", "Alice"])
last_names = pd.Series(["Smith", "Doe", "Johnson", "Brown"])

In [116]:
full_names = first_names.str.cat(last_names, sep=" ")
full_names

0     John Smith
1       Jane Doe
2    Bob Johnson
3    Alice Brown
dtype: object

In [117]:
df["Address"].str.cat(df["Email"], sep=" | ").str.ljust(width=44)

0    123 Main St, NY 10001 | john@example.com
1    456 Elm St, CA 90210 | jane@example.com
2    789 Oak St, TX 75001 | bob@example.com
3    321 Pine St, FL 33101 | alice@example.com
4    654 Maple St, WA 98101 | unknown@example.com
Name: Address, dtype: object

In [118]:
df = pd.DataFrame(
    {
        "Name": ["John Smith", "Jane Doe", "Bob Johnson", "Alice Brown", None],
        "Email": [
            "john@example.com",
            "jane@example.com",
            "bob@example.com",
            "alice@example.com",
            "unknown@example.com",
        ],
        "Address": [
            "123 Main St, NY, 10001",
            "456 Elm St, CA, 90210",
            "789 Oak St, TX, 75001",
            "321 Pine St, FL, 33101",
            "654 Maple St, WA, 98101",
        ],
    }
)

df

          Name                Email                  Address
0   John Smith     john@example.com   123 Main St, NY, 10001
1     Jane Doe     jane@example.com    456 Elm St, CA, 90210
2  Bob Johnson      bob@example.com    789 Oak St, TX, 75001
3  Alice Brown    alice@example.com   321 Pine St, FL, 33101
4         None  unknown@example.com  654 Maple St, WA, 98101

In [119]:
split_names = df["Name"].str.split(n=1, expand=True)
split_names

       0        1
0   John    Smith
1   Jane      Doe
2    Bob  Johnson
3  Alice    Brown
4   None     None

In [120]:
df["First Name"] = split_names[0]
df["Last Name"] = split_names[1]

In [121]:
df

,Name,Email,Address,First Name,Last Name
0,John Smith,john@example.com,"123 Main St, NY, 10001",John,Smith
1,Jane Doe,jane@example.com,"456 Elm St, CA, 90210",Jane,Doe
2,Bob Johnson,bob@example.com,"789 Oak St, TX, 75001",Bob,Johnson
3,Alice Brown,alice@example.com,"321 Pine St, FL, 33101",Alice,Brown
4,None,unknown@example.com,"654 Maple St, WA, 98101",None,None

In [122]:
email_split = df["Email"].str.split("@", expand=True)
email_split

         0            1
0     john  example.com
1     jane  example.com
2      bob  example.com
3    alice  example.com
4  unknown  example.com

In [123]:
df["Username"] = email_split[0]
df["Domain"] = email_split[1]

In [124]:
df

,Name,Email,Address,First Name,Last Name,Username,Domain
0,John Smith,john@example.com,"123 Main St, NY, 10001",John,Smith,john,example.com
1,Jane Doe,jane@example.com,"456 Elm St, CA, 90210",Jane,Doe,jane,example.com
2,Bob Johnson,bob@example.com,"789 Oak St, TX, 75001",Bob,Johnson,bob,example.com
3,Alice Brown,alice@example.com,"321 Pine St, FL, 33101",Alice,Brown,alice,example.com
4,None,unknown@example.com,"654 Maple St, WA, 98101",None,None,unknown,example.com

In [125]:
address_split = df["Address"].str.split(",", n=2, expand=True)
address_split

              0    1       2
0   123 Main St   NY   10001
1    456 Elm St   CA   90210
2    789 Oak St   TX   75001
3   321 Pine St   FL   33101
4  654 Maple St   WA   98101

In [126]:
df["State"] = address_split[1]

In [127]:
df

,Name,Email,Address,First Name,Last Name,Username,Domain,State
0,John Smith,john@example.com,"123 Main St, NY, 10001",John,Smith,john,example.com,NY
1,Jane Doe,jane@example.com,"456 Elm St, CA, 90210",Jane,Doe,jane,example.com,CA
2,Bob Johnson,bob@example.com,"789 Oak St, TX, 75001",Bob,Johnson,bob,example.com,TX
3,Alice Brown,alice@example.com,"321 Pine St, FL, 33101",Alice,Brown,alice,example.com,FL
4,None,unknown@example.com,"654 Maple St, WA, 98101",None,None,unknown,example.com,WA

In [128]:
df["State"] = df["State"].replace(state_mapping, regex=True)

In [129]:
df

,Name,Email,Address,First Name,Last Name,Username,Domain,State
0,John Smith,john@example.com,"123 Main St, NY, 10001",John,Smith,john,example.com,New York
1,Jane Doe,jane@example.com,"456 Elm St, CA, 90210",Jane,Doe,jane,example.com,California
2,Bob Johnson,bob@example.com,"789 Oak St, TX, 75001",Bob,Johnson,bob,example.com,Texas
3,Alice Brown,alice@example.com,"321 Pine St, FL, 33101",Alice,Brown,alice,example.com,Florida
4,None,unknown@example.com,"654 Maple St, WA, 98101",None,None,unknown,example.com,Washington

In [130]:
df["Last Name"].str.cat(df["First Name"], sep=", ", na_rep="--")

0     Smith, John
1       Doe, Jane
2    Johnson, Bob
3    Brown, Alice
4          --, --
Name: Last Name, dtype: object

In [131]:
df["Name"].str.cat(df["Email"], sep=" | ").dropna()

0      John Smith | john@example.com
1        Jane Doe | jane@example.com
2      Bob Johnson | bob@example.com
3    Alice Brown | alice@example.com
Name: Name, dtype: object

### Exercise

In [132]:
df = pd.DataFrame(
    {
        "Customer_Name": [
            "john doe",
            "JANE SMITH",
            "Bob Johnson",
            "  Alice Brown  ",
            np.nan,
        ],
        "Email": [
            "john.doe@email.com",
            "jane.smith@email.com",
            "bob.j@email",
            "alice@email.com",
            "unknown",
        ],
        "Phone": [
            "(123) 456-7890",
            "987-654-3210",
            "1234567890",
            "(456)789-0123",
            np.nan,
        ],
        "Address": [
            "123 Main St., New York, NY 10001",
            "456 Elm St, Los Angeles CA 90001",
            "789 Oak Road TX 75001",
            "321 Pine Avenue, Miami FL 33101",
            "654 Maple St, Seattle WA 98101",
        ],
    }
)
df

,Customer_Name,Email,Phone,Address
0,john doe,john.doe@email.com,(123) 456-7890,"123 Main St., New York, NY 10001"
1,JANE SMITH,jane.smith@email.com,987-654-3210,"456 Elm St, Los Angeles CA 90001"
2,Bob Johnson,bob.j@email,1234567890,789 Oak Road TX 75001
3,Alice Brown,alice@email.com,(456)789-0123,"321 Pine Avenue, Miami FL 33101"
4,NaN,unknown,NaN,"654 Maple St, Seattle WA 98101"

In [133]:
df["Customer_Name"] = df["Customer_Name"].str.title().str.strip()

In [134]:
df["Email"] = df["Email"].str.lower().str.replace(r"@email$", "@email.com", regex=True)

In [135]:
df["Phone"] = (
    df["Phone"]
    .str.replace(r"\D", "", regex=True)
    .str.replace(r"(\d{3})(\d{3})(\d{4})", r"(\1) \2-\3", regex=True)
)

In [136]:
df

,Customer_Name,Email,Phone,Address
0,John Doe,john.doe@email.com,(123) 456-7890,"123 Main St., New York, NY 10001"
1,Jane Smith,jane.smith@email.com,(987) 654-3210,"456 Elm St, Los Angeles CA 90001"
2,Bob Johnson,bob.j@email.com,(123) 456-7890,789 Oak Road TX 75001
3,Alice Brown,alice@email.com,(456) 789-0123,"321 Pine Avenue, Miami FL 33101"
4,NaN,unknown,NaN,"654 Maple St, Seattle WA 98101"

In [137]:
df["State"] = df["Address"].str.extract(r"([A-Z]{2})")

In [138]:
df["Zip Code"] = df["Address"].str.extract(r"(\d{5})$")

In [139]:
df["Address"].replace(r"([A-Z]{2})\s+(\d{5})$", "", regex=True).str.strip(", ")

0     123 Main St., New York
1    456 Elm St, Los Angeles
2               789 Oak Road
3     321 Pine Avenue, Miami
4      654 Maple St, Seattle
Name: Address, dtype: object

In [140]:
df["Address"] = (
    df["Address"].replace(r"([A-Z]{2})\s+(\d{5})$", "", regex=True).str.strip(", ")
)

In [141]:
df

,Customer_Name,Email,Phone,Address,State,Zip Code
0,John Doe,john.doe@email.com,(123) 456-7890,"123 Main St., New York",NY,10001
1,Jane Smith,jane.smith@email.com,(987) 654-3210,"456 Elm St, Los Angeles",CA,90001
2,Bob Johnson,bob.j@email.com,(123) 456-7890,789 Oak Road,TX,75001
3,Alice Brown,alice@email.com,(456) 789-0123,"321 Pine Avenue, Miami",FL,33101
4,NaN,unknown,NaN,"654 Maple St, Seattle",WA,98101

In [142]:
products = pd.DataFrame(
    {
        "Product_ID": ["A001", "B002", "C003", "D004", "E005"],
        "Description": [
            "Red leather wallet, size: 4x3 inches, price: $29.99",
            "Blue denim jeans, waist: 32, length: 34, price: $59.95",
            "Stainless steel watch, diameter: 40mm, water resistant to 50m, price: $129.00",
            "Wireless headphones, battery life: 20 hours, color: black, price: $89.99",
            'Laptop backpack, capacity: 20L, color: gray, fits up to 15" laptop, price: $49.99',
        ],
    }
)
products

  Product_ID                                        Description
0       A001  Red leather wallet, size: 4x3 inches, price: $...
1       B002  Blue denim jeans, waist: 32, length: 34, price...
2       C003  Stainless steel watch, diameter: 40mm, water r...
3       D004  Wireless headphones, battery life: 20 hours, c...
4       E005  Laptop backpack, capacity: 20L, color: gray, f...

In [143]:
products["Price"] = (
    products["Description"].str.extract(r"price: \$(\d+\.\d{2})").astype(float)
)

In [144]:
products

  Product_ID                                        Description   Price
0       A001  Red leather wallet, size: 4x3 inches, price: $...   29.99
1       B002  Blue denim jeans, waist: 32, length: 34, price...   59.95
2       C003  Stainless steel watch, diameter: 40mm, water r...  129.00
3       D004  Wireless headphones, battery life: 20 hours, c...   89.99
4       E005  Laptop backpack, capacity: 20L, color: gray, f...   49.99