# Coding Practice Session 10
## Date and Time in Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 10 days starting from January 1st
dates = pd.date_range(start="01/20/2025", end="02/01/2025", freq="D")

In [3]:
dates

DatetimeIndex(['2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23',
               '2025-01-24', '2025-01-25', '2025-01-26', '2025-01-27',
               '2025-01-28', '2025-01-29', '2025-01-30', '2025-01-31',
               '2025-02-01'],
              dtype='datetime64[ns]', freq='D')

In [4]:
type(dates)

pandas.core.indexes.datetimes.DatetimeIndex

In [5]:
s = pd.Series(np.random.rand(len(dates)), index=dates)

In [6]:
s

2025-01-20    0.961377
2025-01-21    0.797366
2025-01-22    0.925565
2025-01-23    0.628844
2025-01-24    0.909518
2025-01-25    0.992929
2025-01-26    0.197369
2025-01-27    0.553191
2025-01-28    0.587305
2025-01-29    0.153075
2025-01-30    0.820115
2025-01-31    0.221203
2025-02-01    0.626074
Freq: D, dtype: float64

In [7]:
s.sort_values(ascending=False)

2025-01-25    0.992929
2025-01-20    0.961377
2025-01-22    0.925565
2025-01-24    0.909518
2025-01-30    0.820115
2025-01-21    0.797366
2025-01-23    0.628844
2025-02-01    0.626074
2025-01-28    0.587305
2025-01-27    0.553191
2025-01-31    0.221203
2025-01-26    0.197369
2025-01-29    0.153075
dtype: float64

In [8]:
pd.date_range(start="2024-12-25", periods=10, freq="D")

DatetimeIndex(['2024-12-25', '2024-12-26', '2024-12-27', '2024-12-28',
               '2024-12-29', '2024-12-30', '2024-12-31', '2025-01-01',
               '2025-01-02', '2025-01-03'],
              dtype='datetime64[ns]', freq='D')

In [9]:
pd.to_datetime(["2025-08-16", "20251031", "09/22/2025"], format="mixed")

DatetimeIndex(['2025-08-16', '2025-10-31', '2025-09-22'], dtype='datetime64[ns]', freq=None)

In [10]:
pd.to_datetime("04/12/2024 12:30:00", dayfirst=True)

Timestamp('2024-12-04 12:30:00')

In [11]:
ts = pd.Timestamp("2025-07-04 12:00:00", tz="UTC")

In [12]:
ts

Timestamp('2025-07-04 12:00:00+0000', tz='UTC')

In [13]:
type(ts)

pandas._libs.tslibs.timestamps.Timestamp

In [14]:
ts.tz_convert("US/Pacific")

Timestamp('2025-07-04 05:00:00-0700', tz='US/Pacific')

In [15]:
ts.tz_convert("Iran")

Timestamp('2025-07-04 15:30:00+0330', tz='Iran')

In [16]:
s

2025-01-20    0.961377
2025-01-21    0.797366
2025-01-22    0.925565
2025-01-23    0.628844
2025-01-24    0.909518
2025-01-25    0.992929
2025-01-26    0.197369
2025-01-27    0.553191
2025-01-28    0.587305
2025-01-29    0.153075
2025-01-30    0.820115
2025-01-31    0.221203
2025-02-01    0.626074
Freq: D, dtype: float64

In [17]:
monthly = s.resample("MS").mean()

In [18]:
monthly

2025-01-01    0.645655
2025-02-01    0.626074
Freq: MS, dtype: float64

In [19]:
s.rolling(window=3).mean()

2025-01-20         NaN
2025-01-21         NaN
2025-01-22    0.894769
2025-01-23    0.783925
2025-01-24    0.821309
2025-01-25    0.843764
2025-01-26    0.699938
2025-01-27    0.581163
2025-01-28    0.445955
2025-01-29    0.431191
2025-01-30    0.520165
2025-01-31    0.398131
2025-02-01    0.555797
Freq: D, dtype: float64

In [20]:
s

2025-01-20    0.961377
2025-01-21    0.797366
2025-01-22    0.925565
2025-01-23    0.628844
2025-01-24    0.909518
2025-01-25    0.992929
2025-01-26    0.197369
2025-01-27    0.553191
2025-01-28    0.587305
2025-01-29    0.153075
2025-01-30    0.820115
2025-01-31    0.221203
2025-02-01    0.626074
Freq: D, dtype: float64

In [21]:
s.shift(periods=2, fill_value=np.nan)

2025-01-20         NaN
2025-01-21         NaN
2025-01-22    0.961377
2025-01-23    0.797366
2025-01-24    0.925565
2025-01-25    0.628844
2025-01-26    0.909518
2025-01-27    0.992929
2025-01-28    0.197369
2025-01-29    0.553191
2025-01-30    0.587305
2025-01-31    0.153075
2025-02-01    0.820115
Freq: D, dtype: float64

In [22]:
periods = pd.period_range(start="2025-03", end="2025-12", freq="M")

In [23]:
periods

PeriodIndex(['2025-03', '2025-04', '2025-05', '2025-06', '2025-07', '2025-08',
             '2025-09', '2025-10', '2025-11', '2025-12'],
            dtype='period[M]')

In [24]:
type(periods)

pandas.core.indexes.period.PeriodIndex

In [25]:
pd.Series(
    np.random.randint(low=10, high=100, size=len(periods), dtype="u1"), index=periods
)

2025-03    66
2025-04    43
2025-05    74
2025-06    63
2025-07    75
2025-08    86
2025-09    74
2025-10    91
2025-11    62
2025-12    66
Freq: M, dtype: uint8

### Datetime Data Types

In [26]:
# Timestamp
ts = pd.Timestamp("2025-06-22 11:50:00")
ts

Timestamp('2025-06-22 11:50:00')

In [27]:
ts.year

2025

In [28]:
ts.is_leap_year

False

In [29]:
ts.month

6

In [30]:
ts.hour

11

In [31]:
ts.day

22

In [32]:
ts.day_name()

'Sunday'

In [33]:
ts.minute, ts.second

(50, 0)

In [34]:
pd.Timestamp("2025-08-24 08:10:00", tz="Europe/Brussels")

Timestamp('2025-08-24 08:10:00+0200', tz='Europe/Brussels')

In [35]:
pd.Timestamp("2024-09-25 10:45:00", tz="Asia/Tehran")

Timestamp('2024-09-25 10:45:00+0330', tz='Asia/Tehran')

In [36]:
# DatetimeIndex
dates = pd.date_range(start="08-01-1985", end="08-07, 1985", freq="D")
dates

DatetimeIndex(['1985-08-01', '1985-08-02', '1985-08-03', '1985-08-04',
               '1985-08-05', '1985-08-06', '1985-08-07'],
              dtype='datetime64[ns]', freq='D')

In [37]:
len(dates)

7

In [38]:
s = pd.Series(np.random.rand(len(dates)).round(decimals=2), dtype="f4", index=dates)
s

1985-08-01    0.38
1985-08-02    0.22
1985-08-03    0.64
1985-08-04    0.22
1985-08-05    0.97
1985-08-06    0.34
1985-08-07    0.72
Freq: D, dtype: float32

In [39]:
s["1985-08-04"]

np.float32(0.22)

In [40]:
s["1985-08-02":"1985-08-05"]

1985-08-02    0.22
1985-08-03    0.64
1985-08-04    0.22
1985-08-05    0.97
Freq: D, dtype: float32

In [41]:
s.resample("2D").sum()

1985-08-01    0.60
1985-08-03    0.86
1985-08-05    1.31
1985-08-07    0.72
Freq: 2D, dtype: float32

In [42]:
# Timedelta
td = pd.Timedelta(days=2, hours=-5, minutes=20)
td

Timedelta('1 days 19:20:00')

In [43]:
ts

Timestamp('2025-06-22 11:50:00')

In [44]:
ts + td

Timestamp('2025-06-24 07:10:00')

In [45]:
# TimedeltaIndex
tdi = pd.timedelta_range(start="1 day", end="4 days", freq="D")

In [46]:
tdi

TimedeltaIndex(['1 days', '2 days', '3 days', '4 days'], dtype='timedelta64[ns]', freq='D')

In [47]:
s = pd.Series(range(len(tdi)), index=tdi)

In [48]:
s

1 days    0
2 days    1
3 days    2
4 days    3
Freq: D, dtype: int64

In [49]:
s["3 days":]

3 days    2
4 days    3
Freq: D, dtype: int64

In [50]:
pd.date_range(start="2025-08-16", periods=4, freq="MS")

DatetimeIndex(['2025-09-01', '2025-10-01', '2025-11-01', '2025-12-01'], dtype='datetime64[ns]', freq='MS')

In [51]:
pd.date_range(start="2025-08-16", periods=4, freq="h")

DatetimeIndex(['2025-08-16 00:00:00', '2025-08-16 01:00:00',
               '2025-08-16 02:00:00', '2025-08-16 03:00:00'],
              dtype='datetime64[ns]', freq='h')

In [52]:
print(pd.date_range(start="2025", periods=4, freq="YE-AUG"))

DatetimeIndex(['2025-08-31', '2026-08-31', '2027-08-31', '2028-08-31'], dtype='datetime64[ns]', freq='YE-AUG')

In [53]:
dates = pd.date_range(start="2026-01-01", periods=5, freq="MS")
dates

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01',
               '2026-05-01'],
              dtype='datetime64[ns]', freq='MS')

In [54]:
df = pd.DataFrame(
    {"Date": dates, "Value": np.random.choice(range(10), size=5, replace=False)}
)

In [55]:
df

        Date  Value
0 2026-01-01      3
1 2026-02-01      8
2 2026-03-01      1
3 2026-04-01      0
4 2026-05-01      7

In [56]:
df["Date"].min()

Timestamp('2026-01-01 00:00:00')

In [57]:
df["Date"] - df["Date"].min()

0     0 days
1    31 days
2    59 days
3    90 days
4   120 days
Name: Date, dtype: timedelta64[ns]

In [58]:
df["Time Since Start"] = df["Date"] - df["Date"].iloc[0]

In [59]:
df

        Date  Value Time Since Start
0 2026-01-01      3           0 days
1 2026-02-01      8          31 days
2 2026-03-01      1          59 days
3 2026-04-01      0          90 days
4 2026-05-01      7         120 days

### Creating Datetime Objects

In [60]:
date_str = "2025/12/01"
pd.to_datetime(date_str)

Timestamp('2025-12-01 00:00:00')

In [61]:
pd.to_datetime(date_str, format="%Y/%m/%d")

Timestamp('2025-12-01 00:00:00')

In [62]:
date_strings = ["2026-03-21", "20250810", "20010504"]
pd.to_datetime(date_strings, format="mixed")

DatetimeIndex(['2026-03-21', '2025-08-10', '2001-05-04'], dtype='datetime64[ns]', freq=None)

In [71]:
custom_date = "15-Jun-2027"
pd.to_datetime(custom_date, format="%d-%b-%Y")

Timestamp('2027-06-15 00:00:00')

In [64]:
# Unix timestamp
pd.to_datetime(1.45 * 1e9, unit="s")

Timestamp('2015-12-13 09:46:40')

In [65]:
pd.date_range(start="2025-07-04", end="2025-07-14")

DatetimeIndex(['2025-07-04', '2025-07-05', '2025-07-06', '2025-07-07',
               '2025-07-08', '2025-07-09', '2025-07-10', '2025-07-11',
               '2025-07-12', '2025-07-13', '2025-07-14'],
              dtype='datetime64[ns]', freq='D')

In [66]:
pd.date_range(start="2025-02-27", periods=6)

DatetimeIndex(['2025-02-27', '2025-02-28', '2025-03-01', '2025-03-02',
               '2025-03-03', '2025-03-04'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start="2025-04-07", periods=7, freq="B")  # business days

DatetimeIndex(['2025-04-07', '2025-04-08', '2025-04-09', '2025-04-10',
               '2025-04-11', '2025-04-14', '2025-04-15'],
              dtype='datetime64[ns]', freq='B')

In [68]:
pd.date_range(start="2025-08-16", periods=15, freq="2h")

DatetimeIndex(['2025-08-16 00:00:00', '2025-08-16 02:00:00',
               '2025-08-16 04:00:00', '2025-08-16 06:00:00',
               '2025-08-16 08:00:00', '2025-08-16 10:00:00',
               '2025-08-16 12:00:00', '2025-08-16 14:00:00',
               '2025-08-16 16:00:00', '2025-08-16 18:00:00',
               '2025-08-16 20:00:00', '2025-08-16 22:00:00',
               '2025-08-17 00:00:00', '2025-08-17 02:00:00',
               '2025-08-17 04:00:00'],
              dtype='datetime64[ns]', freq='2h')

In [69]:
pd.date_range(start="2025-08-17", periods=5, freq="3W-TUE")

DatetimeIndex(['2025-08-19', '2025-09-09', '2025-09-30', '2025-10-21',
               '2025-11-11'],
              dtype='datetime64[ns]', freq='3W-TUE')

In [70]:
pd.date_range(start="2025-01-01 12:00:00", periods=6, freq="10min")

DatetimeIndex(['2025-01-01 12:00:00', '2025-01-01 12:10:00',
               '2025-01-01 12:20:00', '2025-01-01 12:30:00',
               '2025-01-01 12:40:00', '2025-01-01 12:50:00'],
              dtype='datetime64[ns]', freq='10min')

### Date and Time Components

In [72]:
dates = pd.date_range(start="2025-08-01", periods=10, freq="D")
df = pd.DataFrame({"Value": np.random.randint(low=10, high=100, size=10)}, index=dates)
df

            Value
2025-08-01     73
2025-08-02     13
2025-08-03     28
2025-08-04     31
2025-08-05     31
2025-08-06     41
2025-08-07     67
2025-08-08     43
2025-08-09     50
2025-08-10     51

In [73]:
df.index.year

Index([2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025], dtype='int32')

In [74]:
df.index.month

Index([8, 8, 8, 8, 8, 8, 8, 8, 8, 8], dtype='int32')

In [76]:
df.index.month_name()

Index(['August', 'August', 'August', 'August', 'August', 'August', 'August',
       'August', 'August', 'August'],
      dtype='object')

In [77]:
df.index.day

Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int32')

In [78]:
df.index.day_of_week

Index([4, 5, 6, 0, 1, 2, 3, 4, 5, 6], dtype='int32')

In [79]:
df.index.day_name()

Index(['Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday',
       'Thursday', 'Friday', 'Saturday', 'Sunday'],
      dtype='object')

In [92]:
df.reset_index(inplace=True)

In [93]:
df

       index  Value
0 2025-08-01     73
1 2025-08-02     13
2 2025-08-03     28
3 2025-08-04     31
4 2025-08-05     31
5 2025-08-06     41
6 2025-08-07     67
7 2025-08-08     43
8 2025-08-09     50
9 2025-08-10     51

In [95]:
df.rename(columns={"index": "Date"}, inplace=True)

In [96]:
df

        Date  Value
0 2025-08-01     73
1 2025-08-02     13
2 2025-08-03     28
3 2025-08-04     31
4 2025-08-05     31
5 2025-08-06     41
6 2025-08-07     67
7 2025-08-08     43
8 2025-08-09     50
9 2025-08-10     51

In [98]:
# using .dt accessor
df["Date"].dt.day

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Date, dtype: int32

In [99]:
df["Date"].dt.day_name()

0       Friday
1     Saturday
2       Sunday
3       Monday
4      Tuesday
5    Wednesday
6     Thursday
7       Friday
8     Saturday
9       Sunday
Name: Date, dtype: object

In [100]:
df["Date"].dt.day_of_week

0    4
1    5
2    6
3    0
4    1
5    2
6    3
7    4
8    5
9    6
Name: Date, dtype: int32

In [101]:
df["Date"].dt.quarter

0    3
1    3
2    3
3    3
4    3
5    3
6    3
7    3
8    3
9    3
Name: Date, dtype: int32

In [103]:
datetimes = pd.date_range(start="2025-09-22 13:00:00", periods=10, freq="h")
datetimes

DatetimeIndex(['2025-09-22 13:00:00', '2025-09-22 14:00:00',
               '2025-09-22 15:00:00', '2025-09-22 16:00:00',
               '2025-09-22 17:00:00', '2025-09-22 18:00:00',
               '2025-09-22 19:00:00', '2025-09-22 20:00:00',
               '2025-09-22 21:00:00', '2025-09-22 22:00:00'],
              dtype='datetime64[ns]', freq='h')

In [104]:
df_time = pd.DataFrame({"datetime": datetimes, "Value": np.random.rand(10)})
df_time

             datetime     Value
0 2025-09-22 13:00:00  0.460814
1 2025-09-22 14:00:00  0.529781
2 2025-09-22 15:00:00  0.706731
3 2025-09-22 16:00:00  0.752350
4 2025-09-22 17:00:00  0.396867
5 2025-09-22 18:00:00  0.621931
6 2025-09-22 19:00:00  0.262975
7 2025-09-22 20:00:00  0.300341
8 2025-09-22 21:00:00  0.806020
9 2025-09-22 22:00:00  0.113627

In [105]:
df_time["datetime"].dt.hour

0    13
1    14
2    15
3    16
4    17
5    18
6    19
7    20
8    21
9    22
Name: datetime, dtype: int32

In [107]:
df_time["datetime"].dt.time

0    13:00:00
1    14:00:00
2    15:00:00
3    16:00:00
4    17:00:00
5    18:00:00
6    19:00:00
7    20:00:00
8    21:00:00
9    22:00:00
Name: datetime, dtype: object

In [108]:
df_time["datetime"].dt.date

0    2025-09-22
1    2025-09-22
2    2025-09-22
3    2025-09-22
4    2025-09-22
5    2025-09-22
6    2025-09-22
7    2025-09-22
8    2025-09-22
9    2025-09-22
Name: datetime, dtype: object

In [109]:
df_time["datetime"].dt.minute

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: datetime, dtype: int32

In [110]:
df

        Date  Value
0 2025-08-01     73
1 2025-08-02     13
2 2025-08-03     28
3 2025-08-04     31
4 2025-08-05     31
5 2025-08-06     41
6 2025-08-07     67
7 2025-08-08     43
8 2025-08-09     50
9 2025-08-10     51

In [111]:
df["Year"] = df["Date"].dt.year
df["Month Number"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Day Name"] = df["Date"].dt.day_name()
df["Day of Week"] = df["Date"].dt.day_of_week
df["Quarter"] = df["Date"].dt.quarter

In [112]:
df

        Date  Value  Year  Month Number  Day   Day Name  Day of Week  Quarter
0 2025-08-01     73  2025             8    1     Friday            4        3
1 2025-08-02     13  2025             8    2   Saturday            5        3
2 2025-08-03     28  2025             8    3     Sunday            6        3
3 2025-08-04     31  2025             8    4     Monday            0        3
4 2025-08-05     31  2025             8    5    Tuesday            1        3
5 2025-08-06     41  2025             8    6  Wednesday            2        3
6 2025-08-07     67  2025             8    7   Thursday            3        3
7 2025-08-08     43  2025             8    8     Friday            4        3
8 2025-08-09     50  2025             8    9   Saturday            5        3
9 2025-08-10     51  2025             8   10     Sunday            6        3

In [113]:
df[df["Day Name"] == "Saturday"]

        Date  Value  Year  Month Number  Day  Day Name  Day of Week  Quarter
1 2025-08-02     13  2025             8    2  Saturday            5        3
8 2025-08-09     50  2025             8    9  Saturday            5        3

In [114]:
df[df["Day of Week"] >= 3]

        Date  Value  Year  Month Number  Day  Day Name  Day of Week  Quarter
0 2025-08-01     73  2025             8    1    Friday            4        3
1 2025-08-02     13  2025             8    2  Saturday            5        3
2 2025-08-03     28  2025             8    3    Sunday            6        3
6 2025-08-07     67  2025             8    7  Thursday            3        3
7 2025-08-08     43  2025             8    8    Friday            4        3
8 2025-08-09     50  2025             8    9  Saturday            5        3
9 2025-08-10     51  2025             8   10    Sunday            6        3

In [118]:
df.groupby("Day Name")["Value"].mean().sort_values(ascending=False)

Day Name
Thursday     67.0
Friday       58.0
Wednesday    41.0
Sunday       39.5
Saturday     31.5
Monday       31.0
Tuesday      31.0
Name: Value, dtype: float64

In [119]:
df_time

             datetime     Value
0 2025-09-22 13:00:00  0.460814
1 2025-09-22 14:00:00  0.529781
2 2025-09-22 15:00:00  0.706731
3 2025-09-22 16:00:00  0.752350
4 2025-09-22 17:00:00  0.396867
5 2025-09-22 18:00:00  0.621931
6 2025-09-22 19:00:00  0.262975
7 2025-09-22 20:00:00  0.300341
8 2025-09-22 21:00:00  0.806020
9 2025-09-22 22:00:00  0.113627

In [120]:
df_time["Hour"] = df_time["datetime"].dt.hour

In [121]:
df_time

             datetime     Value  Hour
0 2025-09-22 13:00:00  0.460814    13
1 2025-09-22 14:00:00  0.529781    14
2 2025-09-22 15:00:00  0.706731    15
3 2025-09-22 16:00:00  0.752350    16
4 2025-09-22 17:00:00  0.396867    17
5 2025-09-22 18:00:00  0.621931    18
6 2025-09-22 19:00:00  0.262975    19
7 2025-09-22 20:00:00  0.300341    20
8 2025-09-22 21:00:00  0.806020    21
9 2025-09-22 22:00:00  0.113627    22

In [124]:
df_time.groupby("Hour")["Value"].mean().sort_values(ascending=False)

Hour
21    0.806020
16    0.752350
15    0.706731
18    0.621931
14    0.529781
13    0.460814
17    0.396867
20    0.300341
19    0.262975
22    0.113627
Name: Value, dtype: float64

### Datetime Indexing and Slicing

In [125]:
dates = pd.date_range(start="2025-01-01", end="2025-12-31", freq="B")
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-06',
               '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10',
               '2025-01-13', '2025-01-14',
               ...
               '2025-12-18', '2025-12-19', '2025-12-22', '2025-12-23',
               '2025-12-24', '2025-12-25', '2025-12-26', '2025-12-29',
               '2025-12-30', '2025-12-31'],
              dtype='datetime64[ns]', length=261, freq='B')

In [126]:
df = pd.DataFrame({"Value": np.random.randn(len(dates))}, index=dates)
df

               Value
2025-01-01 -0.327179
2025-01-02 -0.110161
2025-01-03  0.564055
2025-01-06  1.633285
2025-01-07 -2.187693
...              ...
2025-12-25 -0.348331
2025-12-26  1.083235
2025-12-29 -0.318194
2025-12-30  0.494976
2025-12-31 -0.920105

[261 rows x 1 columns]

In [132]:
df.loc["2025-06-25"]

Value    0.985235
Name: 2025-06-25 00:00:00, dtype: float64

In [133]:
# partial string indexing
df.loc["2025-08"]

               Value
2025-08-01  0.293453
2025-08-04 -1.550272
2025-08-05  1.173618
2025-08-06  0.485570
2025-08-07 -0.290032
2025-08-08  0.346906
2025-08-11  0.494319
2025-08-12  0.334957
2025-08-13  0.604712
2025-08-14 -0.705623
2025-08-15 -0.326467
2025-08-18 -1.889949
2025-08-19  0.784153
2025-08-20 -1.531025
2025-08-21  0.077136
2025-08-22  0.945506
2025-08-25 -1.368135
2025-08-26 -0.145616
2025-08-27  0.619696
2025-08-28 -0.879099
2025-08-29  0.531670

In [134]:
df.loc["2025-01":"2025-03"]

               Value
2025-01-01 -0.327179
2025-01-02 -0.110161
2025-01-03  0.564055
2025-01-06  1.633285
2025-01-07 -2.187693
...              ...
2025-03-25 -0.034238
2025-03-26 -1.227505
2025-03-27 -1.061764
2025-03-28 -0.326367
2025-03-31  1.003534

[64 rows x 1 columns]

In [135]:
df.loc["2025-12-10":]

               Value
2025-12-10 -0.696467
2025-12-11 -0.453706
2025-12-12  0.007060
2025-12-15 -1.473886
2025-12-16 -0.717624
2025-12-17 -0.055821
2025-12-18  0.389837
2025-12-19 -0.529083
2025-12-22  3.364667
2025-12-23 -0.267036
2025-12-24 -0.405987
2025-12-25 -0.348331
2025-12-26  1.083235
2025-12-29 -0.318194
2025-12-30  0.494976
2025-12-31 -0.920105

In [136]:
df.tail(6)

               Value
2025-12-24 -0.405987
2025-12-25 -0.348331
2025-12-26  1.083235
2025-12-29 -0.318194
2025-12-30  0.494976
2025-12-31 -0.920105

In [139]:
df.loc[:"2025-04-28"]

               Value
2025-01-01 -0.327179
2025-01-02 -0.110161
2025-01-03  0.564055
2025-01-06  1.633285
2025-01-07 -2.187693
...              ...
2025-04-22  1.780658
2025-04-23  0.562343
2025-04-24  0.929849
2025-04-25 -0.556908
2025-04-28 -0.036326

[84 rows x 1 columns]

In [140]:
df.loc["2025-01":"2025-06"]

               Value
2025-01-01 -0.327179
2025-01-02 -0.110161
2025-01-03  0.564055
2025-01-06  1.633285
2025-01-07 -2.187693
...              ...
2025-06-24  0.379094
2025-06-25  0.985235
2025-06-26 -0.316700
2025-06-27 -0.150146
2025-06-30 -0.905697

[129 rows x 1 columns]

In [143]:
df[df.index.day_name() == "Tuesday"]

               Value
2025-01-07 -2.187693
2025-01-14  0.169465
2025-01-21  0.254375
2025-01-28  0.925481
2025-02-04  0.696978
2025-02-11  0.862391
2025-02-18 -0.452298
2025-02-25 -0.610740
2025-03-04  0.452786
2025-03-11  0.286475
2025-03-18 -0.197036
2025-03-25 -0.034238
2025-04-01 -1.511335
2025-04-08 -0.801491
2025-04-15 -0.432564
2025-04-22  1.780658
2025-04-29 -2.521191
2025-05-06  0.117105
2025-05-13  2.243891
2025-05-20  0.172460
2025-05-27 -1.647257
2025-06-03 -1.498392
2025-06-10  0.102134
2025-06-17 -0.583524
2025-06-24  0.379094
2025-07-01  0.182639
2025-07-08  0.292639
2025-07-15 -0.025373
2025-07-22  2.065404
2025-07-29 -0.324288
2025-08-05  1.173618
2025-08-12  0.334957
2025-08-19  0.784153
2025-08-26 -0.145616
2025-09-02 -0.004891
2025-09-09  0.119018
2025-09-16  0.577513
2025-09-23 -0.103593
2025-09-30  2.208443
2025-10-07  0.920573
2025-10-14  0.152665
2025-10-21 -0.370404
2025-10-28 -0.243099
2025-11-04 -0.442223
2025-11-11 -0.313732
2025-11-18  0.892267
2025-11-25  0.232226
2025-12-02  1.863426
2025-12-09 -0.175911
2025-12-16 -0.717624
2025-12-23 -0.267036
2025-12-30  0.494976

In [146]:
df[df.index.month == 4]

               Value
2025-04-01 -1.511335
2025-04-02  1.531437
2025-04-03  0.292134
2025-04-04 -0.778838
2025-04-07  0.465096
2025-04-08 -0.801491
2025-04-09  0.519815
2025-04-10  0.335380
2025-04-11  0.154952
2025-04-14  0.288088
2025-04-15 -0.432564
2025-04-16  2.008550
2025-04-17  1.730273
2025-04-18  1.542164
2025-04-21 -0.483206
2025-04-22  1.780658
2025-04-23  0.562343
2025-04-24  0.929849
2025-04-25 -0.556908
2025-04-28 -0.036326
2025-04-29 -2.521191
2025-04-30 -0.543858

In [148]:
df[(df.index.day_name() == "Friday") & (df.index.quarter == 2)]

               Value
2025-04-04 -0.778838
2025-04-11  0.154952
2025-04-18  1.542164
2025-04-25 -0.556908
2025-05-02  0.160400
2025-05-09  0.439835
2025-05-16  0.715292
2025-05-23  2.010895
2025-05-30 -0.118025
2025-06-06  0.389462
2025-06-13  0.176182
2025-06-20 -0.825487
2025-06-27 -0.150146

In [150]:
df[df.index.day > 16]

               Value
2025-01-17  1.424899
2025-01-20 -1.451640
2025-01-21  0.254375
2025-01-22 -0.686715
2025-01-23 -0.854756
...              ...
2025-12-25 -0.348331
2025-12-26  1.083235
2025-12-29 -0.318194
2025-12-30  0.494976
2025-12-31 -0.920105

[125 rows x 1 columns]

In [152]:
df[(df.index.month == 8) & (df.index.day_name() == "Thursday") & (df["Value"] > 0)]

               Value
2025-08-21  0.077136

In [156]:
df.resample("ME").max()

               Value
2025-01-31  1.633285
2025-02-28  1.310296
2025-03-31  2.375319
2025-04-30  2.008550
2025-05-31  2.243891
2025-06-30  1.262955
2025-07-31  2.300279
2025-08-31  1.173618
2025-09-30  2.208443
2025-10-31  1.226435
2025-11-30  2.914124
2025-12-31  3.364667

In [162]:
df.groupby(df.index.day_name())["Value"].mean().sort_values(ascending=False)

Tuesday      0.098582
Friday       0.094594
Wednesday    0.059708
Thursday    -0.024725
Monday      -0.075861
Name: Value, dtype: float64

### Parsing and Formatting Dates

In [163]:
date_str = "2025-07-14"
pd.to_datetime(date_str, yearfirst=True)

Timestamp('2025-07-14 00:00:00')

In [164]:
dates = ['2023-06-15', '15/06/2023', 'June 15, 2023', '20230615']

In [165]:
pd.to_datetime(dates, format="mixed")

DatetimeIndex(['2023-06-15', '2023-06-15', '2023-06-15', '2023-06-15'], dtype='datetime64[ns]', freq=None)

In [168]:
custom_date = "15-Jan-26"
pd.to_datetime(custom_date, format="%d-%b-%y")

Timestamp('2026-01-15 00:00:00')

In [170]:
df = pd.DataFrame({
    "date string": ["2025-02-18", "2026-08-14", "2025-11-23"],
    "value": [10, 20, 30]
})

In [171]:
df

  date string  value
0  2025-02-18     10
1  2026-08-14     20
2  2025-11-23     30

In [177]:
print(df["date string"].dtype)

object

In [173]:
df["date"] = pd.to_datetime(df["date string"])

In [174]:
df

  date string  value       date
0  2025-02-18     10 2025-02-18
1  2026-08-14     20 2026-08-14
2  2025-11-23     30 2025-11-23

In [176]:
print(df["date"].dtype)

datetime64[ns]

In [178]:
dates = pd.date_range(start="2025-08-12", periods=4)
s = pd.Series(dates)
s

0   2025-08-12
1   2025-08-13
2   2025-08-14
3   2025-08-15
dtype: datetime64[ns]

In [180]:
s.dt.strftime("%Y-%m-%d")

0    2025-08-12
1    2025-08-13
2    2025-08-14
3    2025-08-15
dtype: object

In [181]:
s.dt.strftime("%A, %b %d, %Y")

0      Tuesday, Aug 12, 2025
1    Wednesday, Aug 13, 2025
2     Thursday, Aug 14, 2025
3       Friday, Aug 15, 2025
dtype: object