# Coding Practice Session 11
## Categorical Data in Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(
    {
        "ID": np.arange(1, 11, dtype="u1"),
        "Color": [
            "Red",
            "Blue",
            "Green",
            "Red",
            "Green",
            "Blue",
            "Red",
            "Green",
            "Blue",
            "Red",
        ],
        "Size": [
            "Small",
            "Medium",
            "Large",
            "Medium",
            "Small",
            "Large",
            "Medium",
            "Small",
            "Large",
            "Medium",
        ],
        "Rating": [
            "Good",
            "Excellent",
            "Fair",
            "Good",
            "Excellent",
            "Fair",
            "Good",
            "Fair",
            "Excellent",
            "Good",
        ],
    }
)

df

   ID  Color    Size     Rating
0   1    Red   Small       Good
1   2   Blue  Medium  Excellent
2   3  Green   Large       Fair
3   4    Red  Medium       Good
4   5  Green   Small  Excellent
5   6   Blue   Large       Fair
6   7    Red  Medium       Good
7   8  Green   Small       Fair
8   9   Blue   Large  Excellent
9  10    Red  Medium       Good

In [3]:
df.dtypes

ID         uint8
Color     object
Size      object
Rating    object
dtype: object

In [4]:
df["Color"] = pd.Categorical(df["Color"])
df["Size"] = pd.Categorical(df["Size"])
df["Rating"] = pd.Categorical(df["Rating"])

In [5]:
df.dtypes

ID           uint8
Color     category
Size      category
Rating    category
dtype: object

In [6]:
df

   ID  Color    Size     Rating
0   1    Red   Small       Good
1   2   Blue  Medium  Excellent
2   3  Green   Large       Fair
3   4    Red  Medium       Good
4   5  Green   Small  Excellent
5   6   Blue   Large       Fair
6   7    Red  Medium       Good
7   8  Green   Small       Fair
8   9   Blue   Large  Excellent
9  10    Red  Medium       Good

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     uint8
 1   Color   10 non-null     category
 2   Size    10 non-null     category
 3   Rating  10 non-null     category
dtypes: category(3), uint8(1)
memory usage: 568.0 bytes

### Creating and Converting Categorical Data

In [8]:
colors = pd.Categorical(["Red", "Blue", "Green", "Khaki", "Red", "Blue"])

In [9]:
type(colors)

pandas.core.arrays.categorical.Categorical

In [10]:
colors

['Red', 'Blue', 'Green', 'Khaki', 'Red', 'Blue']
Categories (4, object): ['Blue', 'Green', 'Khaki', 'Red']

In [11]:
colors.dtype

CategoricalDtype(categories=['Blue', 'Green', 'Khaki', 'Red'], ordered=False, categories_dtype=object)

In [12]:
sizes = pd.Categorical(
    ["Medium", "Small", "Large", "Small", "Medium", "Small"],
    categories=["Small", "Medium", "Large"],
)

In [13]:
sizes

['Medium', 'Small', 'Large', 'Small', 'Medium', 'Small']
Categories (3, object): ['Small', 'Medium', 'Large']

In [14]:
sizes.dtype

CategoricalDtype(categories=['Small', 'Medium', 'Large'], ordered=False, categories_dtype=object)

In [ ]:
ratings = pd.Categorical(
    ["Fair", "Good", "Excellent", "Good", "Good"],
    categories=["Poor", "Fair", "Good", "Excellent"],
    ordered=True,
)

In [16]:
ratings

['Fair', 'Good', 'Excellent', 'Good', 'Good']
Categories (4, object): ['Poor' < 'Fair' < 'Good' < 'Excellent']

In [17]:
ratings.dtype

CategoricalDtype(categories=['Poor', 'Fair', 'Good', 'Excellent'], ordered=True, categories_dtype=object)

In [ ]:
df = pd.DataFrame(
    {
        "Color": ["Red", "Blue", "Green", "Red", "Green"],
        "Size": ["Small", "Medium", "Large", "Medium", "Small"],
        "Rating": ["Good", "Excellent", "Fair", "Good", "Excellent"],
    }
)
df

   Color    Size     Rating
0    Red   Small       Good
1   Blue  Medium  Excellent
2  Green   Large       Fair
3    Red  Medium       Good
4  Green   Small  Excellent

In [19]:
df["Color"] = df["Color"].astype("category")

In [20]:
df["Color"]

0      Red
1     Blue
2    Green
3      Red
4    Green
Name: Color, dtype: category
Categories (3, object): ['Blue', 'Green', 'Red']

In [21]:
df[["Size", "Rating"]] = df[["Size", "Rating"]].astype("category")

In [22]:
df

   Color    Size     Rating
0    Red   Small       Good
1   Blue  Medium  Excellent
2  Green   Large       Fair
3    Red  Medium       Good
4  Green   Small  Excellent

In [23]:
df.dtypes

Color     category
Size      category
Rating    category
dtype: object

In [ ]:
df["Size"] = pd.Categorical(
    df["Size"], categories=["Small", "Medium", "Large"], ordered=True
)

In [ ]:
df["Rating"] = pd.Categorical(
    df["Rating"], categories=["Poor", "Fair", "Good", "Excellent"], ordered=True
)

In [26]:
df[["Size", "Rating"]]

     Size     Rating
0   Small       Good
1  Medium  Excellent
2   Large       Fair
3  Medium       Good
4   Small  Excellent

In [27]:
df["Size"]

0     Small
1    Medium
2     Large
3    Medium
4     Small
Name: Size, dtype: category
Categories (3, object): ['Small' < 'Medium' < 'Large']

In [28]:
df["Rating"]

0         Good
1    Excellent
2         Fair
3         Good
4    Excellent
Name: Rating, dtype: category
Categories (4, object): ['Poor' < 'Fair' < 'Good' < 'Excellent']

In [29]:
# using .cat accessor
df["Size"].cat.ordered

True

In [30]:
df["Color"].cat.categories

Index(['Blue', 'Green', 'Red'], dtype='object')

In [31]:
df["Size"].cat.codes

0    0
1    1
2    2
3    1
4    0
dtype: int8

In [32]:
# comparing values using .cat.codes attribute
df["Size"].cat.codes.iloc[0] < df["Size"].cat.codes.iloc[2]

np.True_

In [33]:
df["Size"].iloc[0], df["Size"].iloc[2]

('Small', 'Large')

In [34]:
df["Color"].cat.reorder_categories(["Blue", "Green", "Red"], ordered=True)

0      Red
1     Blue
2    Green
3      Red
4    Green
Name: Color, dtype: category
Categories (3, object): ['Blue' < 'Green' < 'Red']

In [35]:
df

   Color    Size     Rating
0    Red   Small       Good
1   Blue  Medium  Excellent
2  Green   Large       Fair
3    Red  Medium       Good
4  Green   Small  Excellent

In [36]:
df.sort_values(["Size", "Rating"], ascending=False)

   Color    Size     Rating
2  Green   Large       Fair
1   Blue  Medium  Excellent
3    Red  Medium       Good
4  Green   Small  Excellent
0    Red   Small       Good

### Working with Categorical Data

In [ ]:
df = pd.DataFrame(
    {
        "Color": pd.Categorical(["Red", "Blue", "Green", "Red", "Green"]),
        "Size": pd.Categorical(
            ["Small", "Medium", "Large", "Medium", "Large"],
            categories=["Small", "Medium", "Large"],
            ordered=True,
        ),
    }
)

In [38]:
df

   Color    Size
0    Red   Small
1   Blue  Medium
2  Green   Large
3    Red  Medium
4  Green   Large

In [39]:
df.dtypes

Color    category
Size     category
dtype: object

In [40]:
df["Color"].cat.categories

Index(['Blue', 'Green', 'Red'], dtype='object')

In [41]:
df["Size"].cat.categories

Index(['Small', 'Medium', 'Large'], dtype='object')

In [42]:
df["Size"].cat.ordered

True

In [43]:
df["Color"].cat.codes

0    2
1    0
2    1
3    2
4    1
dtype: int8

In [44]:
df["Color"] = df["Color"].cat.add_categories(["Yellow"])

In [45]:
df["Color"]

0      Red
1     Blue
2    Green
3      Red
4    Green
Name: Color, dtype: category
Categories (4, object): ['Blue', 'Green', 'Red', 'Yellow']

In [46]:
df["Color"].cat.categories

Index(['Blue', 'Green', 'Red', 'Yellow'], dtype='object')

In [47]:
df["Color"].cat.remove_categories(["Blue"])

0      Red
1      NaN
2    Green
3      Red
4    Green
Name: Color, dtype: category
Categories (3, object): ['Green', 'Red', 'Yellow']

Removed data category is replaced by nan

In [48]:
df["Color"].cat.categories

Index(['Blue', 'Green', 'Red', 'Yellow'], dtype='object')

In [49]:
df["Color"].cat.remove_unused_categories()

0      Red
1     Blue
2    Green
3      Red
4    Green
Name: Color, dtype: category
Categories (3, object): ['Blue', 'Green', 'Red']

In [ ]:
df["Size"] = df["Size"].cat.set_categories(
    ["Tiny", "Small", "Medium", "Large", "Huge"], ordered=True
)

In [51]:
df["Size"]

0     Small
1    Medium
2     Large
3    Medium
4     Large
Name: Size, dtype: category
Categories (5, object): ['Tiny' < 'Small' < 'Medium' < 'Large' < 'Huge']

In [52]:
df

   Color    Size
0    Red   Small
1   Blue  Medium
2  Green   Large
3    Red  Medium
4  Green   Large

In [53]:
df["Color"] = df["Color"].cat.add_categories(["Purple", "Orange"])

In [54]:
df["Color"]

0      Red
1     Blue
2    Green
3      Red
4    Green
Name: Color, dtype: category
Categories (6, object): ['Blue', 'Green', 'Red', 'Yellow', 'Purple', 'Orange']

In [55]:
df["Color"].unique()

['Red', 'Blue', 'Green']
Categories (6, object): ['Blue', 'Green', 'Red', 'Yellow', 'Purple', 'Orange']

In [56]:
df["Color"].cat.categories

Index(['Blue', 'Green', 'Red', 'Yellow', 'Purple', 'Orange'], dtype='object')

In [57]:
df["Color"] = df["Color"].cat.rename_categories({"Red": "Crimson", "Blue": "Navy"})

In [58]:
df["Color"]

0    Crimson
1       Navy
2      Green
3    Crimson
4      Green
Name: Color, dtype: category
Categories (6, object): ['Navy', 'Green', 'Crimson', 'Yellow', 'Purple', 'Orange']

In [59]:
df["Color"].cat.rename_categories({"Green": "Lime"})

0    Crimson
1       Navy
2       Lime
3    Crimson
4       Lime
Name: Color, dtype: category
Categories (6, object): ['Navy', 'Lime', 'Crimson', 'Yellow', 'Purple', 'Orange']

In [60]:
df["Size"]

0     Small
1    Medium
2     Large
3    Medium
4     Large
Name: Size, dtype: category
Categories (5, object): ['Tiny' < 'Small' < 'Medium' < 'Large' < 'Huge']

In [61]:
df["Size"] = df["Size"].cat.rename_categories(["XS", "S", "M", "L", "XL"])

In [62]:
df["Size"]

0    S
1    M
2    L
3    M
4    L
Name: Size, dtype: category
Categories (5, object): ['XS' < 'S' < 'M' < 'L' < 'XL']

In [63]:
df["Size"].cat.categories

Index(['XS', 'S', 'M', 'L', 'XL'], dtype='object')

In [64]:
df["Size"].cat.ordered

True

In [65]:
df["Color"].cat.rename_categories(lambda color: color.upper())

0    CRIMSON
1       NAVY
2      GREEN
3    CRIMSON
4      GREEN
Name: Color, dtype: category
Categories (6, object): ['NAVY', 'GREEN', 'CRIMSON', 'YELLOW', 'PURPLE', 'ORANGE']

In [66]:
df["Rating"] = pd.Categorical(["Good", "Fair", "Excellent", "Good", "Fair"])

In [67]:
df

     Color Size     Rating
0  Crimson    S       Good
1     Navy    M       Fair
2    Green    L  Excellent
3  Crimson    M       Good
4    Green    L       Fair

In [ ]:
df["Rating"] = df["Rating"].cat.rename_categories(
    {"Good": "Average", "Excellent": "Outstanding"}
)

In [69]:
df["Rating"]

0        Average
1           Fair
2    Outstanding
3        Average
4           Fair
Name: Rating, dtype: category
Categories (3, object): ['Outstanding', 'Fair', 'Average']

In [70]:
df["Rating"].cat.set_categories(["Fair", "Average", "Outstanding"], ordered=True)

0        Average
1           Fair
2    Outstanding
3        Average
4           Fair
Name: Rating, dtype: category
Categories (3, object): ['Fair' < 'Average' < 'Outstanding']

In [71]:
df

     Color Size       Rating
0  Crimson    S      Average
1     Navy    M         Fair
2    Green    L  Outstanding
3  Crimson    M      Average
4    Green    L         Fair

### Sorting and Ordering Categorical Data

In [ ]:
sizes = pd.Categorical(
    ["Medium", "Small", "Large", "Small", "Medium"],
    categories=["Small", "Medium", "Large"],
    ordered=True,
)

In [73]:
df = pd.DataFrame({"Size": sizes, "Count": [5, 2, 8, 3, 4]})

In [74]:
df

     Size  Count
0  Medium      5
1   Small      2
2   Large      8
3   Small      3
4  Medium      4

In [76]:
df["Size"].cat.categories

Index(['Small', 'Medium', 'Large'], dtype='object')

In [77]:
df.sort_values("Size")

     Size  Count
1   Small      2
3   Small      3
0  Medium      5
4  Medium      4
2   Large      8

In [78]:
df.sort_values("Size", ascending=False)

     Size  Count
2   Large      8
0  Medium      5
4  Medium      4
1   Small      2
3   Small      3

In [79]:
df = pd.DataFrame(
    {
        "Color": pd.Categorical(["Red", "Blue", "Green", "Blue", "Red"]),
        "Value": np.array([10, 20, 15, 25, 5], dtype="u1"),
    }
)

In [80]:
df

   Color  Value
0    Red     10
1   Blue     20
2  Green     15
3   Blue     25
4    Red      5

In [ ]:
df.sort_values(["Color", "Value"])  # sorts alphabetically

   Color  Value
1   Blue     20
3   Blue     25
2  Green     15
4    Red      5
0    Red     10

In [84]:
custom_order = ["Red", "Blue", "Green"]
df["Color"] = df["Color"].cat.reorder_categories(custom_order, ordered=True)

In [85]:
df["Color"]

0      Red
1     Blue
2    Green
3     Blue
4      Red
Name: Color, dtype: category
Categories (3, object): ['Red' < 'Blue' < 'Green']

In [86]:
df["Color"].cat.ordered

True

In [87]:
df.sort_values("Color")

   Color  Value
0    Red     10
4    Red      5
1   Blue     20
3   Blue     25
2  Green     15

In [89]:
df.sort_values(["Color", "Value"], ascending=False)

   Color  Value
2  Green     15
3   Blue     25
1   Blue     20
0    Red     10
4    Red      5

In [91]:
size_index = pd.Categorical(
    ["Medium", "Small", "Large", "Tiny", "Huge"],
    categories=["Tiny", "Small", "Medium", "Large", "Huge"],
    ordered=True,
)

In [92]:
df = pd.DataFrame({"Value": [10, 20, 30, 40, 50]}, index=size_index)

In [93]:
df

        Value
Medium     10
Small      20
Large      30
Tiny       40
Huge       50

In [95]:
df.sort_index()

        Value
Tiny       40
Small      20
Medium     10
Large      30
Huge       50

In [96]:
df = pd.DataFrame(
    {
        "Category": pd.Categorical(
            ["A", "B", np.nan, "C", "B", np.nan],
            categories=["A", "B", "C"],
            ordered=True,
        )
    }
)

In [97]:
df

  Category
0        A
1        B
2      NaN
3        C
4        B
5      NaN

In [99]:
df.sort_values("Category")

  Category
0        A
1        B
4        B
3        C
2      NaN
5      NaN

In [ ]:
df.sort_values("Category", na_position="first")

  Category
0        A
1        B
4        B
3        C

In [102]:
df.dropna()

  Category
0        A
1        B
3        C
4        B

### Memory Efficiency of Categorical Data

In [ ]:
n = 1_000_000
df = pd.DataFrame({"Category_str": np.random.choice(list("ABCDE"), size=n)})

In [106]:
df

       Category_str
0                 E
1                 B
2                 B
3                 D
4                 B
...             ...
999995            E
999996            C
999997            B
999998            B
999999            E

[1000000 rows x 1 columns]

In [108]:
df.memory_usage(deep=True, index=False)

Category_str    58000000
dtype: int64

In [ ]:
58000000 / 1e6  # memory consumption in megabytes

58.0

In [111]:
df["Category_cat"] = df["Category_str"].astype("category")

In [112]:
df

       Category_str Category_cat
0                 E            E
1                 B            B
2                 B            B
3                 D            D
4                 B            B
...             ...          ...
999995            E            E
999996            C            C
999997            B            B
999998            B            B
999999            E            E

[1000000 rows x 2 columns]

In [113]:
df.memory_usage(deep=True, index=False)

Category_str    58000000
Category_cat     1000462
dtype: int64

In [114]:
1000462 / 1e6

1.000462

In [118]:
str(np.round(58 / 1.000462, decimals=2))

'57.97'

In [ ]:
m = 5_000_000
df = pd.DataFrame(
    {
        "String": np.random.choice(list("ABCDE"), size=m),
        "Categorical": pd.Categorical(np.random.choice(list("ABCDE"), size=m)),
    }
)

In [120]:
df

        String Categorical
0            C           A
1            A           D
2            D           E
3            A           D
4            A           B
...        ...         ...
4999995      E           D
4999996      D           E
4999997      C           A
4999998      D           D
4999999      D           B

[5000000 rows x 2 columns]

In [121]:
df.memory_usage(index=False, deep=True)

String         290000000
Categorical      5000462
dtype: int64

In [123]:
%timeit df["String"].value_counts()

154 ms ± 36.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [124]:
%timeit df["Categorical"].value_counts()

20.9 ms ± 3.78 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [126]:
print(f"Using Categorical data is {154 / 20.9: .2f} times faster than raw string data")

Using Categorical data is  7.37 times faster than raw string data

### Encoding Categorical Data

In [127]:
# One-Hot encoding
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red", "Green"],
    "Size": ["Medium", "Large", "Small", "Medium", "Small"]
})

In [128]:
df

   Color    Size
0    Red  Medium
1   Blue   Large
2  Green   Small
3    Red  Medium
4  Green   Small

In [129]:
df_encoded = pd.get_dummies(df, columns=["Color"])

In [130]:
df_encoded

     Size  Color_Blue  Color_Green  Color_Red
0  Medium       False        False       True
1   Large        True        False      False
2   Small       False         True      False
3  Medium       False        False       True
4   Small       False         True      False

In [133]:
pd.get_dummies(df, columns=["Color"], prefix="C", prefix_sep="-")

     Size  C-Blue  C-Green  C-Red
0  Medium   False    False   True
1   Large    True    False  False
2   Small   False     True  False
3  Medium   False    False   True
4   Small   False     True  False

In [134]:
# ordinal encoding
df = pd.DataFrame({
    "Size": ["Small", "Large", "Medium", "Large", "Small"],
    "Quality": ["Low", "Average", "High", "Low", "High"],
})

df

     Size  Quality
0   Small      Low
1   Large  Average
2  Medium     High
3   Large      Low
4   Small     High

In [135]:
df["Size Encoded"] = pd.Categorical(df["Size"], categories=["Small", "Medium", "Large"], ordered=True).codes
df["Quality Encoded"] = pd.Categorical(df["Quality"], categories=["Low", "Average", "High"], ordered=True).codes

In [136]:
df

     Size  Quality  Size Encoded  Quality Encoded
0   Small      Low             0                0
1   Large  Average             2                1
2  Medium     High             1                2
3   Large      Low             2                0
4   Small     High             0                2

In [137]:
df.dtypes

Size               object
Quality            object
Size Encoded         int8
Quality Encoded      int8
dtype: object