# Coding Practice Session 12
## Merging, Joining, and Concatenating DataFrames

In [1]:
import pandas as pd

In [2]:
customers = pd.DataFrame(
    {
        "customer_id": [1, 2, 3, 4, 5],
        "name": [
            "John Doe",
            "Jane Smith",
            "Bob Johnson",
            "Alice Brown",
            "Charlie Davis",
        ],
        "email": [
            "john@example.com",
            "jane@example.com",
            "bob@example.com",
            "alice@example.com",
            "charlie@example.com",
        ],
    }
)

In [3]:
orders = pd.DataFrame(
    {
        "order_id": [101, 102, 103, 104, 105, 106],
        "customer_id": [3, 2, 1, 3, 5, 99],
        "order_date": [
            "2025-06-15",
            "2025-06-16",
            "2025-06-17",
            "2025-06-18",
            "2025-06-19",
            "2025-06-20",
        ],
        "total_amount": [150.50, 200.75, 50.25, 300.00, 175.80, 123.00],
    }
)

In [4]:
products = pd.DataFrame(
    {
        "product_id": ["P1", "P2", "P3", "P4", "P5"],
        "product_name": ["Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch"],
        "category": [
            "Electronics",
            "Electronics",
            "Electronics",
            "Accessories",
            "Accessories",
        ],
        "price": [1200.00, 800.00, 500.00, 150.00, 250.00],
    }
)

In [5]:
customers

   customer_id           name                email
0            1       John Doe     john@example.com
1            2     Jane Smith     jane@example.com
2            3    Bob Johnson      bob@example.com
3            4    Alice Brown    alice@example.com
4            5  Charlie Davis  charlie@example.com

In [6]:
orders

   order_id  customer_id  order_date  total_amount
0       101            3  2025-06-15        150.50
1       102            2  2025-06-16        200.75
2       103            1  2025-06-17         50.25
3       104            3  2025-06-18        300.00
4       105            5  2025-06-19        175.80
5       106           99  2025-06-20        123.00

In [7]:
products

  product_id product_name     category   price
0         P1       Laptop  Electronics  1200.0
1         P2   Smartphone  Electronics   800.0
2         P3       Tablet  Electronics   500.0
3         P4   Headphones  Accessories   150.0
4         P5   Smartwatch  Accessories   250.0

### Concatenating DataFrames

In [8]:
customers_us = pd.DataFrame(
    {
        "customer_id": [1, 2, 3],
        "name": ["John Doe", "Jane Smith", "Bob Johnson"],
        "country": ["USA", "USA", "USA"],
    }
)

In [9]:
customers_us

   customer_id         name country
0            1     John Doe     USA
1            2   Jane Smith     USA
2            3  Bob Johnson     USA

In [10]:
customers_uk = pd.DataFrame(
    {
        "customer_id": [4, 5, 6],
        "name": ["Alice Brown", "Charlie Davis", "Emma Wilson"],
        "country": ["UK", "UK", "UK"],
    }
)

customers_uk

   customer_id           name country
0            4    Alice Brown      UK
1            5  Charlie Davis      UK
2            6    Emma Wilson      UK

In [11]:
pd.concat([customers_us, customers_uk])

   customer_id           name country
0            1       John Doe     USA
1            2     Jane Smith     USA
2            3    Bob Johnson     USA
0            4    Alice Brown      UK
1            5  Charlie Davis      UK
2            6    Emma Wilson      UK

In [12]:
customer_info = pd.DataFrame(
    {
        "customer_id": [1, 2, 3, 4],
        "name": ["John Doe", "Jane Smith", "Bob Johnson", "Alice Brown"],
    }
)

customer_info

   customer_id         name
0            1     John Doe
1            2   Jane Smith
2            3  Bob Johnson
3            4  Alice Brown

In [13]:
customer_orders = pd.DataFrame(
    {
        "customer_id": [1, 2, 3, 4],
        "total_orders": [5, 3, 7, 2],
        "total_spend": [500, 300, 700, 200],
    }
)

customer_orders

   customer_id  total_orders  total_spend
0            1             5          500
1            2             3          300
2            3             7          700
3            4             2          200

In [14]:
pd.concat([customer_info, customer_orders], axis=1)

   customer_id         name  customer_id  total_orders  total_spend
0            1     John Doe            1             5          500
1            2   Jane Smith            2             3          300
2            3  Bob Johnson            3             7          700
3            4  Alice Brown            4             2          200

In [15]:
customer_orders = customer_orders.rename(
    index=dict(zip(customer_orders.index, list("ABCD")))
)
customer_orders

   customer_id  total_orders  total_spend
A            1             5          500
B            2             3          300
C            3             7          700
D            4             2          200

In [16]:
customer_orders

   customer_id  total_orders  total_spend
A            1             5          500
B            2             3          300
C            3             7          700
D            4             2          200

In [17]:
pd.concat([customer_info, customer_orders], axis=1)

   customer_id         name  customer_id  total_orders  total_spend
0          1.0     John Doe          NaN           NaN          NaN
1          2.0   Jane Smith          NaN           NaN          NaN
2          3.0  Bob Johnson          NaN           NaN          NaN
3          4.0  Alice Brown          NaN           NaN          NaN
A          NaN          NaN          1.0           5.0        500.0
B          NaN          NaN          2.0           3.0        300.0
C          NaN          NaN          3.0           7.0        700.0
D          NaN          NaN          4.0           2.0        200.0

In [18]:
pd.concat([customers_us, customers_uk]).reset_index(drop=True)

   customer_id           name country
0            1       John Doe     USA
1            2     Jane Smith     USA
2            3    Bob Johnson     USA
3            4    Alice Brown      UK
4            5  Charlie Davis      UK
5            6    Emma Wilson      UK

In [26]:
# hierarchial index
df = pd.concat([customers_us, customers_uk], axis=0, keys=["US", "UK"])
df

      customer_id           name country
US 0            1       John Doe     USA
   1            2     Jane Smith     USA
   2            3    Bob Johnson     USA
UK 0            4    Alice Brown      UK
   1            5  Charlie Davis      UK
   2            6    Emma Wilson      UK

In [29]:
df.loc["US"]

   customer_id         name country
0            1     John Doe     USA
1            2   Jane Smith     USA
2            3  Bob Johnson     USA

In [30]:
df.loc[("UK", 0), "name"]

'Alice Brown'

In [31]:
pd.concat([customers_us, customers_uk], ignore_index=True)

   customer_id           name country
0            1       John Doe     USA
1            2     Jane Smith     USA
2            3    Bob Johnson     USA
3            4    Alice Brown      UK
4            5  Charlie Davis      UK
5            6    Emma Wilson      UK

In [32]:
customers_us["state"] = ["NY", "CA", "TX"]
customers_us

   customer_id         name country state
0            1     John Doe     USA    NY
1            2   Jane Smith     USA    CA
2            3  Bob Johnson     USA    TX

In [33]:
pd.concat([customers_us, customers_uk], join="inner", ignore_index=True)

   customer_id           name country
0            1       John Doe     USA
1            2     Jane Smith     USA
2            3    Bob Johnson     USA
3            4    Alice Brown      UK
4            5  Charlie Davis      UK
5            6    Emma Wilson      UK

In [34]:
pd.concat([customers_us, customers_uk], join="outer", ignore_index=True)

   customer_id           name country state
0            1       John Doe     USA    NY
1            2     Jane Smith     USA    CA
2            3    Bob Johnson     USA    TX
3            4    Alice Brown      UK   NaN
4            5  Charlie Davis      UK   NaN
5            6    Emma Wilson      UK   NaN

In [35]:
customers_uk["loyalty_score"] = [100, 150, 75]
customers_uk

   customer_id           name country  loyalty_score
0            4    Alice Brown      UK            100
1            5  Charlie Davis      UK            150
2            6    Emma Wilson      UK             75

In [36]:
pd.concat([customers_us, customers_uk])

   customer_id           name country state  loyalty_score
0            1       John Doe     USA    NY            NaN
1            2     Jane Smith     USA    CA            NaN
2            3    Bob Johnson     USA    TX            NaN
0            4    Alice Brown      UK   NaN          100.0
1            5  Charlie Davis      UK   NaN          150.0
2            6    Emma Wilson      UK   NaN           75.0

### Merging DataFrames

In [37]:
customers

   customer_id           name                email
0            1       John Doe     john@example.com
1            2     Jane Smith     jane@example.com
2            3    Bob Johnson      bob@example.com
3            4    Alice Brown    alice@example.com
4            5  Charlie Davis  charlie@example.com

In [38]:
orders

   order_id  customer_id  order_date  total_amount
0       101            3  2025-06-15        150.50
1       102            2  2025-06-16        200.75
2       103            1  2025-06-17         50.25
3       104            3  2025-06-18        300.00
4       105            5  2025-06-19        175.80
5       106           99  2025-06-20        123.00

In [39]:
# inner merge
pd.merge(customers, orders, on="customer_id", how="inner")

,customer_id,name,email,order_id,order_date,total_amount
0,1,John Doe,john@example.com,103,2025-06-17,50.25
1,2,Jane Smith,jane@example.com,102,2025-06-16,200.75
2,3,Bob Johnson,bob@example.com,101,2025-06-15,150.50
3,3,Bob Johnson,bob@example.com,104,2025-06-18,300.00
4,5,Charlie Davis,charlie@example.com,105,2025-06-19,175.80

In [41]:
# outer merge
pd.merge(customers, orders, on="customer_id", how="outer")

,customer_id,name,email,order_id,order_date,total_amount
0,1,John Doe,john@example.com,103.0,2025-06-17,50.25
1,2,Jane Smith,jane@example.com,102.0,2025-06-16,200.75
2,3,Bob Johnson,bob@example.com,101.0,2025-06-15,150.50
3,3,Bob Johnson,bob@example.com,104.0,2025-06-18,300.00
4,4,Alice Brown,alice@example.com,NaN,NaN,NaN
5,5,Charlie Davis,charlie@example.com,105.0,2025-06-19,175.80
6,99,NaN,NaN,106.0,2025-06-20,123.00

In [42]:
pd.merge(customers, orders, how="cross")

,customer_id_x,name,email,order_id,customer_id_y,order_date,total_amount
0,1,John Doe,john@example.com,101,3,2025-06-15,150.50
1,1,John Doe,john@example.com,102,2,2025-06-16,200.75
2,1,John Doe,john@example.com,103,1,2025-06-17,50.25
3,1,John Doe,john@example.com,104,3,2025-06-18,300.00
4,1,John Doe,john@example.com,105,5,2025-06-19,175.80
5,1,John Doe,john@example.com,106,99,2025-06-20,123.00
6,2,Jane Smith,jane@example.com,101,3,2025-06-15,150.50
7,2,Jane Smith,jane@example.com,102,2,2025-06-16,200.75
8,2,Jane Smith,jane@example.com,103,1,2025-06-17,50.25
9,2,Jane Smith,jane@example.com,104,3,2025-06-18,300.00
10,2,Jane Smith,jane@example.com,105,5,2025-06-19,175.80
11,2,Jane Smith,jane@example.com,106,99,2025-06-20,123.00
12,3,Bob Johnson,bob@example.com,101,3,2025-06-15,150.50
13,3,Bob Johnson,bob@example.com,102,2,2025-06-16,200.75
14,3,Bob Johnson,bob@example.com,103,1,2025-06-17,50.25
15,3,Bob Johnson,bob@example.com,104,3,2025-06-18,300.00
16,3,Bob Johnson,bob@example.com,105,5,2025-06-19,175.80
17,3,Bob Johnson,bob@example.com,106,99,2025-06-20,123.00
18,4,Alice Brown,alice@example.com,101,3,2025-06-15,150.50
19,4,Alice Brown,alice@example.com,102,2,2025-06-16,200.75
20,4,Alice Brown,alice@example.com,103,1,2025-06-17,50.25
21,4,Alice Brown,alice@example.com,104,3,2025-06-18,300.00
22,4,Alice Brown,alice@example.com,105,5,2025-06-19,175.80
23,4,Alice Brown,alice@example.com,106,99,2025-06-20,123.00
24,5,Charlie Davis,charlie@example.com,101,3,2025-06-15,150.50
25,5,Charlie Davis,charlie@example.com,102,2,2025-06-16,200.75
26,5,Charlie Davis,charlie@example.com,103,1,2025-06-17,50.25
27,5,Charlie Davis,charlie@example.com,104,3,2025-06-18,300.00
28,5,Charlie Davis,charlie@example.com,105,5,2025-06-19,175.80
29,5,Charlie Davis,charlie@example.com,106,99,2025-06-20,123.00

In [46]:
# left merge
pd.merge(customers, orders, on="customer_id", how="left")

,customer_id,name,email,order_id,order_date,total_amount
0,1,John Doe,john@example.com,103.0,2025-06-17,50.25
1,2,Jane Smith,jane@example.com,102.0,2025-06-16,200.75
2,3,Bob Johnson,bob@example.com,101.0,2025-06-15,150.50
3,3,Bob Johnson,bob@example.com,104.0,2025-06-18,300.00
4,4,Alice Brown,alice@example.com,NaN,NaN,NaN
5,5,Charlie Davis,charlie@example.com,105.0,2025-06-19,175.80

In [47]:
# right merge
pd.merge(customers, orders, on="customer_id", how="right")

,customer_id,name,email,order_id,order_date,total_amount
0,3,Bob Johnson,bob@example.com,101,2025-06-15,150.50
1,2,Jane Smith,jane@example.com,102,2025-06-16,200.75
2,1,John Doe,john@example.com,103,2025-06-17,50.25
3,3,Bob Johnson,bob@example.com,104,2025-06-18,300.00
4,5,Charlie Davis,charlie@example.com,105,2025-06-19,175.80
5,99,NaN,NaN,106,2025-06-20,123.00

In [49]:
customers_indexed = customers.set_index("customer_id")
customers_indexed

                      name                email
customer_id
1                 John Doe     john@example.com
2               Jane Smith     jane@example.com
3              Bob Johnson      bob@example.com
4              Alice Brown    alice@example.com
5            Charlie Davis  charlie@example.com

In [51]:
customers_indexed["name"]

customer_id
1         John Doe
2       Jane Smith
3      Bob Johnson
4      Alice Brown
5    Charlie Davis
Name: name, dtype: object

In [53]:
orders_indexed = orders.set_index("customer_id")
orders_indexed

             order_id  order_date  total_amount
customer_id
3                 101  2025-06-15        150.50
2                 102  2025-06-16        200.75
1                 103  2025-06-17         50.25
3                 104  2025-06-18        300.00
5                 105  2025-06-19        175.80
99                106  2025-06-20        123.00

In [54]:
# merge on index
pd.merge(customers_indexed, orders_indexed, left_index=True, right_index=True)

,name,email,order_id,order_date,total_amount
customer_id,,,,,
1,John Doe,john@example.com,103,2025-06-17,50.25
2,Jane Smith,jane@example.com,102,2025-06-16,200.75
3,Bob Johnson,bob@example.com,101,2025-06-15,150.50
3,Bob Johnson,bob@example.com,104,2025-06-18,300.00
5,Charlie Davis,charlie@example.com,105,2025-06-19,175.80

In [ ]:
purchases = pd.DataFrame(
    {
        "customer_id": [1, 2, 3, 2, 1],
        "product_id": ["P1", "P2", "P3", "P1", "P3"],
        "quantity": [1, 2, 1, 1, 3],
    }
)

purchases

   customer_id product_id  quantity
0            1         P1         1
1            2         P2         2
2            3         P3         1
3            2         P1         1
4            1         P3         3

In [60]:
products

  product_id product_name     category   price
0         P1       Laptop  Electronics  1200.0
1         P2   Smartphone  Electronics   800.0
2         P3       Tablet  Electronics   500.0
3         P4   Headphones  Accessories   150.0
4         P5   Smartwatch  Accessories   250.0

In [61]:
# merge customers, purchases, and products
pd.merge(customers, purchases, on="customer_id").merge(products, on="product_id")

,customer_id,name,email,product_id,quantity,product_name,category,price
0,1,John Doe,john@example.com,P1,1,Laptop,Electronics,1200.0
1,1,John Doe,john@example.com,P3,3,Tablet,Electronics,500.0
2,2,Jane Smith,jane@example.com,P2,2,Smartphone,Electronics,800.0
3,2,Jane Smith,jane@example.com,P1,1,Laptop,Electronics,1200.0
4,3,Bob Johnson,bob@example.com,P3,1,Tablet,Electronics,500.0

In [62]:
customers

   customer_id           name                email
0            1       John Doe     john@example.com
1            2     Jane Smith     jane@example.com
2            3    Bob Johnson      bob@example.com
3            4    Alice Brown    alice@example.com
4            5  Charlie Davis  charlie@example.com

In [63]:
orders

   order_id  customer_id  order_date  total_amount
0       101            3  2025-06-15        150.50
1       102            2  2025-06-16        200.75
2       103            1  2025-06-17         50.25
3       104            3  2025-06-18        300.00
4       105            5  2025-06-19        175.80
5       106           99  2025-06-20        123.00

In [64]:
orders["name"] = customers["name"]

In [66]:
orders.dropna(inplace=True)
orders

   order_id  customer_id  order_date  total_amount           name
0       101            3  2025-06-15        150.50       John Doe
1       102            2  2025-06-16        200.75     Jane Smith
2       103            1  2025-06-17         50.25    Bob Johnson
3       104            3  2025-06-18        300.00    Alice Brown
4       105            5  2025-06-19        175.80  Charlie Davis

In [68]:
pd.merge(customers, orders, on="customer_id")

,customer_id,name_x,email,order_id,order_date,total_amount,name_y
0,1,John Doe,john@example.com,103,2025-06-17,50.25,Bob Johnson
1,2,Jane Smith,jane@example.com,102,2025-06-16,200.75,Jane Smith
2,3,Bob Johnson,bob@example.com,101,2025-06-15,150.50,John Doe
3,3,Bob Johnson,bob@example.com,104,2025-06-18,300.00,Alice Brown
4,5,Charlie Davis,charlie@example.com,105,2025-06-19,175.80,Charlie Davis

In [69]:
pd.merge(customers, orders, on="customer_id", suffixes=["_customers", "_orders"])

,customer_id,name_customers,email,order_id,order_date,total_amount,name_orders
0,1,John Doe,john@example.com,103,2025-06-17,50.25,Bob Johnson
1,2,Jane Smith,jane@example.com,102,2025-06-16,200.75,Jane Smith
2,3,Bob Johnson,bob@example.com,101,2025-06-15,150.50,John Doe
3,3,Bob Johnson,bob@example.com,104,2025-06-18,300.00,Alice Brown
4,5,Charlie Davis,charlie@example.com,105,2025-06-19,175.80,Charlie Davis

In [70]:
orders.drop(columns="name", inplace=True)

In [71]:
pd.merge(customers, orders, on="customer_id", how="outer", indicator=True)

,customer_id,name,email,order_id,order_date,total_amount,_merge
0,1,John Doe,john@example.com,103.0,2025-06-17,50.25,both
1,2,Jane Smith,jane@example.com,102.0,2025-06-16,200.75,both
2,3,Bob Johnson,bob@example.com,101.0,2025-06-15,150.50,both
3,3,Bob Johnson,bob@example.com,104.0,2025-06-18,300.00,both
4,4,Alice Brown,alice@example.com,NaN,NaN,NaN,left_only
5,5,Charlie Davis,charlie@example.com,105.0,2025-06-19,175.80,both

In [75]:
pd.merge(customers, orders, on="customer_id", validate="one_to_many")

,customer_id,name,email,order_id,order_date,total_amount
0,1,John Doe,john@example.com,103,2025-06-17,50.25
1,2,Jane Smith,jane@example.com,102,2025-06-16,200.75
2,3,Bob Johnson,bob@example.com,101,2025-06-15,150.50
3,3,Bob Johnson,bob@example.com,104,2025-06-18,300.00
4,5,Charlie Davis,charlie@example.com,105,2025-06-19,175.80

### Joining DataFrames

In [ ]:
customers = pd.DataFrame(
    {
        "customer_id": [101, 102, 103, 104, 105],
        "name": [
            "Alice Brown",
            "Bob Charles",
            "Charlie Davis",
            "David Evans",
            "Eve Franklin",
        ],
        "email": [
            "alice@example.com",
            "bob@example.com",
            "charlie@example.com",
            "david@example.com",
            "eve@example.com",
        ],
    }
)

In [78]:
customers.set_index("customer_id", inplace=True)

In [81]:
customers

                      name                email
customer_id
101            Alice Brown    alice@example.com
102            Bob Charles      bob@example.com
103          Charlie Davis  charlie@example.com
104            David Evans    david@example.com
105           Eve Franklin      eve@example.com

In [ ]:
orders = pd.DataFrame(
    {
        "order_id": [1001, 1002, 1003, 1004, 1005],
        "customer_id": [101, 103, 102, 105, 101],
        "order_date": [
            "2023-06-01",
            "2023-06-02",
            "2023-06-03",
            "2023-06-04",
            "2023-06-05",
        ],
        "total_amount": [150.50, 200.75, 50.25, 300.00, 175.80],
    }
).set_index("customer_id")

In [80]:
orders

             order_id  order_date  total_amount
customer_id
101              1001  2023-06-01        150.50
103              1002  2023-06-02        200.75
102              1003  2023-06-03         50.25
105              1004  2023-06-04        300.00
101              1005  2023-06-05        175.80

In [ ]:
supports_tickets = pd.DataFrame(
    {
        "ticket_id": [5001, 5002, 5003, 5004],
        "customer_id": [102, 104, 101, 103],
        "issue": [
            "Payment failed",
            "Item not received",
            "Wrong item sent",
            "Refund request",
        ],
        "status": ["Resolved", "In Progress", "Resolved", "Pending"],
    }
).set_index("customer_id")

In [83]:
supports_tickets

             ticket_id              issue       status
customer_id
102               5001     Payment failed     Resolved
104               5002  Item not received  In Progress
101               5003    Wrong item sent     Resolved
103               5004     Refund request      Pending

In [84]:
pd.merge(customers, orders, left_index=True, right_index=True, how="outer")

,name,email,order_id,order_date,total_amount
customer_id,,,,,
101,Alice Brown,alice@example.com,1001.0,2023-06-01,150.50
101,Alice Brown,alice@example.com,1005.0,2023-06-05,175.80
102,Bob Charles,bob@example.com,1003.0,2023-06-03,50.25
103,Charlie Davis,charlie@example.com,1002.0,2023-06-02,200.75
104,David Evans,david@example.com,NaN,NaN,NaN
105,Eve Franklin,eve@example.com,1004.0,2023-06-04,300.00

In [87]:
customers.join(orders, how="outer")

,name,email,order_id,order_date,total_amount
customer_id,,,,,
101,Alice Brown,alice@example.com,1001.0,2023-06-01,150.50
101,Alice Brown,alice@example.com,1005.0,2023-06-05,175.80
102,Bob Charles,bob@example.com,1003.0,2023-06-03,50.25
103,Charlie Davis,charlie@example.com,1002.0,2023-06-02,200.75
104,David Evans,david@example.com,NaN,NaN,NaN
105,Eve Franklin,eve@example.com,1004.0,2023-06-04,300.00

In [88]:
# inner join
customers.join(orders, how="inner")

,name,email,order_id,order_date,total_amount
customer_id,,,,,
101,Alice Brown,alice@example.com,1001,2023-06-01,150.50
101,Alice Brown,alice@example.com,1005,2023-06-05,175.80
102,Bob Charles,bob@example.com,1003,2023-06-03,50.25
103,Charlie Davis,charlie@example.com,1002,2023-06-02,200.75
105,Eve Franklin,eve@example.com,1004,2023-06-04,300.00

In [89]:
# left join
customers.join(orders, how="left")

,name,email,order_id,order_date,total_amount
customer_id,,,,,
101,Alice Brown,alice@example.com,1001.0,2023-06-01,150.50
101,Alice Brown,alice@example.com,1005.0,2023-06-05,175.80
102,Bob Charles,bob@example.com,1003.0,2023-06-03,50.25
103,Charlie Davis,charlie@example.com,1002.0,2023-06-02,200.75
104,David Evans,david@example.com,NaN,NaN,NaN
105,Eve Franklin,eve@example.com,1004.0,2023-06-04,300.00

In [90]:
# right join
customers.join(orders, how="right")

,name,email,order_id,order_date,total_amount
customer_id,,,,,
101,Alice Brown,alice@example.com,1001,2023-06-01,150.50
103,Charlie Davis,charlie@example.com,1002,2023-06-02,200.75
102,Bob Charles,bob@example.com,1003,2023-06-03,50.25
105,Eve Franklin,eve@example.com,1004,2023-06-04,300.00
101,Alice Brown,alice@example.com,1005,2023-06-05,175.80

In [93]:
customers.join([orders, supports_tickets], how="outer")

,name,email,order_id,order_date,total_amount,ticket_id,issue,status
customer_id,,,,,,,,
101,Alice Brown,alice@example.com,1001.0,2023-06-01,150.50,5003.0,Wrong item sent,Resolved
101,Alice Brown,alice@example.com,1005.0,2023-06-05,175.80,5003.0,Wrong item sent,Resolved
102,Bob Charles,bob@example.com,1003.0,2023-06-03,50.25,5001.0,Payment failed,Resolved
103,Charlie Davis,charlie@example.com,1002.0,2023-06-02,200.75,5004.0,Refund request,Pending
104,David Evans,david@example.com,NaN,NaN,NaN,5002.0,Item not received,In Progress
105,Eve Franklin,eve@example.com,1004.0,2023-06-04,300.00,NaN,NaN,NaN

In [95]:
customers["rating"] = [4.5, 3.8, 4.2, 5.0, 4.7]
customers

                      name                email  rating
customer_id
101            Alice Brown    alice@example.com     4.5
102            Bob Charles      bob@example.com     3.8
103          Charlie Davis  charlie@example.com     4.2
104            David Evans    david@example.com     5.0
105           Eve Franklin      eve@example.com     4.7

In [96]:
orders["rating"] = [4.0, 4.5, 3.5, 5.0, 4.8]
orders

             order_id  order_date  total_amount  rating
customer_id
101              1001  2023-06-01        150.50     4.0
103              1002  2023-06-02        200.75     4.5
102              1003  2023-06-03         50.25     3.5
105              1004  2023-06-04        300.00     5.0
101              1005  2023-06-05        175.80     4.8

In [99]:
customers.join(orders, lsuffix="_customer", rsuffix="_order", how="inner")

,name,email,rating_customer,order_id,order_date,total_amount,rating_order
customer_id,,,,,,,
101,Alice Brown,alice@example.com,4.5,1001,2023-06-01,150.50,4.0
101,Alice Brown,alice@example.com,4.5,1005,2023-06-05,175.80,4.8
102,Bob Charles,bob@example.com,3.8,1003,2023-06-03,50.25,3.5
103,Charlie Davis,charlie@example.com,4.2,1002,2023-06-02,200.75,4.5
105,Eve Franklin,eve@example.com,4.7,1004,2023-06-04,300.00,5.0

### Best Practices and Common pitfalls

In [ ]:
# check data types
customers.reset_index()["customer_id"].dtype

dtype('int64')

In [105]:
orders.reset_index()["customer_id"].dtype

dtype('int64')

In [ ]:
# convert if necessary
orders.index.astype("u8")

Index([101, 103, 102, 105, 101], dtype='uint64', name='customer_id')

In [113]:
customers.merge(orders, on="customer_id", how="inner")

,name,email,rating_x,order_id,order_date,total_amount,rating_y
customer_id,,,,,,,
101,Alice Brown,alice@example.com,4.5,1001,2023-06-01,150.50,4.0
101,Alice Brown,alice@example.com,4.5,1005,2023-06-05,175.80,4.8
102,Bob Charles,bob@example.com,3.8,1003,2023-06-03,50.25,3.5
103,Charlie Davis,charlie@example.com,4.2,1002,2023-06-02,200.75,4.5
105,Eve Franklin,eve@example.com,4.7,1004,2023-06-04,300.00,5.0

In [114]:
print(
    f"Shape before merge: (customers data frame: {customers.shape}), (orders data frame: {orders.shape})"
)

Shape before merge: (customers data frame: (5, 3)), (orders data frame: (5, 4))

In [ ]:
print(
    f"Shape after merge: {customers.merge(orders, on='customer_id', how='inner').shape}"
)

Shape after merge: (5, 7)

In [ ]:
pd.merge(
    customers, orders, on="customer_id", how="outer", indicator=True
)._merge.value_counts()

_merge
both          5
left_only     1
right_only    0
Name: count, dtype: int64