# Coding Practice Session 13
## Grouping and Aggregating Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(25)

In [3]:
dates = pd.date_range(start="2024-01-01", end="2025-12-31", freq="D")
products = ["Laptop", "Smartphone", "Tablet", "Headphones"]
regions = ["North", "South", "East", "West"]

In [4]:
num_entries = 1000

In [ ]:
df = pd.DataFrame(
    {
        "Date": np.random.choice(dates, num_entries),
        "Product": np.random.choice(products, num_entries),
        "Region": np.random.choice(regions, num_entries),
        "Sales": np.random.randint(100, 1500, num_entries),
        "Units": np.random.randint(1, 10, num_entries),
    }
)

In [6]:
df

          Date     Product Region  Sales  Units
0   2024-05-12      Laptop   East   1285      8
1   2024-11-14  Smartphone  South   1411      8
2   2025-04-19      Tablet   East   1429      2
3   2024-05-23  Smartphone  North    962      2
4   2024-11-13      Tablet   West    775      4
..         ...         ...    ...    ...    ...
995 2025-11-19  Headphones  North   1140      1
996 2025-07-15      Tablet   West    599      3
997 2024-11-04      Laptop   East    827      7
998 2024-07-03      Laptop   East    432      4
999 2025-12-20      Laptop   East    854      2

[1000 rows x 5 columns]

In [7]:
df["Revenue"] = df["Sales"] * df["Units"]

In [8]:
df

          Date     Product Region  Sales  Units  Revenue
0   2024-05-12      Laptop   East   1285      8    10280
1   2024-11-14  Smartphone  South   1411      8    11288
2   2025-04-19      Tablet   East   1429      2     2858
3   2024-05-23  Smartphone  North    962      2     1924
4   2024-11-13      Tablet   West    775      4     3100
..         ...         ...    ...    ...    ...      ...
995 2025-11-19  Headphones  North   1140      1     1140
996 2025-07-15      Tablet   West    599      3     1797
997 2024-11-04      Laptop   East    827      7     5789
998 2024-07-03      Laptop   East    432      4     1728
999 2025-12-20      Laptop   East    854      2     1708

[1000 rows x 6 columns]

In [9]:
df = df.sort_values("Date")

In [10]:
df.reset_index(drop=True, inplace=True)

In [11]:
df

          Date     Product Region  Sales  Units  Revenue
0   2024-01-01  Headphones  North    713      9     6417
1   2024-01-01  Smartphone  South    866      6     5196
2   2024-01-02      Tablet  North   1038      8     8304
3   2024-01-02      Tablet  North   1305      5     6525
4   2024-01-03  Smartphone   East    523      5     2615
..         ...         ...    ...    ...    ...      ...
995 2025-12-28  Headphones  North   1224      2     2448
996 2025-12-29  Smartphone  North    448      2      896
997 2025-12-29      Tablet  South    336      7     2352
998 2025-12-30      Tablet  North    621      7     4347
999 2025-12-31  Smartphone  South    208      4      832

[1000 rows x 6 columns]

In [12]:
df["Product"] = df["Product"].astype("category")

In [13]:
df["Product"].value_counts()

Product
Laptop        259
Headphones    257
Tablet        249
Smartphone    235
Name: count, dtype: int64

### Basic Grouping with `groupby()`

In [14]:
df.groupby("Product", observed=True)["Revenue"].sum()

Product
Headphones     958286
Laptop        1033886
Smartphone     882313
Tablet         963400
Name: Revenue, dtype: int64

In [15]:
df.groupby("Product", observed=True)["Revenue"].sum().sort_values(ascending=False)

Product
Laptop        1033886
Tablet         963400
Headphones     958286
Smartphone     882313
Name: Revenue, dtype: int64

In [ ]:
df.groupby("Product", observed=True).agg(
    {"Revenue": "sum", "Units": "mean", "Sales": "mean"}
)

            Revenue     Units       Sales
Product
Headphones   958286  4.782101  778.381323
Laptop      1033886  5.027027  784.644788
Smartphone   882313  4.889362  780.148936
Tablet       963400  4.895582  794.261044

In [21]:
df.groupby(["Region", "Product"], observed=True)["Revenue"].sum()

Region  Product
East    Headphones    262419
        Laptop        258383
        Smartphone    226576
        Tablet        232959
North   Headphones    264924
        Laptop        269503
        Smartphone    261388
        Tablet        208650
South   Headphones    196608
        Laptop        226668
        Smartphone    213503
        Tablet        298257
West    Headphones    234335
        Laptop        279332
        Smartphone    180846
        Tablet        223534
Name: Revenue, dtype: int64

In [22]:
df.groupby(["Region", "Product"], observed=True)["Revenue"].sum().unstack()

Product  Headphones  Laptop  Smartphone  Tablet
Region
East         262419  258383      226576  232959
North        264924  269503      261388  208650
South        196608  226668      213503  298257
West         234335  279332      180846  223534

In [ ]:
df.groupby(["Region", "Product"], observed=True)["Revenue"].sum().unstack(
    level="Region"
)

Region        East   North   South    West
Product
Headphones  262419  264924  196608  234335
Laptop      258383  269503  226668  279332
Smartphone  226576  261388  213503  180846
Tablet      232959  208650  298257  223534

In [25]:
def get_quarter(date):
    return f"Q{date.quarter}"

In [28]:
df.groupby(df["Date"].apply(get_quarter))["Revenue"].sum().sort_values(ascending=False)

Date
Q1    1017268
Q3     974240
Q2     949444
Q4     896933
Name: Revenue, dtype: int64

In [29]:
df.groupby(df["Date"].dt.to_period("M"))["Revenue"].sum()

Date
2024-01    185023
2024-02    169187
2024-03    140064
2024-04    120656
2024-05    183941
2024-06    132474
2024-07    163530
2024-08    183507
2024-09    167244
2024-10    130568
2024-11    179595
2024-12    143637
2025-01    203575
2025-02    125490
2025-03    193929
2025-04    181071
2025-05    173034
2025-06    158268
2025-07    168438
2025-08    180347
2025-09    111174
2025-10    138363
2025-11    142374
2025-12    162396
Freq: M, Name: Revenue, dtype: int64

In [30]:
df.groupby(df["Date"].dt.to_period("Q"))["Revenue"].sum()

Date
2024Q1    494274
2024Q2    437071
2024Q3    514281
2024Q4    453800
2025Q1    522994
2025Q2    512373
2025Q3    459959
2025Q4    443133
Freq: Q-DEC, Name: Revenue, dtype: int64

In [ ]:
df.groupby([df["Date"].apply(get_quarter), "Product"], observed=True)[
    "Revenue"
].sum().unstack(level="Product")

Product  Headphones  Laptop  Smartphone  Tablet
Date
Q1           242842  219660      284904  269862
Q2           198429  273864      200477  276674
Q3           289559  296361      190901  197419
Q4           227456  244001      206031  219445

### Aggregation Methods

In [36]:
df

          Date     Product Region  Sales  Units  Revenue
0   2024-01-01  Headphones  North    713      9     6417
1   2024-01-01  Smartphone  South    866      6     5196
2   2024-01-02      Tablet  North   1038      8     8304
3   2024-01-02      Tablet  North   1305      5     6525
4   2024-01-03  Smartphone   East    523      5     2615
..         ...         ...    ...    ...    ...      ...
995 2025-12-28  Headphones  North   1224      2     2448
996 2025-12-29  Smartphone  North    448      2      896
997 2025-12-29      Tablet  South    336      7     2352
998 2025-12-30      Tablet  North    621      7     4347
999 2025-12-31  Smartphone  South    208      4      832

[1000 rows x 6 columns]

In [33]:
grouped = df.groupby("Product", observed=True)

In [34]:
grouped.agg({"Revenue": ["count", "sum", "mean", "median"]})

           Revenue
             count      sum         mean  median
Product
Headphones     257   958286  3728.739300  2734.0
Laptop         259  1033886  3991.837838  3241.0
Smartphone     235   882313  3754.523404  2830.0
Tablet         249   963400  3869.076305  3033.0

In [37]:
grouped.agg({
    "Revenue": ["sum", "mean"],
    "Units": ["count", "max", "min"]
})

            Revenue              Units
                sum         mean count max min
Product
Headphones   958286  3728.739300   257   9   1
Laptop      1033886  3991.837838   259   9   1
Smartphone   882313  3754.523404   235   9   1
Tablet       963400  3869.076305   249   9   1

In [38]:
def sales_range(column):
    return column.max() - column.min()

In [41]:
grouped.agg({
    "Revenue": ["sum"],
    "Sales": ["max", sales_range],
})

            Revenue Sales
                sum   max sales_range
Product
Headphones   958286  1475        1368
Laptop      1033886  1490        1371
Smartphone   882313  1477        1377
Tablet       963400  1498        1393

In [45]:
grouped["Revenue"].agg([
    ("Total", "sum"),
    ("Average", "mean"),
    ("Range", lambda col: col.max() - col.min())
]).round(2)

              Total  Average  Range
Product
Headphones   958286  3728.74  13158
Laptop      1033886  3991.84  12316
Smartphone   882313  3754.52  12399
Tablet       963400  3869.08  13267

In [46]:
df.groupby("Region").agg({
    "Revenue": ["sum", "mean", "median"],
    "Units": ["sum", "mean"],
    "Sales": ["min", "max"],
})

        Revenue                      Units           Sales
            sum         mean  median   sum      mean   min   max
Region
East     980337  3874.849802  3080.0  1267  5.007905   107  1496
North   1004465  3734.070632  2877.0  1316  4.892193   100  1487
South    935036  3863.785124  2789.5  1184  4.892562   101  1498
West     918047  3890.029661  3077.0  1132  4.796610   117  1487

In [48]:
grouped.agg(
    Total_Revenue=("Revenue", "sum"),
    Average_Price=("Sales", "mean"),
    Total_Units=("Units", "sum")
)

            Total_Revenue  Average_Price  Total_Units
Product
Headphones         958286     778.381323         1229
Laptop            1033886     784.644788         1302
Smartphone         882313     780.148936         1149
Tablet             963400     794.261044         1219

### Advanced Grouping Techniques

In [49]:
grouped

In [57]:
grouped.get_group("Laptop")

          Date Product Region  Sales  Units  Revenue
5   2024-01-03  Laptop   East    121      6      726
7   2024-01-05  Laptop  North    623      9     5607
15  2024-01-11  Laptop   West    895      8     7160
18  2024-01-12  Laptop  South    434      8     3472
20  2024-01-14  Laptop  South    376      3     1128
..         ...     ...    ...    ...    ...      ...
982 2025-12-20  Laptop   East    854      2     1708
988 2025-12-22  Laptop  North    346      4     1384
989 2025-12-23  Laptop  North   1307      4     5228
990 2025-12-24  Laptop  North    339      9     3051
992 2025-12-25  Laptop   East   1138      5     5690

[259 rows x 6 columns]

In [60]:
grouped.get_group("Laptop").agg({
    "Revenue": ["sum", "mean"],
    "Units": "sum",
    "Sales": ["min", "max", "mean"]
})

           Revenue   Units        Sales
sum   1.033886e+06  1302.0          NaN
mean  3.991838e+03     NaN   784.644788
min            NaN     NaN   119.000000
max            NaN     NaN  1490.000000

In [61]:
df["Product"].value_counts()

Product
Laptop        259
Headphones    257
Tablet        249
Smartphone    235
Name: count, dtype: int64

In [63]:
high_number_groups = grouped.filter(lambda group: len(group)> 250)
high_number_groups

          Date     Product Region  Sales  Units  Revenue
0   2024-01-01  Headphones  North    713      9     6417
5   2024-01-03      Laptop   East    121      6      726
6   2024-01-04  Headphones  North    187      9     1683
7   2024-01-05      Laptop  North    623      9     5607
13  2024-01-09  Headphones   West   1193      5     5965
..         ...         ...    ...    ...    ...      ...
990 2025-12-24      Laptop  North    339      9     3051
991 2025-12-24  Headphones   East    318      3      954
992 2025-12-25      Laptop   East   1138      5     5690
993 2025-12-26  Headphones   West    903      6     5418
995 2025-12-28  Headphones  North   1224      2     2448

[516 rows x 6 columns]

In [64]:
high_number_groups["Product"].unique()

['Headphones', 'Laptop']
Categories (4, object): ['Headphones', 'Laptop', 'Smartphone', 'Tablet']

In [68]:
high_number_groups.groupby("Product", observed=True).agg({
    "Revenue": ["sum", "mean"],
    "Units": "sum"
}).dropna()

            Revenue              Units
                sum         mean   sum
Product
Headphones   958286  3728.739300  1229
Laptop      1033886  3991.837838  1302

### Transformation and Applying Functions to Groups