# Coding Practice Session 14
## Reshaping and Pivot Tables

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(25)

In [3]:
products = ["Laptop", "Smartphone", "Tablet", "Smartwatch"]
regions = ["North", "South", "East", "West"]
dates = pd.date_range(start="2024-01-01", end="2024-12-31", freq="ME")

In [ ]:
data = []
for date in dates:
    for product in products:
        for region in regions:
            if product == "Laptop":
                sales = np.random.randint(800, 2000)
                units = np.random.randint(5, 20)
            elif product == "Smartphone":
                sales = np.random.randint(500, 1200)
                units = np.random.randint(10, 30)
            elif product == "Tablet":
                sales = np.random.randint(300, 800)
                units = np.random.randint(5, 15)
            else:  # Smartwatch
                sales = np.random.randint(200, 500)
                units = np.random.randint(8, 25)

            if date.month in [11, 12]:  # Holiday season
                sales = int(sales * 1.2)
                units = int(units * 1.2)

            data.append([date, product, region, sales, units])

In [5]:
data[0]

[Timestamp('2024-01-31 00:00:00'), 'Laptop', 'North', 1956, 19]

In [6]:
df = pd.DataFrame(data, columns=["Date", "Product", "Region", "Sales", "Units"])

In [7]:
df["Average Price"] = (df["Sales"] / df["Units"]).round(decimals=2)

In [8]:
df.head(8)

        Date     Product Region  Sales  Units  Average Price
0 2024-01-31      Laptop  North   1956     19         102.95
1 2024-01-31      Laptop  South   1274     18          70.78
2 2024-01-31      Laptop   East   1686     12         140.50
3 2024-01-31      Laptop   West   1740      7         248.57
4 2024-01-31  Smartphone  North    636     14          45.43
5 2024-01-31  Smartphone  South    753     15          50.20
6 2024-01-31  Smartphone   East   1141     17          67.12
7 2024-01-31  Smartphone   West    588     13          45.23

In [9]:
df.tail(8)

          Date     Product Region  Sales  Units  Average Price
184 2024-12-31      Tablet  North    908     13          69.85
185 2024-12-31      Tablet  South    777     13          59.77
186 2024-12-31      Tablet   East    704     10          70.40
187 2024-12-31      Tablet   West    638     16          39.88
188 2024-12-31  Smartwatch  North    308      9          34.22
189 2024-12-31  Smartwatch  South    266     20          13.30
190 2024-12-31  Smartwatch   East    510     14          36.43
191 2024-12-31  Smartwatch   West    268     15          17.87

In [10]:
df.count()

Date             192
Product          192
Region           192
Sales            192
Units            192
Average Price    192
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           192 non-null    datetime64[ns]
 1   Product        192 non-null    object
 2   Region         192 non-null    object
 3   Sales          192 non-null    int64
 4   Units          192 non-null    int64
 5   Average Price  192 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 9.1+ KB

### Pivoting Data

In [ ]:
data = {
    "variable": ["A"] * 3 + ["B"] * 3 + ["C"] * 3 + ["D"] * 3,
    "value": range(12),
    "date": pd.to_datetime(["2025-06-12", "2025-08-04", "2024-11-23"] * 4),
}

df_example = pd.DataFrame(data)
df_example

   variable  value       date
0         A      0 2025-06-12
1         A      1 2025-08-04
2         A      2 2024-11-23
3         B      3 2025-06-12
4         B      4 2025-08-04
5         B      5 2024-11-23
6         C      6 2025-06-12
7         C      7 2025-08-04
8         C      8 2024-11-23
9         D      9 2025-06-12
10        D     10 2025-08-04
11        D     11 2024-11-23

In [13]:
# using pivot()
df_example.pivot(index="date", columns="variable", values="value")

variable    A  B  C   D
date
2024-11-23  2  5  8  11
2025-06-12  0  3  6   9
2025-08-04  1  4  7  10

In [14]:
df

          Date     Product Region  Sales  Units  Average Price
0   2024-01-31      Laptop  North   1956     19         102.95
1   2024-01-31      Laptop  South   1274     18          70.78
2   2024-01-31      Laptop   East   1686     12         140.50
3   2024-01-31      Laptop   West   1740      7         248.57
4   2024-01-31  Smartphone  North    636     14          45.43
..         ...         ...    ...    ...    ...            ...
187 2024-12-31      Tablet   West    638     16          39.88
188 2024-12-31  Smartwatch  North    308      9          34.22
189 2024-12-31  Smartwatch  South    266     20          13.30
190 2024-12-31  Smartwatch   East    510     14          36.43
191 2024-12-31  Smartwatch   West    268     15          17.87

[192 rows x 6 columns]

**Note**: `pivot` is used when each index and column pair is unique.

In [15]:
# using pivot_table()
df.pivot_table(index="Product", columns="Region", values="Sales", aggfunc="sum")

Region       East  North  South   West
Product
Laptop      18910  19005  15976  15203
Smartphone  10785  10785  10962  10411
Smartwatch   4415   3945   3857   4182
Tablet       6192   7034   7002   6455

In [ ]:
df.pivot_table(
    index=["Region", "Product"],
    columns="Date",
    values=["Sales", "Units"],
    aggfunc={"Sales": "sum", "Units": "mean"},
    fill_value=0,
)

                       Sales                                              \
Date              2024-01-31 2024-02-29 2024-03-31 2024-04-30 2024-05-31
Region Product
East   Laptop           1686       1797       1870        852       1632
       Smartphone       1141        522        908       1034        907
       Smartwatch        337        214        489        308        440
       Tablet            715        314        511        315        548
North  Laptop           1956       1930       1683       1184       1299
       Smartphone        636       1178       1014       1169        525
       Smartwatch        344        251        383        430        282
       Tablet            640        471        460        399        664
South  Laptop           1274       1404       1725       1975       1642
       Smartphone        753        761        800        859        891
       Smartwatch        309        390        271        331        422
       Tablet            557        511        740        730        594
West   Laptop           1740       1035        862       1142        889
       Smartphone        588        767        951       1140        641
       Smartwatch        338        495        417        208        464
       Tablet            347        721        439        493        649

                                                                          ...  \
Date              2024-06-30 2024-07-31 2024-08-31 2024-09-30 2024-10-31  ...
Region Product                                                            ...
East   Laptop           1946       1067       1108       1293       1910  ...
       Smartphone        946       1097        616        952       1030  ...
       Smartwatch        208        269        314        444        484  ...
       Tablet            367        559        305        715        543  ...
North  Laptop           1606       1027       1759       1186       1205  ...
       Smartphone        607        947        889        651        525  ...
       Smartwatch        285        251        443        266        278  ...
       Tablet            657        630        782        504        437  ...
South  Laptop           1757        893       1226       1020       1012  ...
       Smartphone       1061       1172       1026        903        757  ...
       Smartwatch        466        385        202        231        310  ...
       Tablet            701        477        506        383        455  ...
West   Laptop           1063       1334       1161       1328       1374  ...
       Smartphone        670       1019       1102        782        983  ...
       Smartwatch        417        216        259        393        254  ...
       Tablet            691        365        344        501        341  ...

                       Units                                              \
Date              2024-03-31 2024-04-30 2024-05-31 2024-06-30 2024-07-31
Region Product
East   Laptop           10.0        9.0       18.0        9.0       14.0
       Smartphone       19.0       10.0       28.0       13.0       11.0
       Smartwatch       18.0       22.0       11.0       19.0       20.0
       Tablet            8.0        9.0       11.0        7.0       12.0
North  Laptop           10.0        5.0        9.0       11.0       15.0
       Smartphone       22.0       10.0       15.0       16.0       24.0
       Smartwatch       20.0        9.0       15.0       20.0       14.0
       Tablet           10.0        5.0       10.0        9.0       12.0
South  Laptop           18.0        5.0       12.0        5.0       15.0
       Smartphone       23.0       28.0       26.0       19.0       12.0
       Smartwatch       22.0       20.0       14.0       10.0       19.0
       Tablet            9.0        5.0       14.0        5.0        6.0
West   Laptop            8.0       12.0       12.0       11.0        5.0
       Smartphone       25.0       15.0       10.0       17.0       28.0
       Smartwatch       16.0       14.0       24.0       21.0       11.0
       Tablet           10.0        7.0        7.0        7.0        7.0


Date              2024-08-31 2024-09-30 2024-10-31 2024-11-30 2024-12-31
Region Product
East   Laptop            6.0       14.0        7.0       10.0        9.0
       Smartphone       29.0       14.0       27.0       13.0       15.0
       Smartwatch       13.0       22.0       24.0       28.0       14.0
       Tablet           14.0        6.0        6.0       16.0       10.0
North  Laptop           10.0       14.0       15.0       22.0       14.0
       Smartphone       21.0       21.0       14.0       21.0       30.0
       Smartwatch       16.0       18.0       19.0       10.0        9.0
       Tablet            5.0       10.0        6.0        9.0       13.0
South  Laptop           10.0       19.0       16.0       15.0        7.0
       Smartphone       12.0       24.0       19.0       20.0       33.0
       Smartwatch       21.0       24.0       11.0       22.0       20.0
       Tablet           10.0       11.0       14.0       10.0       13.0
West   Laptop           10.0       14.0        8.0       19.0       15.0
       Smartphone       25.0       24.0       20.0       15.0       12.0
       Smartwatch       13.0       18.0       13.0       25.0       15.0
       Tablet           11.0       11.0       11.0       15.0       16.0

[16 rows x 24 columns]

In [ ]:
df.pivot_table(
    index="Product",
    values=["Sales", "Units", "Average Price"],
    aggfunc={
        "Sales": ["mean", "sum"],
        "Units": ["mean", "sum"],
        "Average Price": ["mean", "min", "max"],
    },
)

           Average Price                           Sales             Units  \
                     max        mean    min         mean    sum       mean
Product
Laptop            395.00  147.191667  53.68  1439.458333  69094  11.583333
Smartphone        116.90   52.601042  20.08   894.645833  42943  18.916667
Smartwatch         47.78   21.453125   9.62   341.645833  16399  17.583333
Tablet            156.40   65.318333  21.79   555.895833  26683   9.583333


            sum
Product
Laptop      556
Smartphone  908
Smartwatch  844
Tablet      460

### Stacking and Unstacking

In [ ]:
sales_pivot = df.pivot_table(
    index="Product", columns="Region", values="Sales", aggfunc="sum"
)
sales_pivot

Region       East  North  South   West
Product
Laptop      18910  19005  15976  15203
Smartphone  10785  10785  10962  10411
Smartwatch   4415   3945   3857   4182
Tablet       6192   7034   7002   6455

In [19]:
stacked_sales = sales_pivot.stack()
stacked_sales

Product     Region
Laptop      East      18910
            North     19005
            South     15976
            West      15203
Smartphone  East      10785
            North     10785
            South     10962
            West      10411
Smartwatch  East       4415
            North      3945
            South      3857
            West       4182
Tablet      East       6192
            North      7034
            South      7002
            West       6455
dtype: int64

In [20]:
type(stacked_sales)

pandas.core.series.Series

In [21]:
type(stacked_sales.index)

pandas.core.indexes.multi.MultiIndex

In [ ]:
complex_pivot = df.pivot_table(
    index="Product", values=["Sales", "Units"], columns=["Region", "Date"]
)

In [32]:
complex_pivot.head()

                Sales                                                         \
Region           East
Date       2024-01-31 2024-02-29 2024-03-31 2024-04-30 2024-05-31 2024-06-30
Product
Laptop         1686.0     1797.0     1870.0      852.0     1632.0     1946.0
Smartphone     1141.0      522.0      908.0     1034.0      907.0      946.0
Smartwatch      337.0      214.0      489.0      308.0      440.0      208.0
Tablet          715.0      314.0      511.0      315.0      548.0      367.0

                                                        ...      Units  \
Region                                                  ...       West
Date       2024-07-31 2024-08-31 2024-09-30 2024-10-31  ... 2024-03-31
Product                                                 ...
Laptop         1067.0     1108.0     1293.0     1910.0  ...        8.0
Smartphone     1097.0      616.0      952.0     1030.0  ...       25.0
Smartwatch      269.0      314.0      444.0      484.0  ...       16.0
Tablet          559.0      305.0      715.0      543.0  ...       10.0

                                                                              \
Region
Date       2024-04-30 2024-05-31 2024-06-30 2024-07-31 2024-08-31 2024-09-30
Product
Laptop           12.0       12.0       11.0        5.0       10.0       14.0
Smartphone       15.0       10.0       17.0       28.0       25.0       24.0
Smartwatch       14.0       24.0       21.0       11.0       13.0       18.0
Tablet            7.0        7.0        7.0        7.0       11.0       11.0


Region
Date       2024-10-31 2024-11-30 2024-12-31
Product
Laptop            8.0       19.0       15.0
Smartphone       20.0       15.0       12.0
Smartwatch       13.0       25.0       15.0
Tablet           11.0       15.0       16.0

[4 rows x 96 columns]

In [23]:
stacked_complex = complex_pivot.stack(level=0, future_stack=True)
stacked_complex

Region                 East                                              \
Date             2024-01-31 2024-02-29 2024-03-31 2024-04-30 2024-05-31
Product
Laptop     Sales     1686.0     1797.0     1870.0      852.0     1632.0
           Units       12.0       13.0       10.0        9.0       18.0
Smartphone Sales     1141.0      522.0      908.0     1034.0      907.0
           Units       17.0       26.0       19.0       10.0       28.0
Smartwatch Sales      337.0      214.0      489.0      308.0      440.0
           Units        8.0       20.0       18.0       22.0       11.0
Tablet     Sales      715.0      314.0      511.0      315.0      548.0
           Units        5.0        8.0        8.0        9.0       11.0

Region                                                                   ...  \
Date             2024-06-30 2024-07-31 2024-08-31 2024-09-30 2024-10-31  ...
Product                                                                  ...
Laptop     Sales     1946.0     1067.0     1108.0     1293.0     1910.0  ...
           Units        9.0       14.0        6.0       14.0        7.0  ...
Smartphone Sales      946.0     1097.0      616.0      952.0     1030.0  ...
           Units       13.0       11.0       29.0       14.0       27.0  ...
Smartwatch Sales      208.0      269.0      314.0      444.0      484.0  ...
           Units       19.0       20.0       13.0       22.0       24.0  ...
Tablet     Sales      367.0      559.0      305.0      715.0      543.0  ...
           Units        7.0       12.0       14.0        6.0        6.0  ...

Region                 West                                              \
Date             2024-03-31 2024-04-30 2024-05-31 2024-06-30 2024-07-31
Product
Laptop     Sales      862.0     1142.0      889.0     1063.0     1334.0
           Units        8.0       12.0       12.0       11.0        5.0
Smartphone Sales      951.0     1140.0      641.0      670.0     1019.0
           Units       25.0       15.0       10.0       17.0       28.0
Smartwatch Sales      417.0      208.0      464.0      417.0      216.0
           Units       16.0       14.0       24.0       21.0       11.0
Tablet     Sales      439.0      493.0      649.0      691.0      365.0
           Units       10.0        7.0        7.0        7.0        7.0

Region
Date             2024-08-31 2024-09-30 2024-10-31 2024-11-30 2024-12-31
Product
Laptop     Sales     1161.0     1328.0     1374.0     1543.0     1732.0
           Units       10.0       14.0        8.0       19.0       15.0
Smartphone Sales     1102.0      782.0      983.0      991.0      777.0
           Units       25.0       24.0       20.0       15.0       12.0
Smartwatch Sales      259.0      393.0      254.0      453.0      268.0
           Units       13.0       18.0       13.0       25.0       15.0
Tablet     Sales      344.0      501.0      341.0      926.0      638.0
           Units       11.0       11.0       11.0       15.0       16.0

[8 rows x 48 columns]

In [24]:
stacked_complex.index

MultiIndex([(    'Laptop', 'Sales'),
            (    'Laptop', 'Units'),
            ('Smartphone', 'Sales'),
            ('Smartphone', 'Units'),
            ('Smartwatch', 'Sales'),
            ('Smartwatch', 'Units'),
            (    'Tablet', 'Sales'),
            (    'Tablet', 'Units')],
           names=['Product', None])

In [25]:
complex_pivot.stack(level=["Date", "Region"], future_stack=True)

                            Sales  Units
Product Date       Region
Laptop  2024-01-31 East    1686.0   12.0
        2024-02-29 East    1797.0   13.0
        2024-03-31 East    1870.0   10.0
        2024-04-30 East     852.0    9.0
        2024-05-31 East    1632.0   18.0
...                           ...    ...
Tablet  2024-08-31 West     344.0   11.0
        2024-09-30 West     501.0   11.0
        2024-10-31 West     341.0   11.0
        2024-11-30 West     926.0   15.0
        2024-12-31 West     638.0   16.0

[192 rows x 2 columns]

In [26]:
stacked_sales

Product     Region
Laptop      East      18910
            North     19005
            South     15976
            West      15203
Smartphone  East      10785
            North     10785
            South     10962
            West      10411
Smartwatch  East       4415
            North      3945
            South      3857
            West       4182
Tablet      East       6192
            North      7034
            South      7002
            West       6455
dtype: int64

In [27]:
stacked_sales.unstack()

Region       East  North  South   West
Product
Laptop      18910  19005  15976  15203
Smartphone  10785  10785  10962  10411
Smartwatch   4415   3945   3857   4182
Tablet       6192   7034   7002   6455

In [28]:
multi_index_df = df.set_index(["Date", "Product", "Region"])
multi_index_df

                              Sales  Units  Average Price
Date       Product    Region
2024-01-31 Laptop     North    1956     19         102.95
                      South    1274     18          70.78
                      East     1686     12         140.50
                      West     1740      7         248.57
           Smartphone North     636     14          45.43
...                             ...    ...            ...
2024-12-31 Tablet     West      638     16          39.88
           Smartwatch North     308      9          34.22
                      South     266     20          13.30
                      East      510     14          36.43
                      West      268     15          17.87

[192 rows x 3 columns]

In [29]:
multi_index_df.head(10)

                              Sales  Units  Average Price
Date       Product    Region
2024-01-31 Laptop     North    1956     19         102.95
                      South    1274     18          70.78
                      East     1686     12         140.50
                      West     1740      7         248.57
           Smartphone North     636     14          45.43
                      South     753     15          50.20
                      East     1141     17          67.12
                      West      588     13          45.23
           Tablet     North     640      8          80.00
                      South     557     11          50.64

In [30]:
multi_index_df.unstack(level="Region").head(8)

                      Sales                   Units                   \
Region                 East North South  West  East North South West
Date       Product
2024-01-31 Laptop      1686  1956  1274  1740    12    19    18    7
           Smartphone  1141   636   753   588    17    14    15   13
           Smartwatch   337   344   309   338     8    20    12   23
           Tablet       715   640   557   347     5     8    11   14
2024-02-29 Laptop      1797  1930  1404  1035    13     6     9    5
           Smartphone   522  1178   761   767    26    12    19   12
           Smartwatch   214   251   390   495    20    22    23   22
           Tablet       314   471   511   721     8     9     6   12

                      Average Price
Region                         East   North   South    West
Date       Product
2024-01-31 Laptop            140.50  102.95   70.78  248.57
           Smartphone         67.12   45.43   50.20   45.23
           Smartwatch         42.12   17.20   25.75   14.70
           Tablet            143.00   80.00   50.64   24.79
2024-02-29 Laptop            138.23  321.67  156.00  207.00
           Smartphone         20.08   98.17   40.05   63.92
           Smartwatch         10.70   11.41   16.96   22.50
           Tablet             39.25   52.33   85.17   60.08

In [31]:
stacked_sales.unstack().unstack()

Region  Product
East    Laptop        18910
        Smartphone    10785
        Smartwatch     4415
        Tablet         6192
North   Laptop        19005
        Smartphone    10785
        Smartwatch     3945
        Tablet         7034
South   Laptop        15976
        Smartphone    10962
        Smartwatch     3857
        Tablet         7002
West    Laptop        15203
        Smartphone    10411
        Smartwatch     4182
        Tablet         6455
dtype: int64

In [ ]:
avg_price_pivot = df.pivot_table(
    index=["Product", "Region"], columns="Date", values="Average Price", aggfunc="mean"
)

avg_price_pivot.head(8)

Date               2024-01-31  2024-02-29  2024-03-31  2024-04-30  2024-05-31  \
Product    Region
Laptop     East        140.50      138.23      187.00       94.67       90.67
           North       102.95      321.67      168.30      236.80      144.33
           South        70.78      156.00       95.83      395.00      136.83
           West        248.57      207.00      107.75       95.17       74.08
Smartphone East         67.12       20.08       47.79      103.40       32.39
           North        45.43       98.17       46.09      116.90       35.00
           South        50.20       40.05       34.78       30.68       34.27
           West         45.23       63.92       38.04       76.00       64.10

Date               2024-06-30  2024-07-31  2024-08-31  2024-09-30  2024-10-31  \
Product    Region
Laptop     East        216.22       76.21      184.67       92.36      272.86
           North       146.00       68.47      175.90       84.71       80.33
           South       351.40       59.53      122.60       53.68       63.25
           West         96.64      266.80      116.10       94.86      171.75
Smartphone East         72.77       99.73       21.24       68.00       38.15
           North        37.94       39.46       42.33       31.00       37.50
           South        55.84       97.67       85.50       37.62       39.84
           West         39.41       36.39       44.08       32.58       49.15

Date               2024-11-30  2024-12-31
Product    Region
Laptop     East        183.30      212.89
           North        80.91      170.71
           South        68.53      145.71
           West         81.21      115.47
Smartphone East         71.54       46.80
           North        58.43       47.23
           South        36.10       38.09
           West         66.07       64.75

In [33]:
avg_price_pivot.stack().head(10)

Product  Region  Date
Laptop   East    2024-01-31    140.50
                 2024-02-29    138.23
                 2024-03-31    187.00
                 2024-04-30     94.67
                 2024-05-31     90.67
                 2024-06-30    216.22
                 2024-07-31     76.21
                 2024-08-31    184.67
                 2024-09-30     92.36
                 2024-10-31    272.86
dtype: float64

In [34]:
avg_price_pivot.unstack()

Date       2024-01-31                        2024-02-29                  \
Region           East   North  South    West       East   North   South
Product
Laptop         140.50  102.95  70.78  248.57     138.23  321.67  156.00
Smartphone      67.12   45.43  50.20   45.23      20.08   98.17   40.05
Smartwatch      42.12   17.20  25.75   14.70      10.70   11.41   16.96
Tablet         143.00   80.00  50.64   24.79      39.25   52.33   85.17

Date               2024-03-31          ... 2024-10-31         2024-11-30  \
Region        West       East   North  ...      South    West       East
Product                                ...
Laptop      207.00     187.00  168.30  ...      63.25  171.75     183.30
Smartphone   63.92      47.79   46.09  ...      39.84   49.15      71.54
Smartwatch   22.50      27.17   19.15  ...      28.18   19.54      14.21
Tablet       60.08      63.88   46.00  ...      32.50   31.00      37.25

Date                            2024-12-31
Region      North  South   West       East   North   South    West
Product
Laptop      80.91  68.53  81.21     212.89  170.71  145.71  115.47
Smartphone  58.43  36.10  66.07      46.80   47.23   38.09   64.75
Smartwatch  42.40  12.45  18.12      36.43   34.22   13.30   17.87
Tablet      53.56  57.10  61.73      70.40   69.85   59.77   39.88

[4 rows x 48 columns]

In [35]:
avg_price_pivot.unstack().stack(level="Region", future_stack=True)

Date               2024-01-31  2024-02-29  2024-03-31  2024-04-30  2024-05-31  \
Product    Region
Laptop     East        140.50      138.23      187.00       94.67       90.67
           North       102.95      321.67      168.30      236.80      144.33
           South        70.78      156.00       95.83      395.00      136.83
           West        248.57      207.00      107.75       95.17       74.08
Smartphone East         67.12       20.08       47.79      103.40       32.39
           North        45.43       98.17       46.09      116.90       35.00
           South        50.20       40.05       34.78       30.68       34.27
           West         45.23       63.92       38.04       76.00       64.10
Smartwatch East         42.12       10.70       27.17       14.00       40.00
           North        17.20       11.41       19.15       47.78       18.80
           South        25.75       16.96       12.32       16.55       30.14
           West         14.70       22.50       26.06       14.86       19.33
Tablet     East        143.00       39.25       63.88       35.00       49.82
           North        80.00       52.33       46.00       79.80       66.40
           South        50.64       85.17       82.22      146.00       42.43
           West         24.79       60.08       43.90       70.43       92.71

Date               2024-06-30  2024-07-31  2024-08-31  2024-09-30  2024-10-31  \
Product    Region
Laptop     East        216.22       76.21      184.67       92.36      272.86
           North       146.00       68.47      175.90       84.71       80.33
           South       351.40       59.53      122.60       53.68       63.25
           West         96.64      266.80      116.10       94.86      171.75
Smartphone East         72.77       99.73       21.24       68.00       38.15
           North        37.94       39.46       42.33       31.00       37.50
           South        55.84       97.67       85.50       37.62       39.84
           West         39.41       36.39       44.08       32.58       49.15
Smartwatch East         10.95       13.45       24.15       20.18       20.17
           North        14.25       17.93       27.69       14.78       14.63
           South        46.60       20.26        9.62        9.62       28.18
           West         19.86       19.64       19.92       21.83       19.54
Tablet     East         52.43       46.58       21.79      119.17       90.50
           North        73.00       52.50      156.40       50.40       72.83
           South       140.20       79.50       50.60       34.82       32.50
           West         98.71       52.14       31.27       45.55       31.00

Date               2024-11-30  2024-12-31
Product    Region
Laptop     East        183.30      212.89
           North        80.91      170.71
           South        68.53      145.71
           West         81.21      115.47
Smartphone East         71.54       46.80
           North        58.43       47.23
           South        36.10       38.09
           West         66.07       64.75
Smartwatch East         14.21       36.43
           North        42.40       34.22
           South        12.45       13.30
           West         18.12       17.87
Tablet     East         37.25       70.40
           North        53.56       69.85
           South        57.10       59.77
           West         61.73       39.88

### Melting DataFrames

In [ ]:
sales_pivot = df.pivot_table(
    index="Product", columns="Region", values="Sales", aggfunc="sum"
).reset_index()
sales_pivot

Region     Product   East  North  South   West
0           Laptop  18910  19005  15976  15203
1       Smartphone  10785  10785  10962  10411
2       Smartwatch   4415   3945   3857   4182
3           Tablet   6192   7034   7002   6455

In [40]:
sales_pivot.columns.name

'Region'

In [41]:
sales_pivot.columns.name = None

In [42]:
sales_pivot

      Product   East  North  South   West
0      Laptop  18910  19005  15976  15203
1  Smartphone  10785  10785  10962  10411
2  Smartwatch   4415   3945   3857   4182
3      Tablet   6192   7034   7002   6455

In [43]:
sales_pivot.melt(id_vars="Product")

       Product variable  value
0       Laptop     East  18910
1   Smartphone     East  10785
2   Smartwatch     East   4415
3       Tablet     East   6192
4       Laptop    North  19005
5   Smartphone    North  10785
6   Smartwatch    North   3945
7       Tablet    North   7034
8       Laptop    South  15976
9   Smartphone    South  10962
10  Smartwatch    South   3857
11      Tablet    South   7002
12      Laptop     West  15203
13  Smartphone     West  10411
14  Smartwatch     West   4182
15      Tablet     West   6455

In [44]:
sales_pivot.melt(id_vars="Product", var_name="Region", value_name="Total Sales")

       Product Region  Total Sales
0       Laptop   East        18910
1   Smartphone   East        10785
2   Smartwatch   East         4415
3       Tablet   East         6192
4       Laptop  North        19005
5   Smartphone  North        10785
6   Smartwatch  North         3945
7       Tablet  North         7034
8       Laptop  South        15976
9   Smartphone  South        10962
10  Smartwatch  South         3857
11      Tablet  South         7002
12      Laptop   West        15203
13  Smartphone   West        10411
14  Smartwatch   West         4182
15      Tablet   West         6455

In [47]:
subset_df = df[["Date", "Product", "Sales", "Units"]].head(20)
subset_df

         Date     Product  Sales  Units
0  2024-01-31      Laptop   1956     19
1  2024-01-31      Laptop   1274     18
2  2024-01-31      Laptop   1686     12
3  2024-01-31      Laptop   1740      7
4  2024-01-31  Smartphone    636     14
5  2024-01-31  Smartphone    753     15
6  2024-01-31  Smartphone   1141     17
7  2024-01-31  Smartphone    588     13
8  2024-01-31      Tablet    640      8
9  2024-01-31      Tablet    557     11
10 2024-01-31      Tablet    715      5
11 2024-01-31      Tablet    347     14
12 2024-01-31  Smartwatch    344     20
13 2024-01-31  Smartwatch    309     12
14 2024-01-31  Smartwatch    337      8
15 2024-01-31  Smartwatch    338     23
16 2024-02-29      Laptop   1930      6
17 2024-02-29      Laptop   1404      9
18 2024-02-29      Laptop   1797     13
19 2024-02-29      Laptop   1035      5

In [ ]:
subset_df.melt(id_vars=["Date", "Product"], var_name="Metric", value_name="Value")

         Date     Product Metric  Value
0  2024-01-31      Laptop  Sales   1956
1  2024-01-31      Laptop  Sales   1274
2  2024-01-31      Laptop  Sales   1686
3  2024-01-31      Laptop  Sales   1740
4  2024-01-31  Smartphone  Sales    636
5  2024-01-31  Smartphone  Sales    753
6  2024-01-31  Smartphone  Sales   1141
7  2024-01-31  Smartphone  Sales    588
8  2024-01-31      Tablet  Sales    640
9  2024-01-31      Tablet  Sales    557
10 2024-01-31      Tablet  Sales    715
11 2024-01-31      Tablet  Sales    347
12 2024-01-31  Smartwatch  Sales    344
13 2024-01-31  Smartwatch  Sales    309
14 2024-01-31  Smartwatch  Sales    337
15 2024-01-31  Smartwatch  Sales    338
16 2024-02-29      Laptop  Sales   1930
17 2024-02-29      Laptop  Sales   1404
18 2024-02-29      Laptop  Sales   1797
19 2024-02-29      Laptop  Sales   1035
20 2024-01-31      Laptop  Units     19
21 2024-01-31      Laptop  Units     18
22 2024-01-31      Laptop  Units     12
23 2024-01-31      Laptop  Units      7
24 2024-01-31  Smartphone  Units     14
25 2024-01-31  Smartphone  Units     15
26 2024-01-31  Smartphone  Units     17
27 2024-01-31  Smartphone  Units     13
28 2024-01-31      Tablet  Units      8
29 2024-01-31      Tablet  Units     11
30 2024-01-31      Tablet  Units      5
31 2024-01-31      Tablet  Units     14
32 2024-01-31  Smartwatch  Units     20
33 2024-01-31  Smartwatch  Units     12
34 2024-01-31  Smartwatch  Units      8
35 2024-01-31  Smartwatch  Units     23
36 2024-02-29      Laptop  Units      6
37 2024-02-29      Laptop  Units      9
38 2024-02-29      Laptop  Units     13
39 2024-02-29      Laptop  Units      5

In [ ]:
# Creating a wide-format DataFrame
wide_df = df.pivot_table(
    index=["Product", "Date"],
    columns="Region",
    values=["Sales", "Units"],
).reset_index()

wide_df

           Product       Date   Sales                         Units        \
Region                           East   North   South    West  East North
0           Laptop 2024-01-31  1686.0  1956.0  1274.0  1740.0  12.0  19.0
1           Laptop 2024-02-29  1797.0  1930.0  1404.0  1035.0  13.0   6.0
2           Laptop 2024-03-31  1870.0  1683.0  1725.0   862.0  10.0  10.0
3           Laptop 2024-04-30   852.0  1184.0  1975.0  1142.0   9.0   5.0
4           Laptop 2024-05-31  1632.0  1299.0  1642.0   889.0  18.0   9.0
5           Laptop 2024-06-30  1946.0  1606.0  1757.0  1063.0   9.0  11.0
6           Laptop 2024-07-31  1067.0  1027.0   893.0  1334.0  14.0  15.0
7           Laptop 2024-08-31  1108.0  1759.0  1226.0  1161.0   6.0  10.0
8           Laptop 2024-09-30  1293.0  1186.0  1020.0  1328.0  14.0  14.0
9           Laptop 2024-10-31  1910.0  1205.0  1012.0  1374.0   7.0  15.0
10          Laptop 2024-11-30  1833.0  1780.0  1028.0  1543.0  10.0  22.0
11          Laptop 2024-12-31  1916.0  2390.0  1020.0  1732.0   9.0  14.0
12      Smartphone 2024-01-31  1141.0   636.0   753.0   588.0  17.0  14.0
13      Smartphone 2024-02-29   522.0  1178.0   761.0   767.0  26.0  12.0
14      Smartphone 2024-03-31   908.0  1014.0   800.0   951.0  19.0  22.0
15      Smartphone 2024-04-30  1034.0  1169.0   859.0  1140.0  10.0  10.0
16      Smartphone 2024-05-31   907.0   525.0   891.0   641.0  28.0  15.0
17      Smartphone 2024-06-30   946.0   607.0  1061.0   670.0  13.0  16.0
18      Smartphone 2024-07-31  1097.0   947.0  1172.0  1019.0  11.0  24.0
19      Smartphone 2024-08-31   616.0   889.0  1026.0  1102.0  29.0  21.0
20      Smartphone 2024-09-30   952.0   651.0   903.0   782.0  14.0  21.0
21      Smartphone 2024-10-31  1030.0   525.0   757.0   983.0  27.0  14.0
22      Smartphone 2024-11-30   930.0  1227.0   722.0   991.0  13.0  21.0
23      Smartphone 2024-12-31   702.0  1417.0  1257.0   777.0  15.0  30.0
24      Smartwatch 2024-01-31   337.0   344.0   309.0   338.0   8.0  20.0
25      Smartwatch 2024-02-29   214.0   251.0   390.0   495.0  20.0  22.0
26      Smartwatch 2024-03-31   489.0   383.0   271.0   417.0  18.0  20.0
27      Smartwatch 2024-04-30   308.0   430.0   331.0   208.0  22.0   9.0
28      Smartwatch 2024-05-31   440.0   282.0   422.0   464.0  11.0  15.0
29      Smartwatch 2024-06-30   208.0   285.0   466.0   417.0  19.0  20.0
30      Smartwatch 2024-07-31   269.0   251.0   385.0   216.0  20.0  14.0
31      Smartwatch 2024-08-31   314.0   443.0   202.0   259.0  13.0  16.0
32      Smartwatch 2024-09-30   444.0   266.0   231.0   393.0  22.0  18.0
33      Smartwatch 2024-10-31   484.0   278.0   310.0   254.0  24.0  19.0
34      Smartwatch 2024-11-30   398.0   424.0   274.0   453.0  28.0  10.0
35      Smartwatch 2024-12-31   510.0   308.0   266.0   268.0  14.0   9.0
36          Tablet 2024-01-31   715.0   640.0   557.0   347.0   5.0   8.0
37          Tablet 2024-02-29   314.0   471.0   511.0   721.0   8.0   9.0
38          Tablet 2024-03-31   511.0   460.0   740.0   439.0   8.0  10.0
39          Tablet 2024-04-30   315.0   399.0   730.0   493.0   9.0   5.0
40          Tablet 2024-05-31   548.0   664.0   594.0   649.0  11.0  10.0
41          Tablet 2024-06-30   367.0   657.0   701.0   691.0   7.0   9.0
42          Tablet 2024-07-31   559.0   630.0   477.0   365.0  12.0  12.0
43          Tablet 2024-08-31   305.0   782.0   506.0   344.0  14.0   5.0
44          Tablet 2024-09-30   715.0   504.0   383.0   501.0   6.0  10.0
45          Tablet 2024-10-31   543.0   437.0   455.0   341.0   6.0   6.0
46          Tablet 2024-11-30   596.0   482.0   571.0   926.0  16.0   9.0
47          Tablet 2024-12-31   704.0   908.0   777.0   638.0  10.0  13.0


Region South  West
0       18.0   7.0
1        9.0   5.0
2       18.0   8.0
3        5.0  12.0
4       12.0  12.0
5        5.0  11.0
6       15.0   5.0
7       10.0  10.0
8       19.0  14.0
9       16.0   8.0
10      15.0  19.0
11       7.0  15.0
12      15.0  13.0
13      19.0  12.0
14      23.0  25.0
15      28.0  15.0
16      26.0  10.0
17      19.0  17.0
18      12.0  28.0
19      12.0  25.0
20      24.0  24.0
21      19.0  20.0
22      20.0  15.0
23      33.0  12.0
24      12.0  23.0
25      23.0  22.0
26      22.0  16.0
27      20.0  14.0
28      14.0  24.0
29      10.0  21.0
30      19.0  11.0
31      21.0  13.0
32      24.0  18.0
33      11.0  13.0
34      22.0  25.0
35      20.0  15.0
36      11.0  14.0
37       6.0  12.0
38       9.0  10.0
39       5.0   7.0
40      14.0   7.0
41       5.0   7.0
42       6.0   7.0
43      10.0  11.0
44      11.0  11.0
45      14.0  11.0
46      10.0  15.0
47      13.0  16.0

In [ ]:
wide_df.columns = ["Product", "Date"] + [
    f"{col[0]}_{col[1]}" for col in wide_df.columns[2:]
]

In [52]:
wide_df

,Product,Date,Sales_East,Sales_North,Sales_South,Sales_West,Units_East,Units_North,Units_South,Units_West
0,Laptop,2024-01-31,1686.0,1956.0,1274.0,1740.0,12.0,19.0,18.0,7.0
1,Laptop,2024-02-29,1797.0,1930.0,1404.0,1035.0,13.0,6.0,9.0,5.0
2,Laptop,2024-03-31,1870.0,1683.0,1725.0,862.0,10.0,10.0,18.0,8.0
3,Laptop,2024-04-30,852.0,1184.0,1975.0,1142.0,9.0,5.0,5.0,12.0
4,Laptop,2024-05-31,1632.0,1299.0,1642.0,889.0,18.0,9.0,12.0,12.0
5,Laptop,2024-06-30,1946.0,1606.0,1757.0,1063.0,9.0,11.0,5.0,11.0
6,Laptop,2024-07-31,1067.0,1027.0,893.0,1334.0,14.0,15.0,15.0,5.0
7,Laptop,2024-08-31,1108.0,1759.0,1226.0,1161.0,6.0,10.0,10.0,10.0
8,Laptop,2024-09-30,1293.0,1186.0,1020.0,1328.0,14.0,14.0,19.0,14.0
9,Laptop,2024-10-31,1910.0,1205.0,1012.0,1374.0,7.0,15.0,16.0,8.0
10,Laptop,2024-11-30,1833.0,1780.0,1028.0,1543.0,10.0,22.0,15.0,19.0
11,Laptop,2024-12-31,1916.0,2390.0,1020.0,1732.0,9.0,14.0,7.0,15.0
12,Smartphone,2024-01-31,1141.0,636.0,753.0,588.0,17.0,14.0,15.0,13.0
13,Smartphone,2024-02-29,522.0,1178.0,761.0,767.0,26.0,12.0,19.0,12.0
14,Smartphone,2024-03-31,908.0,1014.0,800.0,951.0,19.0,22.0,23.0,25.0
15,Smartphone,2024-04-30,1034.0,1169.0,859.0,1140.0,10.0,10.0,28.0,15.0
16,Smartphone,2024-05-31,907.0,525.0,891.0,641.0,28.0,15.0,26.0,10.0
17,Smartphone,2024-06-30,946.0,607.0,1061.0,670.0,13.0,16.0,19.0,17.0
18,Smartphone,2024-07-31,1097.0,947.0,1172.0,1019.0,11.0,24.0,12.0,28.0
19,Smartphone,2024-08-31,616.0,889.0,1026.0,1102.0,29.0,21.0,12.0,25.0
20,Smartphone,2024-09-30,952.0,651.0,903.0,782.0,14.0,21.0,24.0,24.0
21,Smartphone,2024-10-31,1030.0,525.0,757.0,983.0,27.0,14.0,19.0,20.0
22,Smartphone,2024-11-30,930.0,1227.0,722.0,991.0,13.0,21.0,20.0,15.0
23,Smartphone,2024-12-31,702.0,1417.0,1257.0,777.0,15.0,30.0,33.0,12.0
24,Smartwatch,2024-01-31,337.0,344.0,309.0,338.0,8.0,20.0,12.0,23.0
25,Smartwatch,2024-02-29,214.0,251.0,390.0,495.0,20.0,22.0,23.0,22.0
26,Smartwatch,2024-03-31,489.0,383.0,271.0,417.0,18.0,20.0,22.0,16.0
27,Smartwatch,2024-04-30,308.0,430.0,331.0,208.0,22.0,9.0,20.0,14.0
28,Smartwatch,2024-05-31,440.0,282.0,422.0,464.0,11.0,15.0,14.0,24.0
29,Smartwatch,2024-06-30,208.0,285.0,466.0,417.0,19.0,20.0,10.0,21.0
30,Smartwatch,2024-07-31,269.0,251.0,385.0,216.0,20.0,14.0,19.0,11.0
31,Smartwatch,2024-08-31,314.0,443.0,202.0,259.0,13.0,16.0,21.0,13.0
32,Smartwatch,2024-09-30,444.0,266.0,231.0,393.0,22.0,18.0,24.0,18.0
33,Smartwatch,2024-10-31,484.0,278.0,310.0,254.0,24.0,19.0,11.0,13.0
34,Smartwatch,2024-11-30,398.0,424.0,274.0,453.0,28.0,10.0,22.0,25.0
35,Smartwatch,2024-12-31,510.0,308.0,266.0,268.0,14.0,9.0,20.0,15.0
36,Tablet,2024-01-31,715.0,640.0,557.0,347.0,5.0,8.0,11.0,14.0
37,Tablet,2024-02-29,314.0,471.0,511.0,721.0,8.0,9.0,6.0,12.0
38,Tablet,2024-03-31,511.0,460.0,740.0,439.0,8.0,10.0,9.0,10.0
39,Tablet,2024-04-30,315.0,399.0,730.0,493.0,9.0,5.0,5.0,7.0
40,Tablet,2024-05-31,548.0,664.0,594.0,649.0,11.0,10.0,14.0,7.0
41,Tablet,2024-06-30,367.0,657.0,701.0,691.0,7.0,9.0,5.0,7.0
42,Tablet,2024-07-31,559.0,630.0,477.0,365.0,12.0,12.0,6.0,7.0
43,Tablet,2024-08-31,305.0,782.0,506.0,344.0,14.0,5.0,10.0,11.0
44,Tablet,2024-09-30,715.0,504.0,383.0,501.0,6.0,10.0,11.0,11.0
45,Tablet,2024-10-31,543.0,437.0,455.0,341.0,6.0,6.0,14.0,11.0
46,Tablet,2024-11-30,596.0,482.0,571.0,926.0,16.0,9.0,10.0,15.0
47,Tablet,2024-12-31,704.0,908.0,777.0,638.0,10.0,13.0,13.0,16.0

In [ ]:
pd.wide_to_long(
    wide_df,
    i=["Product", "Date"],
    stubnames=["Sales", "Units"],
    sep="_",
    suffix=r"\w+",
    j="Region",
).head(10)

                            Sales  Units
Product Date       Region
Laptop  2024-01-31 East    1686.0   12.0
                   North   1956.0   19.0
                   South   1274.0   18.0
                   West    1740.0    7.0
        2024-02-29 East    1797.0   13.0
                   North   1930.0    6.0
                   South   1404.0    9.0
                   West    1035.0    5.0
        2024-03-31 East    1870.0   10.0
                   North   1683.0   10.0

### Exploding List-like Columns

In [ ]:
df_list = pd.DataFrame(
    {
        "Product": ["Laptop", "Smartphone", "Tablet"],
        "Brands": [
            ["Dell", "HP", "Lenovo"],
            ["Apple", "Samsung", "Google"],
            ["Apple", "Samsung", "Microsoft"],
        ],
        "Average Price": [1200, 800, 650],
    }
)

df_list

      Product                       Brands  Average Price
0      Laptop           [Dell, HP, Lenovo]           1200
1  Smartphone     [Apple, Samsung, Google]            800
2      Tablet  [Apple, Samsung, Microsoft]            650

In [65]:
df_list["Brands"].value_counts()

Brands
[Dell, HP, Lenovo]             1
[Apple, Samsung, Google]       1
[Apple, Samsung, Microsoft]    1
Name: count, dtype: int64

In [56]:
df_list.explode("Brands")

      Product     Brands  Average Price
0      Laptop       Dell           1200
0      Laptop         HP           1200
0      Laptop     Lenovo           1200
1  Smartphone      Apple            800
1  Smartphone    Samsung            800
1  Smartphone     Google            800
2      Tablet      Apple            650
2      Tablet    Samsung            650
2      Tablet  Microsoft            650

In [66]:
df_list.explode("Brands")["Brands"].value_counts()

Brands
Apple        2
Samsung      2
Dell         1
Lenovo       1
HP           1
Google       1
Microsoft    1
Name: count, dtype: int64

In [ ]:
df_grouped = (
    df.groupby("Product")
    .agg({"Region": lambda x: x.unique().tolist(), "Sales": "sum", "Units": "sum"})
    .reset_index()
)

df_grouped

      Product                      Region  Sales  Units
0      Laptop  [North, South, East, West]  69094    556
1  Smartphone  [North, South, East, West]  42943    908
2  Smartwatch  [North, South, East, West]  16399    844
3      Tablet  [North, South, East, West]  26683    460

In [60]:
df_grouped.explode("Region")

      Product Region  Sales  Units
0      Laptop  North  69094    556
0      Laptop  South  69094    556
0      Laptop   East  69094    556
0      Laptop   West  69094    556
1  Smartphone  North  42943    908
1  Smartphone  South  42943    908
1  Smartphone   East  42943    908
1  Smartphone   West  42943    908
2  Smartwatch  North  16399    844
2  Smartwatch  South  16399    844
2  Smartwatch   East  16399    844
2  Smartwatch   West  16399    844
3      Tablet  North  26683    460
3      Tablet  South  26683    460
3      Tablet   East  26683    460
3      Tablet   West  26683    460

In [ ]:
monthly_sales = pd.DataFrame(
    {
        "Month": pd.date_range(start="2024-01-01", end="2024-12-31", freq="ME"),
        "Products Sold": [
            ["Laptop", "Smartphone"],
            ["Smartphone", "Tablet", "Smartwatch"],
            ["Laptop", "Tablet"],
            ["Smartphone", "Smartwatch"],
            ["Laptop", "Smartphone", "Tablet"],
            ["Tablet", "Smartwatch"],
            ["Laptop", "Smartphone"],
            ["Smartphone", "Tablet"],
            ["Laptop", "Smartwatch"],
            ["Smartphone", "Tablet"],
            ["Laptop", "Smartphone", "Smartwatch"],
            ["Tablet", "Smartwatch"],
        ],
    }
)

monthly_sales

        Month                     Products Sold
0  2024-01-31              [Laptop, Smartphone]
1  2024-02-29  [Smartphone, Tablet, Smartwatch]
2  2024-03-31                  [Laptop, Tablet]
3  2024-04-30          [Smartphone, Smartwatch]
4  2024-05-31      [Laptop, Smartphone, Tablet]
5  2024-06-30              [Tablet, Smartwatch]
6  2024-07-31              [Laptop, Smartphone]
7  2024-08-31              [Smartphone, Tablet]
8  2024-09-30              [Laptop, Smartwatch]
9  2024-10-31              [Smartphone, Tablet]
10 2024-11-30  [Laptop, Smartphone, Smartwatch]
11 2024-12-31              [Tablet, Smartwatch]

In [70]:
exploded_sales = monthly_sales.explode("Products Sold").reset_index(drop=True)
exploded_sales

        Month Products Sold
0  2024-01-31        Laptop
1  2024-01-31    Smartphone
2  2024-02-29    Smartphone
3  2024-02-29        Tablet
4  2024-02-29    Smartwatch
5  2024-03-31        Laptop
6  2024-03-31        Tablet
7  2024-04-30    Smartphone
8  2024-04-30    Smartwatch
9  2024-05-31        Laptop
10 2024-05-31    Smartphone
11 2024-05-31        Tablet
12 2024-06-30        Tablet
13 2024-06-30    Smartwatch
14 2024-07-31        Laptop
15 2024-07-31    Smartphone
16 2024-08-31    Smartphone
17 2024-08-31        Tablet
18 2024-09-30        Laptop
19 2024-09-30    Smartwatch
20 2024-10-31    Smartphone
21 2024-10-31        Tablet
22 2024-11-30        Laptop
23 2024-11-30    Smartphone
24 2024-11-30    Smartwatch
25 2024-12-31        Tablet
26 2024-12-31    Smartwatch

In [68]:
exploded_sales["Products Sold"].value_counts()

Products Sold
Smartphone    8
Tablet        7
Laptop        6
Smartwatch    6
Name: count, dtype: int64

### Cross-tabulation

In [71]:
df

          Date     Product Region  Sales  Units  Average Price
0   2024-01-31      Laptop  North   1956     19         102.95
1   2024-01-31      Laptop  South   1274     18          70.78
2   2024-01-31      Laptop   East   1686     12         140.50
3   2024-01-31      Laptop   West   1740      7         248.57
4   2024-01-31  Smartphone  North    636     14          45.43
..         ...         ...    ...    ...    ...            ...
187 2024-12-31      Tablet   West    638     16          39.88
188 2024-12-31  Smartwatch  North    308      9          34.22
189 2024-12-31  Smartwatch  South    266     20          13.30
190 2024-12-31  Smartwatch   East    510     14          36.43
191 2024-12-31  Smartwatch   West    268     15          17.87

[192 rows x 6 columns]

In [ ]:
pd.crosstab(df["Product"], df["Region"])  # frequency dist

Region      East  North  South  West
Product
Laptop        12     12     12    12
Smartphone    12     12     12    12
Smartwatch    12     12     12    12
Tablet        12     12     12    12

In [73]:
pd.crosstab(df["Product"], df["Region"], values=df["Sales"], aggfunc="sum")

Region       East  North  South   West
Product
Laptop      18910  19005  15976  15203
Smartphone  10785  10785  10962  10411
Smartwatch   4415   3945   3857   4182
Tablet       6192   7034   7002   6455

In [75]:
# percentage distribution of each product across regions
pd.crosstab(df["Product"], df["Region"], normalize="index")

Region      East  North  South  West
Product
Laptop      0.25   0.25   0.25  0.25
Smartphone  0.25   0.25   0.25  0.25
Smartwatch  0.25   0.25   0.25  0.25
Tablet      0.25   0.25   0.25  0.25

In [76]:
df["Quarter"] = df["Date"].dt.to_period("Q")

In [77]:
df

          Date     Product Region  Sales  Units  Average Price Quarter
0   2024-01-31      Laptop  North   1956     19         102.95  2024Q1
1   2024-01-31      Laptop  South   1274     18          70.78  2024Q1
2   2024-01-31      Laptop   East   1686     12         140.50  2024Q1
3   2024-01-31      Laptop   West   1740      7         248.57  2024Q1
4   2024-01-31  Smartphone  North    636     14          45.43  2024Q1
..         ...         ...    ...    ...    ...            ...     ...
187 2024-12-31      Tablet   West    638     16          39.88  2024Q4
188 2024-12-31  Smartwatch  North    308      9          34.22  2024Q4
189 2024-12-31  Smartwatch  South    266     20          13.30  2024Q4
190 2024-12-31  Smartwatch   East    510     14          36.43  2024Q4
191 2024-12-31  Smartwatch   West    268     15          17.87  2024Q4

[192 rows x 7 columns]

In [ ]:
pd.crosstab(
    [df["Product"], df["Quarter"]], df["Region"], values=df["Sales"], aggfunc="sum"
)

Region              East  North  South  West
Product    Quarter
Laptop     2024Q1   5353   5569   4403  3637
           2024Q2   4430   4089   5374  3094
           2024Q3   3468   3972   3139  3823
           2024Q4   5659   5375   3060  4649
Smartphone 2024Q1   2571   2828   2314  2306
           2024Q2   2887   2301   2811  2451
           2024Q3   2665   2487   3101  2903
           2024Q4   2662   3169   2736  2751
Smartwatch 2024Q1   1040    978    970  1250
           2024Q2    956    997   1219  1089
           2024Q3   1027    960    818   868
           2024Q4   1392   1010    850   975
Tablet     2024Q1   1540   1571   1808  1507
           2024Q2   1230   1720   2025  1833
           2024Q3   1579   1916   1366  1210
           2024Q4   1843   1827   1803  1905

### Discretization and Categorization

In [ ]:
df["Sales Category"] = pd.cut(
    df["Sales"],
    bins=[0, 500, 1000, 1500, np.inf],
    labels=["Low", "Medium", "High", "Very High"],
)

In [82]:
df[["Product", "Sales", "Sales Category"]].head(10)

      Product  Sales Sales Category
0      Laptop   1956      Very High
1      Laptop   1274           High
2      Laptop   1686      Very High
3      Laptop   1740      Very High
4  Smartphone    636         Medium
5  Smartphone    753         Medium
6  Smartphone   1141           High
7  Smartphone    588         Medium
8      Tablet    640         Medium
9      Tablet    557         Medium

In [83]:
df["Sales Category"]

0      Very High
1           High
2      Very High
3      Very High
4         Medium
         ...
187       Medium
188          Low
189          Low
190       Medium
191          Low
Name: Sales Category, Length: 192, dtype: category
Categories (4, object): ['Low' < 'Medium' < 'High' < 'Very High']

In [85]:
df["Sales Category"].value_counts().sort_index()

Sales Category
Low          65
Medium       67
High         38
Very High    22
Name: count, dtype: int64

In [100]:
df["Sales Category"].cat.codes

0      3
1      2
2      3
3      3
4      1
      ..
187    1
188    0
189    0
190    1
191    0
Length: 192, dtype: int8

In [101]:
df["Sales Category"].cat.ordered

True

In [ ]:
pd.cut(df["Sales"], bins=5, include_lowest=True)

0      (1952.4, 2390.0]
1      (1077.2, 1514.8]
2      (1514.8, 1952.4]
3      (1514.8, 1952.4]
4      (199.811, 639.6]
             ...
187    (199.811, 639.6]
188    (199.811, 639.6]
189    (199.811, 639.6]
190    (199.811, 639.6]
191    (199.811, 639.6]
Name: Sales, Length: 192, dtype: category
Categories (5, interval[float64, right]): [(199.811, 639.6] < (639.6, 1077.2] < (1077.2, 1514.8] < (1514.8, 1952.4] < (1952.4, 2390.0]]

In [93]:
df["Sales Quartile"] = pd.qcut(df["Sales"], q=4, labels=["Low", "Medium", "High", "Very High"])

In [96]:
df[["Product", "Sales", "Sales Category", "Sales Quartile"]].head(8)

      Product  Sales Sales Category Sales Quartile
0      Laptop   1956      Very High      Very High
1      Laptop   1274           High      Very High
2      Laptop   1686      Very High      Very High
3      Laptop   1740      Very High      Very High
4  Smartphone    636         Medium         Medium
5  Smartphone    753         Medium           High
6  Smartphone   1141           High      Very High
7  Smartphone    588         Medium         Medium

In [99]:
pd.qcut(df["Sales"], q=6)

0      (1226.167, 2390.0]
1      (1226.167, 2390.0]
2      (1226.167, 2390.0]
3      (1226.167, 2390.0]
4        (494.333, 701.5]
              ...
187      (494.333, 701.5]
188      (201.999, 344.0]
189      (201.999, 344.0]
190      (494.333, 701.5]
191      (201.999, 344.0]
Name: Sales, Length: 192, dtype: category
Categories (6, interval[float64, right]): [(201.999, 344.0] < (344.0, 494.333] < (494.333, 701.5] < (701.5, 948.333] < (948.333, 1226.167] < (1226.167, 2390.0]]

In [103]:
df["Sales Quartile"].value_counts()

Sales Quartile
Low          48
Medium       48
High         48
Very High    48
Name: count, dtype: int64