# Coding Practice Session 15
## Database Fundamentals

In this Lecture, I am going through basic concepts in databases. `pandas` is used to simulate SQL-like operations and commands.

Panda's Data Frames are used to represent database tables.

In [1]:
import pandas as pd

In [2]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["John Doe", "Jane Smith", "Bob Johnson", "Alice Brown"],
    "email": ["john@example.com", "jane@example.com", "bob@office.com", "alice@mydomain.com"]
})

In [3]:
print("\nCustomers Table:")
customers

Customers Table:

   customer_id         name               email
0            1     John Doe    john@example.com
1            2   Jane Smith    jane@example.com
2            3  Bob Johnson      bob@office.com
3            4  Alice Brown  alice@mydomain.com

In [4]:
orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105],
    'customer_id': [1, 2, 1, 3, 4],
    'product': ['Widget A', 'Widget B', 'Widget C', 'Widget A', 'Widget B'],
    'quantity': [2, 1, 3, 1, 2],
    'order_date': pd.to_datetime(['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04', '2025-05-05'])
})

In [5]:
print("\nOrders Table:")
orders

Orders Table:

   order_id  customer_id   product  quantity order_date
0       101            1  Widget A         2 2025-05-01
1       102            2  Widget B         1 2025-05-02
2       103            1  Widget C         3 2025-05-03
3       104            3  Widget A         1 2025-05-04
4       105            4  Widget B         2 2025-05-05

### Relational Database Concepts

- **Tables** (also called relations) represent entities or concepts (e.g., customers, orders).
- **Rows** (or records) represent individual instances of that entity.
- **Columns** (or fields) represent attributes of the entity.

In [6]:
# DataFrames or Tables
customers

   customer_id         name               email
0            1     John Doe    john@example.com
1            2   Jane Smith    jane@example.com
2            3  Bob Johnson      bob@office.com
3            4  Alice Brown  alice@mydomain.com

In [7]:
orders

   order_id  customer_id   product  quantity order_date
0       101            1  Widget A         2 2025-05-01
1       102            2  Widget B         1 2025-05-02
2       103            1  Widget C         3 2025-05-03
3       104            3  Widget A         1 2025-05-04
4       105            4  Widget B         2 2025-05-05

In [8]:
# row or record
customers.iloc[1]

customer_id                   2
name                 Jane Smith
email          jane@example.com
Name: 1, dtype: object

In [9]:
orders.iloc[-1]

order_id                       105
customer_id                      4
product                   Widget B
quantity                         2
order_date     2025-05-05 00:00:00
Name: 4, dtype: object

In [10]:
# column or field
customers["email"]

0      john@example.com
1      jane@example.com
2        bob@office.com
3    alice@mydomain.com
Name: email, dtype: object

In [11]:
orders["order_date"]

0   2025-05-01
1   2025-05-02
2   2025-05-03
3   2025-05-04
4   2025-05-05
Name: order_date, dtype: datetime64[ns]

- **Primary Keys**: A column (or set of columns) that uniquely identifies each row in a table.
- **Foreign Keys**: A column that refers to the primary key of another table, establishing a relationship between the tables

In [12]:
print("Primary Key in Customers Table:")
customers["customer_id"]

Primary Key in Customers Table:

0    1
1    2
2    3
3    4
Name: customer_id, dtype: int64

In [13]:
print("Primary Key in Orders Table:")
orders["order_id"]

Primary Key in Orders Table:

0    101
1    102
2    103
3    104
4    105
Name: order_id, dtype: int64

In [14]:
print("Foreign Key in Orders Table:")
orders["customer_id"] # connects to customers table

Foreign Key in Orders Table:

0    1
1    2
2    1
3    3
4    4
Name: customer_id, dtype: int64

Relationships Between Tables:

1. **One-to-One (1:1)**: Each record in Table A is related to exactly one record in Table B, and vice versa.

2. **One-to-Many (1:N)**: Each record in Table A can be related to multiple records in Table B, but each record in Table B is related to only one record in Table A.

3. **Many-to-Many (M:N)**: Multiple records in Table A can be related to multiple records in Table B, and vice versa.

There is a **One-to-Many** relationship between `customers` and `orders` tables. Each customer can have multiple orders, but each order belongs to exactly one customer.

In [15]:
# number of orders per customer_id
orders["customer_id"].value_counts()

customer_id
1    2
2    1
3    1
4    1
Name: count, dtype: int64

In [16]:
pd.merge(customers, orders, on="customer_id", how="outer")

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101,Widget A,2,2025-05-01
1,1,John Doe,john@example.com,103,Widget C,3,2025-05-03
2,2,Jane Smith,jane@example.com,102,Widget B,1,2025-05-02
3,3,Bob Johnson,bob@office.com,104,Widget A,1,2025-05-04
4,4,Alice Brown,alice@mydomain.com,105,Widget B,2,2025-05-05

### Basic SQL Operations

In each section, the SQL command and its pandas equivalent is given

1. SELECT Statement

```sql
SELECT * FROM customers;
```

In [17]:
customers

   customer_id         name               email
0            1     John Doe    john@example.com
1            2   Jane Smith    jane@example.com
2            3  Bob Johnson      bob@office.com
3            4  Alice Brown  alice@mydomain.com

In [18]:
customers[["email", "customer_id"]]

                email  customer_id
0    john@example.com            1
1    jane@example.com            2
2      bob@office.com            3
3  alice@mydomain.com            4

2. Filtering with WHERE

```sql
SELECT * FROM orders WHERE quantity > 1;
```

In [19]:
orders[orders["quantity"] > 1]

   order_id  customer_id   product  quantity order_date
0       101            1  Widget A         2 2025-05-01
2       103            1  Widget C         3 2025-05-03
4       105            4  Widget B         2 2025-05-05

3. Sorting with ORDER BY

```sql
SELECT * FROM orders ORDER BY quantity DESC;
```

In [20]:
orders.sort_values(by="quantity", ascending=False)

   order_id  customer_id   product  quantity order_date
2       103            1  Widget C         3 2025-05-03
0       101            1  Widget A         2 2025-05-01
4       105            4  Widget B         2 2025-05-05
1       102            2  Widget B         1 2025-05-02
3       104            3  Widget A         1 2025-05-04

4. Limiting Results with LIMIT

```sql
SELECT * FROM orders LIMIT 3;
```

In [21]:
customers.head(2)

   customer_id        name             email
0            1    John Doe  john@example.com
1            2  Jane Smith  jane@example.com

### Joining Tables

In [22]:
# Adding a customer with no orders and an order with no matching customer
customers.loc[len(customers)] = {'customer_id': 5, 'name': 'Dua Lipa', 'email': 'dua@example.com'}
orders.loc[len(orders)] = {'order_id': 106, 'customer_id': 6, 'product': 'Widget D', 'quantity': 1, 'order_date': '2025-05-06'}

In [23]:
customers

   customer_id         name               email
0            1     John Doe    john@example.com
1            2   Jane Smith    jane@example.com
2            3  Bob Johnson      bob@office.com
3            4  Alice Brown  alice@mydomain.com
4            5     Dua Lipa     dua@example.com

In [24]:
orders

   order_id  customer_id   product  quantity           order_date
0       101            1  Widget A         2  2025-05-01 00:00:00
1       102            2  Widget B         1  2025-05-02 00:00:00
2       103            1  Widget C         3  2025-05-03 00:00:00
3       104            3  Widget A         1  2025-05-04 00:00:00
4       105            4  Widget B         2  2025-05-05 00:00:00
5       106            6  Widget D         1           2025-05-06

In [25]:
# inner join
customers.merge(orders, on="customer_id", how="inner")

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101,Widget A,2,2025-05-01 00:00:00
1,1,John Doe,john@example.com,103,Widget C,3,2025-05-03 00:00:00
2,2,Jane Smith,jane@example.com,102,Widget B,1,2025-05-02 00:00:00
3,3,Bob Johnson,bob@office.com,104,Widget A,1,2025-05-04 00:00:00
4,4,Alice Brown,alice@mydomain.com,105,Widget B,2,2025-05-05 00:00:00

In [26]:
# left join
pd.merge(customers, orders, on="customer_id", how="left")

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101.0,Widget A,2.0,2025-05-01 00:00:00
1,1,John Doe,john@example.com,103.0,Widget C,3.0,2025-05-03 00:00:00
2,2,Jane Smith,jane@example.com,102.0,Widget B,1.0,2025-05-02 00:00:00
3,3,Bob Johnson,bob@office.com,104.0,Widget A,1.0,2025-05-04 00:00:00
4,4,Alice Brown,alice@mydomain.com,105.0,Widget B,2.0,2025-05-05 00:00:00
5,5,Dua Lipa,dua@example.com,NaN,NaN,NaN,NaN

In [27]:
# right join
customers.merge(orders, on="customer_id", how="right")

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101,Widget A,2,2025-05-01 00:00:00
1,2,Jane Smith,jane@example.com,102,Widget B,1,2025-05-02 00:00:00
2,1,John Doe,john@example.com,103,Widget C,3,2025-05-03 00:00:00
3,3,Bob Johnson,bob@office.com,104,Widget A,1,2025-05-04 00:00:00
4,4,Alice Brown,alice@mydomain.com,105,Widget B,2,2025-05-05 00:00:00
5,6,NaN,NaN,106,Widget D,1,2025-05-06

In [28]:
# full outer join
pd.merge(customers, orders, on="customer_id", how="outer")

,customer_id,name,email,order_id,product,quantity,order_date
0,1,John Doe,john@example.com,101.0,Widget A,2.0,2025-05-01 00:00:00
1,1,John Doe,john@example.com,103.0,Widget C,3.0,2025-05-03 00:00:00
2,2,Jane Smith,jane@example.com,102.0,Widget B,1.0,2025-05-02 00:00:00
3,3,Bob Johnson,bob@office.com,104.0,Widget A,1.0,2025-05-04 00:00:00
4,4,Alice Brown,alice@mydomain.com,105.0,Widget B,2.0,2025-05-05 00:00:00
5,5,Dua Lipa,dua@example.com,NaN,NaN,NaN,NaN
6,6,NaN,NaN,106.0,Widget D,1.0,2025-05-06